### ISSUE TITLE
jdk9 JAVA_HOME has no conf directory, causes crypto classes to fail since they can't find "unlimited" policy

### ISSUE THREAD

**Issue by hossman** [docker-library/openjdk#101]
I suspect this is an upstream packaging problem, but i'm not very familiar with how debian packaging of the JVM is *designed* to work, so filing this here...

when using openjdk:9-b158-jdk (current latest) images, there is not "conf" dir in JAVA_HOME, so when Crypto classes atempt to acces the (default) "unlimited" crypto policy they fail hard.

All of the files/directories that the Crypto classes seem to be looking for are (oddly) in the "lib" dir -- symlinking "conf" to "lib" seems to make everything happy.

You can see a quick and easy demonstration if you create a directory with the following two files...

```
# NAME THIS FILE Dockerfile -*- mode: Shell-script -*-

FROM    openjdk:9-b158-jdk

ENV JAVA_CONF_DIR=$JAVA_HOME/conf

# To see work around for bug, uncomment this line...
#RUN bash -c '([[ ! -d $JAVA_SECURITY_DIR ]] && ln -s $JAVA_HOME/lib $JAVA_HOME/conf) || (echo "Found java conf dir, package has been fixed, remove this hack"; exit -1)'

RUN mkdir -p /tmp/java-test
COPY Test.java /tmp/java-test/Test.java

RUN bash -c 'cd /tmp/java-test && javac Test.java && java -cp . Test'
```

```
// NAME THIS FILE Test.java
import javax.crypto.Cipher;

public class Test {
    public static void main(String args[]) throws Exception {
        if (Integer.MAX_VALUE != Cipher.getMaxAllowedKeyLength("RC5")) {
            System.exit(-1);
        }
    }
}
```

And then run `docker build -t test/docker-jdk9-jce-bug:latest .` ...

```
hossman@tray:~/tmp/docker-jdk9-jce-bug$ docker build -t test/docker-jdk9-jce-bug:latest .
Sending build context to Docker daemon 3.072 kB
Sending build context to Docker daemon 
Step 0 : FROM openjdk:9-b158-jdk
 ---> 43b5ff2ff057
Step 1 : ENV JAVA_CONF_DIR $JAVA_HOME/conf
 ---> Using cache
 ---> 46bf6fed11b9
Step 2 : RUN mkdir -p /tmp/java-test
 ---> Using cache
 ---> 5c54a92ee82b
Step 3 : COPY Test.java /tmp/java-test/Test.java
 ---> 7b14ddbe90b2
Removing intermediate container e6df7278a502
Step 4 : RUN bash -c 'cd /tmp/java-test && javac Test.java && java -cp . Test'
 ---> Running in 3804d17bf396
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.base/javax.crypto.JceSecurityManager.<clinit>(JceSecurityManager.java:66)
	at java.base/javax.crypto.Cipher.getConfiguredPermission(Cipher.java:2610)
	at java.base/javax.crypto.Cipher.getMaxAllowedKeyLength(Cipher.java:2634)
	at Test.main(Test.java:6)
Caused by: java.lang.SecurityException: Can not initialize cryptographic mechanism
	at java.base/javax.crypto.JceSecurity.<clinit>(JceSecurity.java:118)
	... 4 more
Caused by: java.lang.SecurityException: Can't read cryptographic policy directory: unlimited
	at java.base/javax.crypto.JceSecurity.setupJurisdictionPolicies(JceSecurity.java:324)
	at java.base/javax.crypto.JceSecurity.access$000(JceSecurity.java:73)
	at java.base/javax.crypto.JceSecurity$1.run(JceSecurity.java:109)
	at java.base/javax.crypto.JceSecurity$1.run(JceSecurity.java:106)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.crypto.JceSecurity.<clinit>(JceSecurity.java:105)
	... 4 more
INFO[0002] The command [/bin/sh -c bash -c 'cd /tmp/java-test && javac Test.java && java -cp . Test'] returned a non-zero code: 1 

```

If you uncomment the indicated workaround line of the Dockerfile, Crypto starts working properly and the image can be built.

**Comment by keeganwitt** [comment]
Thanks for the workaround!

**Comment by FauxFaux** [comment]
I've raised this with Debian as http://bugs.debian.org/866924. Please do file bugs with Debian for this kind of thing, we care, honest!

**Comment by tianon** [comment]
Thanks @FauxFaux ❤️ 👍

**Comment by sellersj** [comment]
I can't confirm, but it looks like it is fixed in the current version of jdk 9. Debian says fixed in 9~b177-2 and current docker image seems to be 9b181-4.

**Comment by tianon** [comment]
Yay, thanks @sellersj! (and thanks again @FauxFaux for filing upstream :+1:)

**Comment by juaninse** [comment]
The fix does not work for me. Symlinking conf to lib in  the /usr/lib/jvm/default-java directory does nothing. I am using Ubuntu 17.04. The strangest thing is that this problem appeared suddenly, two days ago. In the morning everything was OK, and later in the afternoon the problem appeared. I did not apply any updates that day before this happened.

There is no JAVA_HOME environment defined, although even if I define it to point to any of the versions on /usr/lib/jvm the problem persists, with or without symlinking a conf directory to the lib directory.

Any other useful tips on a fix to the problem?

**Comment by hossman** [comment]
the upstream bug was fixed a while ago -- i suspect you are either seeing a diff problem, or a new (packaging?) problem that manifests with similar symptoms (particularly if you aren't seeing JAVA_HOME defined at all)

I would suggest you create a new issue with your specifics (Dockerfile showing base image name & version, steps to reproduce including java code, detailed error message, etc...) similar to what I posted when this issue #101 was created
