### ISSUE TITLE
jdk-nanoserver executing command

### ISSUE THREAD

**Issue by ferpegaplain** [docker-library/openjdk#105]
Hello, I am testing openjdk:jdk-nanoserver with a basic HelloWorld.java.

If I put my commands on a dockerfile all is fine.  But if I try to execute all of them in a command line, then I have problems with commands passed into -c argument.

This is my executing line (mintty command prompt on Windows 10):
`winpty docker run -it -v /c:/MyHostFolder/java/helloworld:c:/app --workdir c:/app openjdk:jdk-nanoserver -c "javac HelloWorld & java HelloWorld"`

And this is the error I get:

> docker: Error response from daemon: container 3678d0841b468a105d3653143b62a9699d6607e4e2a0c13e7dd142e497752509 encountered an error during CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2) extra info: {"ApplicationName":"",
> "CommandLine":"-c \"javac HelloWorld \u0026 java HelloWorld\"","User":"","WorkingDirectory":"c:\\app","Environment":{"JAVA_HOME":"C:\\ojdkbuild","JAVA_OJDKBUILD_SHA256":"68476588b135a2ad9030567ab90368c36f5eb1f20bedffac9619bbcda5e3575b","JAVA_OJDKBUILD_VERSION":"1.8.0.121
> -1","JAVA_OJDKBUILD_ZIP":"java-1.8.0-openjdk-1.8.0.121-1.b13.ojdkbuild.windows.x86_64.zip","JAVA_VERSION":"8u121"},"EmulateConsole":true,"CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":false,"ConsoleSize":[85,271]}.

If I only execute the line without tty+interactive connection and only a command parameter, like this:
`docker run -v /c:/WorkingGit/docker/java/helloworld:c:/app --workdir c:/app openjdk:jdk-nanoserver -c "javac HelloWorld"`

The error is the same.

Any help would be welcome.  Sorry if this is not the place to request for help.

Thanks.

**Comment by yosifkit** [comment]
There is no entrypoint script in the image that would take your two arguments `-c "javac HelloWorld & java HelloWorld", so the container is literally looking for the executable `-c`.  I think what you really need is `docker run .... openjdk:jdk-nanoserver cmd -c "javac HelloWorld & java HelloWorld"`

**Comment by ferpegaplain** [comment]
You give me the clue.  Thanks.  :-)

Finally this is the good command (from a mintty command prompt terminal):

`winpty docker run -it --rm -v /c:/MyHostFolder/java/helloworld:c:/app --workdir c:/app openjdk:jdk-nanoserver cmd //c "javac HelloWorld.java & java HelloWorld"`

Thanks again.
