### ISSUE TITLE
Release Java SE 8u131

### ISSUE THREAD

**Issue by TamalSaha** [docker-library/openjdk#108]
https://blogs.oracle.com/java/java-se-8-update-131

**Comment by yosifkit** [comment]
For the Debian based images we have to wait for the version to be bumped in [jessie-backports](https://packages.debian.org/jessie-backports/openjdk-8-jre-headless) (and it is not even in sid/unstable yet).  For the Alpine based images, we have to wait for a bump there as well: [alpine 3.5](https://pkgs.alpinelinux.org/package/v3.5/community/x86_64/openjdk8-jre).

**Comment by tianon** [comment]
Indeed, given that OpenJDK is very complicated to build from source, we're at the mercy of our associated upstreams here. :disappointed:

FWIW, the Windows variants have updated to 8u131 in https://github.com/docker-library/openjdk/commit/9745c87a15896ec558429a826e23926e721e4846. :+1:
