### ISSUE TITLE
Apt does not know about installed openjdk 8 jre (tag 8-jre)

### ISSUE THREAD

**Issue by hugoverne** [docker-library/openjdk#109]
I am building my docker container from `openjdk:8-jre`. After running `apt-get update` on the docker container I tried to install openjfx by running `apt-get install openjfx`. I got the error

> The following packages have unmet dependencies:
> openjfx : Depends: openjdk-8-jre but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.

Running `apt-cache policy openjdk-8-jre` results in

> openjdk-8-jre:
>  Installed: (none)
>  Candidate: 8u121-b13-1\~bpo8+1
>  Version table:
>           8u121-b13-1~bpo8+1 0
>           100 http://deb.debian.org/debian/ jessie-backports/main amd64 Packages

The docker image obviously has openjdk 8 jre installed. But shouldn't aptitude know about that? How else could I install packages depending on openjdk 8 jre?

**Comment by yosifkit** [comment]
We haven't installed `openjdk-8-jre`; we install `openjdk-8-jre-headless` to make it a little slimmer.  I am unable to reproduce the error when trying to install `openjfx`.

Perhaps your image contains a slightly older `openjdk-8-jre-headless`. Have you pulled the image recently?

**Comment by hugoverne** [comment]
Thank you for your help! After pulling the newest version of the image, the issue disappeared (mine was 3 month old i guess). I was able to install openjfx.
