### ISSUE TITLE
Mitigating vulnerabilities / CVE's reported by Docker Hub scans

### ISSUE THREAD

**Issue by mdeguzis** [docker-library/openjdk#112]
All of the images have vulnerabilities listed of some number/type. It is concerning to large organizations I would think. How are these treated/tracked/mitigated? You can reference these from the tags page on Docker Hub after logging in.

Some examples for 8-ire used by jenkins:

glibc 2.19-18+deb8u7 
selinux 2.3-2
systemd 215-17+deb8u6
pcre 8.35-3.3+deb8u4
...

**Comment by yosifkit** [comment]
Basically the same as https://github.com/docker-library/postgres/issues/286

Related issues:
https://github.com/docker-library/drupal/issues/84
https://github.com/docker-library/official-images/issues/2740
https://github.com/docker-library/ruby/issues/117
https://github.com/docker-library/ruby/issues/94
https://github.com/docker-library/python/issues/152
https://github.com/docker-library/php/issues/242
https://github.com/docker-library/buildpack-deps/issues/46
