### ISSUE TITLE
I cannot find a 'jar' executable.

### ISSUE THREAD

**Issue by bryanjbelanger** [docker-library/openjdk#113]
I believe the jar executable is standard on a JDK deployment.

**Comment by tianon** [comment]
Aren't jars normally run via `java -jar ...`?  I don't think I've ever seen a `jar` executable used. :confused:

**Comment by bryanjbelanger** [comment]
That is the correct method to execute a jar file.

‘jar’, the executable, is the utility for creating and extracting jars and their associated metadata.

Thanks,

Bryan

On May 4, 2017, at 12:01 PM, Tianon Gravi <notifications@github.com<mailto:notifications@github.com>> wrote:


Aren't jars normally run via java -jar ...? I don't think I've ever seen a jar executable used. 😕

**Comment by yosifkit** [comment]
The `jar` binary is only part of the `openjdk-*-jdk` packages from Debian and Alpine, so it will only be in the `jdk` variants of the images, not the `jre` images: `openjdk:6-jdk`, `openjdk:7-jdk`, `openjdk:7-jdk-alpine`, `openjdk:8-jdk`, `openjdk:8-jdk-alpine`, `openjdk:9-jdk`.

**Comment by tianon** [comment]
Closing, since this is solved (use the `-jdk` variants of the image to have the `jar` binary). :+1:
