### ISSUE TITLE
No 8u131 JRE image for windows?

### ISSUE THREAD

**Issue by danbrandow** [docker-library/openjdk#119]
I did not see a 8u131 JRE image for windows. Will one be in the works?

Many thanks.

**Comment by tianon** [comment]
On Windows, we consume the [releases from the "ojdkbuild" project](https://github.com/ojdkbuild/ojdkbuild/releases), which as I understand only releases the JDK (no JRE-only releases).  If I'm mistaken about that, having JRE-only variants would be nice!

**Comment by tianon** [comment]
Closing since there's not really anything we can do from here -- if ojdkbuild (or OpenJDK upstream directly) were to start creating JRE-only Windows releases, we could then consume them. :+1:
