### ISSUE TITLE
Downgrade to alpine 3.5 or offer a choice?

### ISSUE THREAD

**Issue by cen1** [docker-library/openjdk#120]
Breaking several Java apps https://bugs.alpinelinux.org/issues/7372

**Comment by yosifkit** [comment]
It is tied to the version bump from 8u121 to 8u131, so if you can't use Alpine 3.6 yet, then just use 8u121. (https://github.com/docker-library/openjdk/pull/118)

**Comment by cen1** [comment]
Fair enough
