### ISSUE TITLE
rpm utility in openjdk docker image

### ISSUE THREAD

**Issue by ravi567** [docker-library/openjdk#122]
Hi: I built a docker image using openjdk. I need the rpm utility included to install a few other things and this image doesn't seem to have it. What do I include in the Dockerfile to include the rpm utility?

Thanks
Ravi

**Comment by yosifkit** [comment]
This is a Debian, Alpine, or Windowsservercore/Nanoserver based image, so it has apt, apk, or powershell, respectively.

**Comment by ravi567** [comment]
I am trying to install MQ client and the only option I have to install it is using rpm. Is there a way around or would I need to look for a different docker image?

**Comment by yosifkit** [comment]
You can use apt to install rpm. Are you following this [howto](https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_8.0.0/com.ibm.mq.ins.doc/q115255_.htm)?  Maybe the [ibmjava](https://hub.docker.com/_/ibmjava/) official image would be helpful with that?

**Comment by ravi567** [comment]
thank you. That howto link helped.
