### ISSUE TITLE
Changing to Debian 9 on existing tags

### ISSUE THREAD

**Issue by royletron** [docker-library/openjdk#126]
Hey JDK'ers. I am using the openjdk Docker images via the Maven Docker images and I have been chasing a bug that has been introduced because of this change:

https://github.com/docker-library/openjdk/commit/502f18c2a34cb4a6f50ca6943a82e9a0b18f4254

Essentially our product that lives inside this image is failing because of a change in version of the openssl package (because of the upgrade to Debian 9). Is it normal practice to update an existing tag in such a fundamental way?

**Comment by yosifkit** [comment]
Yes, this comment is applicable: https://github.com/docker-library/openjdk/issues/125#issuecomment-314193929

**Comment by tianon** [comment]
Closing given https://github.com/docker-library/openjdk/issues/125#issuecomment-314193929, which is also linked above and embedded below for reference:

> When we evaluated the decision, we decided it was either update the base image or not have any more java updates.  But, we do keep a recorded history of every image by their full sha256 digest in https://github.com/docker-library/repo-info/, so you can find past openjdk 8 images in https://github.com/docker-library/repo-info/blob/master/repos/openjdk/remote/8.md (just look at the git history to find the old sha 256 digests that referred to openjdk 8).
