### ISSUE TITLE
Is there a way to add certificates into cacerts

### ISSUE THREAD

**Issue by lourdufelix** [docker-library/openjdk#127]
I am using this image to build java application in drone and I get ssl errors because the certificates are not available. Is there a way to add certificates into this image before building the app?

**Comment by nicorevin** [comment]
```dockerfile
FROM openjdk

COPY cert.crt /anywhere

RUN cat /anywhere/cacert.crt | \
    tee -a /etc/ssl/certs/ca-certificates.crt | \
    keytool -importcert -trustcacerts -keystore /etc/ssl/certs/java/cacerts -noprompt -storepass changeit -alias mycert
```

**Comment by lourdufelix** [comment]
Thank Nick. I kind of figured it and resolved my issue.  but I used curl command to import the certificate into the image.
