### ISSUE TITLE
openjdk arm32v5

### ISSUE THREAD

**Issue by yosifkit** [docker-library/openjdk#128]
It is currently unable to build since it is not available on the Debian archives. Most recent build attempt: https://doi-janky.infosiftr.net/job/multiarch/view/images/view/openjdk/job/arm32v5/job/openjdk/.

Here is the bug report in Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=864464.  It is important to note: `Server VM is only supported on ARMv7+ VFP`.

So, the current plan is that if it becomes available in Debian, then we'll push the image. :smile:

**Comment by tianon** [comment]
This has been building successfully for a while now. :smile: (https://hub.docker.com/r/arm32v5/openjdk/)
