### ISSUE TITLE
Recent change breaks java

### ISSUE THREAD

**Issue by rstrauss** [docker-library/openjdk#129]
The recent change breaks java:
 - Commits on Jul 5, 2017 - @tianon -- `Also adjust "update.sh", drop "jessie-backports", and bump versions`

Write a tiny program, to run inside the docker image, that does:
    `UIManager.getFont("Label.font").getFamily();`

This worked since June 6th, but broke when we started after the July 5th change.

**Comment by yosifkit** [comment]
This is related to https://github.com/docker-library/openjdk/issues/125#issuecomment-314193929, but I hope this is just a missing package install.

**Comment by rstrauss** [comment]
I don't know. Is there a way to induce them to add a small java program to their tests?

**Comment by yosifkit** [comment]
I would love some basic java program tests.  If you have a some simple ones, we could add them in [docker-library/official-images/test](https://github.com/docker-library/official-images/tree/master/test).  They would get run on each PR here since they are used in the travis.yml.

**Comment by rstrauss** [comment]
Here is a simple test of the UIManager functions. It wouldn't let me attach a .java file, so I added a .txt extension.  Thanks!

You probably know how to compile and run java programs.

In a version with jdk, you can do these two commands:

`javac UIManagerInitTest.java ; java -cp . UIManagerInitTest`

But this docker image only has the jre, so I think you have to compile it first, then put the class file into the docker image and do the second command.

[UIManagerInitTest.java.txt](https://github.com/docker-library/openjdk/files/1146941/UIManagerInitTest.java.txt)

**Comment by adam-sandor** [comment]
Any updates on this one. We are stuck with using `FROM tomcat@sha256:c55c84d34b82d794298bb7ee8c70f52f9dfcd1bd34106394b2bc99ed60216f16` which is not a long-term solution.
