### ISSUE TITLE
Why aren't openjdk:8 installing headless like openjdk:8-jre?

### ISSUE THREAD

**Issue by bjornbak** [docker-library/openjdk#130]
The openjdk:8 Dockerfile installs a complete openjdk including all the GUI tools:

apt-get install -y \
		openjdk-8-jdk="$JAVA_DEBIAN_VERSION" \
		ca-certificates-java="$CA_CERTIFICATES_JAVA_VERSION" \
	;

while openjdk:8-jre only installs the headless:

	apt-get install -y \
		openjdk-8-jre-headless="$JAVA_DEBIAN_VERSION" \
		ca-certificates-java="$CA_CERTIFICATES_JAVA_VERSION" \
	; \

I believe most people run docker in a headless facon so please install openjdk-8-jdk-headless instead.

**Comment by tianon** [comment]
I think the reason we didn't use that originally is that `openjdk-7-jdk-headless` doesn't exist.  I'm +1 on making the change, but we've seen a lot of backlash from #124, so I'd be hesitant on those grounds (since this is something that's likely to break some folks' usage).

**Comment by bjornbak** [comment]
Hi Tianon,

In #131 I suggest to do variants based on debian slim maybe these two can be combined creating new slim variants which install headless. This way people like me who want a small glibc image can opt for the slim vairants while people who wants it all or have legacy requirements can stick with the old one...

**Comment by tianon** [comment]
Ooh, that's a neat thought -- we could even then consider expanding the
normal JRE variant to non-headless for issues like #129.

**Comment by tianon** [comment]
Half of this was fixed in #133 and the other half in #143. :+1:
