### ISSUE TITLE
how to change timezone

### ISSUE THREAD

**Issue by FrankJian** [docker-library/openjdk#134]
hello , in the images , the default timezone is UTC, how to change it when run an java app, such as jenkins ?
thanks.

**Comment by pcornelissen** [comment]
You could do something like this:

```
# Pull base image.
FROM openjdk:8
MAINTAINER $YOU

RUN echo "Europe/Berlin" > /etc/timezone && dpkg-reconfigure -f noninteractive tzdata
...
```

**Comment by tianon** [comment]
You should also be able to set the `TZ` environment variable via something like either `ENV TZ America/Denver` or `-e TZ=America/Denver`.

**Comment by tianon** [comment]
See also https://github.com/docker-library/openjdk/issues/80#issuecomment-355136567.
