### ISSUE TITLE
Update alpine jre to 8u141

### ISSUE THREAD

**Issue by mrcasablr** [docker-library/openjdk#136]
I do not see alpine jre images for 8u141. Is this planned to be released soon?

**Comment by fpavageau** [comment]
Or even 8u144.

**Comment by yosifkit** [comment]
Currently, the only version available in Alpine 3.6 is `8u131`.  While `8u141` is available in the Alpine edge channel, I'm am unable to pull in just openjdk8 from edge and I definitely don't want to move the image to be `FROM alpine:edge`.

> End users should not use "edge" as their main day-to-day workstation or as productive system. Because "edge" is a development branch, many changes are not heavily tested (or tested at all) and packages in "edge" can and sometimes do break without warning.
>
> \- https://wiki.alpinelinux.org/wiki/Edge

Following are snippets from my tries. It might be possible to get Alpine to bump the version of openjdk available in Alpine 3.6, but I don't know the ramifications to other packages in Alpine.
```Dockerfile
FROM alpine:3.6

ENV JAVA_VERSION 8u141
ENV JAVA_ALPINE_VERSION 8.141.15-r0

RUN set -ex; \
	echo '@edge http://dl-cdn.alpinelinux.org/alpine/edge/main' >> /etc/apk/repositories; \
	apk add --no-cache \
		openjdk8@edge="$JAVA_ALPINE_VERSION";

# I even tried adding in all the jdk specific dependencies:
RUN set -ex; \
	echo '@edge http://dl-cdn.alpinelinux.org/alpine/edge/main' >> /etc/apk/repositories; \
	apk add --no-cache \
		openjdk8-jre@edge="$JAVA_ALPINE_VERSION" \
		openjdk8-jre-base@edge="$JAVA_ALPINE_VERSION" \
		openjdk8-jre-lib@edge="$JAVA_ALPINE_VERSION" \
		java-cacerts@edge \
		openjdk8@edge="$JAVA_ALPINE_VERSION"; \

# both of these run lines fail with "ERROR: unsatisfiable constraints:"
```

**Comment by jhovell** [comment]
JDK/Alpine 8u131 issue being tracked on Alpine's bug tracker:

https://bugs.alpinelinux.org/issues/7372

**Comment by shatil** [comment]
@fpavageau you might already know this, but for anyone else like me stumbling upon this thread: unlike some other Docker Hub-hosted images, this `8-alpine` and its variants install the distribution-provided JDK or JRE. In this case, it's coming from Alpine Linux 3.6, which shipped OpenJDK 8u131.

If Alpine Linux's "edge" release is cut as 3.7, then we'll end up with 8u144: https://pkgs.alpinelinux.org/packages?name=openjdk8&branch=edge&repo=&arch=x86_64&maintainer=

Release date for 3.7 is supposed to be November: https://bugs.alpinelinux.org/projects/alpine/roadmap#3.7.0

While the Alpine variants of JDK and JRE are much, much smaller (80ish MiB vs. 207 for the `8-jre-slim`, even), patches are few and far between. It was back in July that [Java 8 Update 144 was released](https://blogs.oracle.com/java/java-se-8-update-144) and here we are 3+ months later.

**Comment by tianon** [comment]
The OpenJDK 8 Alpine variants have since moved to Alpine 3.7, and thus 8u151 and this no longer applies. :+1:
