### ISSUE TITLE
openjdk-6-jdk on buildpack-deps:jessie

### ISSUE THREAD

**Issue by hermanzdosilovic** [docker-library/openjdk#137]
Is there a way to install openjdk-6-jdk package on `buildpack-deps:jessie`? I have figured out from history of your Dockerfiles how to install openjdk-7-jdk and openjdk-8-jdk on the same `buildpack-deps:jessie` but now I would like to know if I can also install openjdk-6-jdk and/or even openjdk-9-jdk on `buildpack-deps:jessie`.

Thanks in advance!

**Comment by yosifkit** [comment]
Unfortunately not. The `openjdk-6-*` packages are only available in `wheezy` and the `openjdk-9-*` packages are only available in `testing`.

https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=openjdk

**Comment by hermanzdosilovic** [comment]
Thanks!
:disappointed:
