### ISSUE TITLE
Update to 8u144?

### ISSUE THREAD

**Issue by volphy** [docker-library/openjdk#140]
Is update to 8u144 planned to be added soon?

Are there any obstacles preventing it?

**Comment by tianon** [comment]
We pull OpenJDK from Debian and Alpine's package repositories (as can be seen in the relevant `Dockerfile` for each variant), so we cannot package a version which they do not contain.

**Comment by joelbirchler** [comment]
The obstacle is upstream with Alpine. The openjdk package is only available on the edge channel. https://pkgs.alpinelinux.org/package/edge/community/x86/openjdk8

**Comment by dja-fr** [comment]
Hello,
It seem that alpine update the package version of java to 8u144 ( Build time | 2017-09-24 07:51:18 ).
Is it possible to reconsider this issue ?

thx

**Comment by tianon** [comment]
Both Debian and Alpine are currently at 8u151. :+1:
