### ISSUE TITLE
JAVA_HOME pointing to JRE in openjdk:9-jdk

### ISSUE THREAD

**Issue by aiannucci** [docker-library/openjdk#144]
When trying to create container based on the Dockerfile provided, JAVA_HOME seems to be set to JRE instead of JDK:

```
JAVA_DEBIAN_VERSION=9~b181-4
JAVA_HOME=/usr/lib/jvm/jre
JAVA_VERSION=9-b181
```

Of course when I try to run for instance a Maven build, it fails with the following output:

```
The JAVA_HOME environment variable is not defined correctly
This environment variable is needed to run this program
NB: JAVA_HOME should point to a JDK not a JRE
```

**Comment by yosifkit** [comment]
I am unable to reproduce in the image. The Dockerfile sets `JAVA_HOME` to `/docker-java-home`, which itself is a symlink to `/usr/lib/jvm/java-9-openjdk-amd64`. Do you have something else running before java that might be changing env vars?

https://github.com/docker-library/openjdk/blob/7bd5c28e1ade462bfcc4a49f237023dfd2330b8f/9-jdk/Dockerfile#L39-L40

```console
$ docker run -it --rm openjdk:9-jdk bash
Unable to find image 'openjdk:9-jdk' locally
9-jdk: Pulling from library/openjdk
b5499bef70c5: Already exists 
f0aefbd8335b: Pull complete 
0c86784c73ea: Pull complete 
3308601cadb7: Pull complete 
89af2b318efb: Pull complete 
46023e7743d9: Pull complete 
40d47966cab2: Pull complete 
9a1e39ea93da: Pull complete 
Digest: sha256:2f4bd5ee05dc1fa67be90bcded03e0da0c4a081235221de07971677b9bee5ca8
Status: Downloaded newer image for openjdk:9-jdk
root@a635978f55d9:/# env | grep -i java
JAVA_HOME=/docker-java-home
JAVA_VERSION=9-b181
JAVA_DEBIAN_VERSION=9~b181-4
root@a635978f55d9:/# ls -la "$JAVA_HOME"
lrwxrwxrwx 1 root root 33 Aug 25 21:04 /docker-java-home -> /usr/lib/jvm/java-9-openjdk-amd64
root@a635978f55d9:/# 
```

**Comment by aiannucci** [comment]
Trying to use this image with Jenkins Docker plugin and it seems JAVA_HOME environment variable needs to be overwritten manually. Closing this one now. Thanks!
