### ISSUE TITLE
Update openjdk docker to java 8u151

### ISSUE THREAD

**Issue by sauravgarg** [docker-library/openjdk#150]
By when can we expect openjdk docker to be updated to java 8u151?

**Comment by tianon** [comment]
This has been asked a few times before; see https://github.com/docker-library/openjdk/issues/140 for a semi-recent example.

We consume OpenJDK from the distro packages for several reasons:

https://github.com/docker-library/openjdk/blob/7bd5c28e1ade462bfcc4a49f237023dfd2330b8f/8-jdk/Dockerfile#L8-L18

(Build time and complexity of OpenJDK being the main driver.)

Thus, we're beholden to each distribution (Debian, Alpine, and the ojdkbuild project) for platform updates.

**Comment by dja-fr** [comment]
Hello,

Just for information I opened a ticket on alpine bug tracker's for this subject : https://bugs.alpinelinux.org/issues/8018
I hope they will update the package on 3.6 branch (The last time for u144 they just updated the edge).

**Comment by carlossg** [comment]
@tianon given the delay on the alpine side would a `8u151-jdk-alpine-edge` tag be acceptable? 

I gave it a quick try and seems to work, I can submit the PR

```
diff --git a/8-jdk/alpine/Dockerfile b/8-jdk/alpine/Dockerfile
index c2a537b..31f032f 100644
--- a/8-jdk/alpine/Dockerfile
+++ b/8-jdk/alpine/Dockerfile
@@ -4,7 +4,7 @@
 # PLEASE DO NOT EDIT IT DIRECTLY.
 #

-FROM alpine:3.6
+FROM alpine:edge

 # A few reasons for installing distribution-provided OpenJDK:
 #
@@ -31,8 +31,8 @@ RUN { \
 ENV JAVA_HOME /usr/lib/jvm/java-1.8-openjdk
 ENV PATH $PATH:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin

-ENV JAVA_VERSION 8u131
-ENV JAVA_ALPINE_VERSION 8.131.11-r2
+ENV JAVA_VERSION 8u151
+ENV JAVA_ALPINE_VERSION 8.151.12-r0

 RUN set -x \
        && apk add --no-cache \
```

**Comment by wrporter** [comment]
@tianon It looks like Alpine just released 3.7! Can this get updated now? https://alpinelinux.org/posts/Alpine-3.7.0-released.html

**Comment by wrporter** [comment]
There is now a pull request for the docker alpine update https://github.com/docker-library/official-images/pull/3762

**Comment by wrporter** [comment]
There is now an official docker image for alpine 3.7 https://hub.docker.com/_/alpine/

**Comment by wrporter** [comment]
@tianon or anyone else that has merge permission. I submitted a pull request. https://github.com/docker-library/openjdk/pull/155

**Comment by tianon** [comment]
Both Debian and Alpine are currently at 8u151. :+1:
