### ISSUE TITLE
supervisord stopped working properly 

### ISSUE THREAD

**Issue by sdudui1804** [docker-library/openjdk#154]
I was building my container  "FROM openjdk:8-jre. The last changes break the functionality of supervisord. 

Supervisord cannot push anymore the system environment variables to the process. 
The configuration line *environment* does not work anymore:

`[program:etl_test]`
`command=....`
`environment=http.proxySet="test"`

I had to downgrade   to openjdk:8u121-jre.

Thank you,
Sorin

**Comment by yosifkit** [comment]
I am not sure what "last changes" you would be referring to. What is the sha256 digests of the working and not working images (`docker images --digests openjdk`)?

**Comment by sdudui1804** [comment]
![grafik](https://user-images.githubusercontent.com/34056596/33418202-0df79fb0-d5a5-11e7-8ff0-aa9d1d6c8b74.png)

The 8u121-jre works correctly. The 8-jre not. 

We are using the "environment" configuration in supervisor to tell the process that a http proxy is present. In the log file we can see that with the 8-jre the environment variables are no set.  Also by listing of  /proc/<pid</environ. 

Thank you.

**Comment by sdudui1804** [comment]
Hi,

I really cannot explain it. I wanted today to reproduce the issue and I cannot anymore, even we did no changes to the compose file.   I suggest to close the issue for the moment,

Thank you,
Sorin
