### ISSUE TITLE
8u151 alpine image not signed

### ISSUE THREAD

**Issue by wrporter** [docker-library/openjdk#156]
When pulling with docker content trust enabled, I get an error message stating that there is not trust data for 8u151-jdk-alpine and 8u151-jre-alpine. Is there any reason why this latest update was not signed? Can someone who has access publish a new signed version?

**Comment by wrporter** [comment]
@yosifkit You worked on merging my pull request. Do you have any insights here?

**Comment by wrporter** [comment]
Just to be clear what I mean by this ticket, I get the following output.

```
$ docker build --disable-content-trust=false .
Sending build context to Docker daemon

error during connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.32/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=ddc6c2edbd84f8208fd7b0ec762126af8db6c436ba66aeceb2d42f5f1a2e2140&shmsize=0&target=&ulimits=null: No trust data for 8u151-jdk-alpine
```

With a Dockerfile that has the following

```
FROM openjdk:8u151-jdk-alpine
```

**Comment by yosifkit** [comment]
The signing of images (along with vulnerability scanning) is a queue that is processed as official images get pushed to Docker Hub.  It is controlled by Docker Inc.  cc @toli who currently oversees the process; was there a hiccup in the queue?

**Comment by tianon** [comment]
Closing since there's unfortunately nothing more we can do here.  Sorry!
