### ISSUE TITLE
Update to alpine jre 8u161 

### ISSUE THREAD

**Issue by mrcasablr** [docker-library/openjdk#164]
Is this dependent on upstream alpine 3.7 to update first?

**Comment by yosifkit** [comment]
Correct, for the alpine based images, we are beholden to updates in Alpine Linux.

See also https://github.com/docker-library/openjdk/issues/150#issuecomment-338713389.

**Comment by owennewo** [comment]
Does this alpine commit (from 23 days ago) mean that `openjdk/8-jdk/alpine` can be updated to 8u161`
https://bugs.alpinelinux.org/issues/8667
There is a known security issue in 8u151

**Comment by yosifkit** [comment]
Unfortunately not unless we want to switch to the `edge` alpine release.  We'll have to wait until Alpine 3.8 or if they happen to backport it to 3.7.

https://pkgs.alpinelinux.org/packages?name=openjdk8&branch=edge
https://pkgs.alpinelinux.org/packages?name=openjdk8&branch=v3.7
