### ISSUE TITLE
openjdk:8 is not finding rt.jar

### ISSUE THREAD

**Issue by JavierTorres** [docker-library/openjdk#169]
Hi guys,
I was wondering if you could help with that. If I pull openjdk:8 (Image id: sha256:db77212ffe0598207c9d1024d86b64abc332382ebb459c48fd5d5631a4cf2287), Java is not running as it can't find the library /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar. Could you please have a look?

Thanks.

`$ docker run openjdk:8 java -version

Error occurred during initialization of VM
java/lang/ClassNotFoundException: error in opening JAR file /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar
`

**Comment by yosifkit** [comment]
I am unable to reproduce. It is probably a corrupt image; delete it and pull again.

```console
$ docker pull openjdk:8
8: Pulling from library/openjdk
3e731ddb7fc9: Pull complete 
47cafa6a79d0: Pull complete 
79fcf5a213c7: Pull complete 
68e99216b7ad: Pull complete 
0e688b2d7215: Pull complete 
b3e9ec3ed749: Pull complete 
dcd3ba267864: Pull complete 
5672be24157f: Pull complete 
8c5307d6ff27: Pull complete 
Digest: sha256:27db23b865fb1691ea72e4ff5db27a442e97819d7a29b57dc7ea5ddc4cd1f210
Status: Downloaded newer image for openjdk:8
$ docker run --rm openjdk:8 java -version
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-1~deb9u1-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
```

**Comment by JavierTorres** [comment]
yes, you're right. thanks
