### ISSUE TITLE
CI failure for jdk-10-ea-46 on amd64

### ISSUE THREAD

**Issue by philwebb** [docker-library/openjdk#171]
It appears that the [CI build for jdk-10-ea-46](https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/openjdk/67/) triggered by [this commit](https://github.com/docker-library/official-images/commit/d5fbdb646cc52344691e529888978dbf2f5f39ee#diff-d98e87a890febc528e812418af0e02fc) has failed due to being cancelled:

```
ERROR: Queue task was cancelled
Finished: FAILURE
```

Is it possible to trigger the CI build again so that jdk-10-ea-46 can be published as an official Docker image?

**Comment by yosifkit** [comment]
Thanks and job started.

**Comment by wilkinsona** [comment]
Thank you, @yosifkit. We're now able to build an image using idk-10-ea-46.
