### ISSUE TITLE
Alpine for jdk10 ?

### ISSUE THREAD

**Issue by titoc** [docker-library/openjdk#177]
Is there a possibility of having alpine based images with jdk10 ?

Edit:
I understand that there is no support for openjdk9 and 10 packages in alpine yet.
https://pkgs.alpinelinux.org/packages?name=openjdk*&branch=edge
Maybe I should ask this question in alpine list.

**Comment by yosifkit** [comment]
Correct, there is currently nothing we can do in the image.

Swap 9 to 10 and this comment applies: https://github.com/docker-library/openjdk/issues/100#issuecomment-282149214.

Related/similar issues: #136, #140, https://github.com/docker-library/openjdk/issues/150#issuecomment-338713389, #151
