### ISSUE TITLE
Update to newer version of JDK 8u162

### ISSUE THREAD

**Issue by bdub85** [docker-library/openjdk#178]
Is it possible to update this image https://github.com/docker-library/openjdk/tree/master/8-jdk/alpine to use the latest version http://openjdk.java.net/projects/jdk8u/releases/8u162.html?

**Comment by tianon** [comment]
See https://github.com/docker-library/openjdk/issues/150#issuecomment-338713389.

If Alpine and Debian update, we will, but until then, it's not feasible for us to update.

In the case of the Debian-based images, we're already at 8u162 though. :+1:
