### ISSUE TITLE
Are you going to update the alpine jre image to 8u171?

### ISSUE THREAD

**Issue by PabloL007** [docker-library/openjdk#194]
I've been checking the tags on the docker hub page for a while but there hasn't been any update since u151, is this because of a limitation with Alpine?

**Comment by tianon** [comment]
See #178, https://github.com/docker-library/openjdk/issues/150#issuecomment-338713389, etc.

(Yes, it's a limitation of available pre-built packages in Alpine itself.)

**Comment by PabloL007** [comment]
Ok, thanks for the quick reply!

**Comment by J0WI** [comment]
See https://bugs.alpinelinux.org/issues/8853

**Comment by nasthu** [comment]
Alpine issue is now resolved ^

**Comment by yosifkit** [comment]
Nice, bot pushed the update in https://github.com/docker-library/openjdk/commit/dd54ae37bc44d19ecb5be702d36d664fed2c68e4. PR to official-images will be made soon.
