### ISSUE TITLE
All alpine images are missing

### ISSUE THREAD

**Issue by kishaningithub** [docker-library/openjdk#195]
In docker hub all the alpine images are missing.

Attaching the pdf of the web page here
[library_openjdk - Docker Hub.pdf](https://github.com/docker-library/openjdk/files/2003463/library_openjdk.-.Docker.Hub.pdf)

**Comment by yosifkit** [comment]
The tags page is not long enough to display all of the current tags and unfortunately doesn't have paging, but the images are there and pull just fine.  The place to look for which tags are actively maintained is not the tags page but the section in the description "Supported tags and respective Dockerfile links".

```console
$ docker pull openjdk:alpine
alpine: Pulling from library/openjdk
ff3a5c916c92: Already exists 
5de5f69f42d7: Pull complete 
fd869c8b9b59: Pull complete 
Digest: sha256:e82316151c501a2a0f73b3089da8dc867816470a464fcb191db9f88c2343ad53
Status: Downloaded newer image for openjdk:alpine
```
