### ISSUE TITLE
Curl or wget in image 

### ISSUE THREAD

**Issue by glfp** [docker-library/openjdk#196]
Hi, 

i'm using new openjdk:10.0.1-10-jre-slim image with some java microservice.

In order to activate the healthcheck from docker stack command, I need to run wget or curl on a internal endpoint (the java microservice).

Curl and WGet are missing from current images.

It's possibile to add in future release ? 

Thanks.

**Comment by tianon** [comment]
The `-slim` variants of the images intentionally don't include `wget`.  In fact, that's one of the main differentiators between `-slim` and non-`-slim` images.

You'll need to either install `wget` yourself or just use the non-slim images.
