### ISSUE TITLE
VM root password

### ISSUE THREAD

**Issue by norbertoritzmann** [docker-library/openjdk#205]
I neet to connect in VM of this docker image by SSH, but there is no password in any document, someone know this information?

**Comment by wglambert** [comment]
The image doesn't install ssh by default, you can add it yourself. By default the image has just the root user with no password. If you're exposing the container in such a way you would want to secure that.

`docker exec -it [image] bash`  is the preferred method of shell access. I don't know your setup but you could ssh to the vm and then `docker exec` in.

**Comment by norbertoritzmann** [comment]
Thanks @wglambert by your helpful answer. I needed to access the production image, that's why bash do not work.
I got it by changing the root password and installing ssh.
