### ISSUE TITLE
update.sh constantly failing

### ISSUE THREAD

**Issue by J0WI** [docker-library/openjdk#206]
Just a hint for @tianon that https://doi-janky.infosiftr.net/job/update.sh/job/openjdk/ is constantly failing and the `openjdk:7-*-alpine` variants lack [security updates](https://github.com/alpinelinux/aports/commit/c0566ebd84fc098e3cc50c1ae2a97fbf7577adaf).

**Comment by yosifkit** [comment]
Looks like 11-jdk is now failing with the following:

```console
  dpkg: error processing archive /var/cache/apt/archives/openjdk-11-jdk_11~19-1_amd64.deb (--unpack):
   trying to overwrite '/usr/lib/jvm/java-11-openjdk-amd64/bin/jconsole', which is also in package openjdk-11-jre-headless:amd64 11~19-1
```

Which is the same error found by Debian's automated testing ["piuparts"](https://piuparts.debian.org/), here: https://piuparts.debian.org/sid/fail/openjdk-11-jdk_11~19-1.log, so this is an upstream bug.

Looks like there is a bug filed: https://bugs.debian.org/902368.

**Comment by J0WI** [comment]
It's a bit sad that a failing prerelease package blocks all others.
Is there a reason that all builds fail if one variant is affected?

**Comment by tianon** [comment]
> Is there a reason that all builds fail if one variant is affected?

Just that it's a tad complicated to get the builds and commits to line up otherwise.

I've committed this regardless of the build failure because the current build also now fails (due to the nature of the Debian archive) and it's "correct" even though it will forever fail to build.
