### ISSUE TITLE
Build Java 11 Alpine

### ISSUE THREAD

**Issue by ST-DDT** [docker-library/openjdk#211]
On the java page there is a alpine compatible build for Java 11.

http://jdk.java.net/11/
https://download.java.net/java/early_access/alpine/19/binaries/openjdk-11-ea+19_linux-x64-musl_bin.tar.gz

Could you please build a docker image for that, so I could start testing Java 11 before Java 8 goes EOL this year?

Or is it required to appear in the official repository that was linked in some other issues https://pkgs.alpinelinux.org/packages?name=openjdk*&branch=edge ?

**Comment by tianon** [comment]
Isn't `src.zip` useful to include for many use cases?  (Especially since this is already the full JDK, so not exactly "slim".)

For context, the current `openjdk:11-jdk` image contains `src.zip`:
```console
$ docker run --rm openjdk:11-jdk find /usr -name src.zip
/usr/lib/jvm/java-11-openjdk-amd64/src.zip
```

**Comment by tianon** [comment]
I'm a little bit concerned that this will be a divergence from our previous Alpine images (and will mean we can only support amd64), but given that https://bugs.alpinelinux.org/issues/8089 is still open and unresolved 9 months and 2 releases later, I think moving forward with the upstream-provided binaires for Alpine probably makes sense.

**Comment by tianon** [comment]
(It looks like we could even add the Early Access builds of OpenJDK 12 via this method, which would get the jump on Debian too.)

**Comment by tianon** [comment]
This is related to https://github.com/docker-library/openjdk/issues/212 too 👍

**Comment by nafeger** [comment]
The openjdk build for alpine was removed for jdk 11, there is only an EAP for jdk12. Should the default download for linux jdk work on a stock alpine image?

**Comment by tianon** [comment]
Yeah, see https://github.com/docker-library/openjdk/issues/212#issuecomment-424453577 and https://github.com/docker-library/openjdk/pull/235#issuecomment-424599754:

> Yeah, the alpine port is not in a supported release, since it's not in the mainline code base, so it's only available as early access builds of OpenJDK Project Portola http://openjdk.java.net/projects/portola.  
> 
> It works, but at this stage it basically needs community contributors to help maintain it and get it into mainline - see https://twitter.com/MikaelVidstedt/status/984920426655526912 for details. Interested contributors should drop by portola-dev to discuss specifics.

**Comment by nafeger** [comment]
> Yeah, see [#212 (comment)](https://github.com/docker-library/openjdk/issues/212#issuecomment-424453577) and [#235 (comment)](https://github.com/docker-library/openjdk/pull/235#issuecomment-424599754):
> 
> > Yeah, the alpine port is not in a supported release, since it's not in the mainline code base, so it's only available as early access builds of OpenJDK Project Portola http://openjdk.java.net/projects/portola.
> > It works, but at this stage it basically needs community contributors to help maintain it and get it into mainline - see https://twitter.com/MikaelVidstedt/status/984920426655526912 for details. Interested contributors should drop by portola-dev to discuss specifics.

Thanks for the update, totally missed those comments.

**Comment by tianon** [comment]
> Please correct me if I am wrong, but going forward - which OpenJDK build will be used by Alpine for the official images?

Right now, the official images have no plans to support Alpine for OpenJDK 11 -- the Alpine project is not producing usable or timely builds since OpenJDK 8 (https://bugs.alpinelinux.org/issues/8089), and Project Portola (as noted above) does not have the necessary manpower to be fully supported by Oracle, so there's really nothing we can do there except recommend that interested folks go get involved with Project Portola.

For OpenJDK 12 EA builds, we currently have Alpine builds courtesy of Portola, but those might go away with 12's GA if Portola doesn't get enough support before then.

**Comment by michaelbannister** [comment]
Worth having a look at https://hub.docker.com/u/adoptopenjdk/

**Comment by ST-DDT** [comment]
@michaelbannister Are there any slim builds for that repo? Also I'm missing the tags for "just java 11" what is jdk-11.28) and the distinction between jre and jdk.

The images are smaller that this repository's non-slim ones though. Is there less of something in there?

**Comment by michaelbannister** [comment]
@ST-DDT I should've made clear that I haven't yet tried using these images (but I've been aware of the AdoptOpenJDK efforts for a few months). I only just found out they were producing Alpine images.
If you look at the [tags for adoptopenjdk/openjdk11](https://hub.docker.com/r/adoptopenjdk/openjdk11/tags/) you'll see they include `jdk-11.28-alpine`, `alpine` (I'm guessing that's equivalent of latest jdk-11)

See the readme for more detail, including the fact that:
> The Alpine Linux and the slim images are not yet TCK certified.
https://github.com/AdoptOpenJDK/openjdk-docker#supported-builds-and-build-types

**Comment by robilad** [comment]
A bit more on Portola status is available here: https://mjg123.github.io/2018/11/05/alpine-jdk11-images.html

" In order to move Alpine to “supported” and have GA releases of Portola Oracle is looking for people to be actively interested: contribute to the extent of your abilities - code and tests are welcome but so is being active and public about your support - say if you find any issues, and say too if everything worked fine. If containers are critical to your company, saying that you would be interested in a Java SE Subscription if Alpine were supported would go a long way, too."

**Comment by p-bakker** [comment]
Azul seems to have gotten OpenJDK going on Alpine and passes the full OpenJDK TCK Java compliance suite, see https://www.azul.com/downloads/zulu/zulu-download-alpine/

How does this factor into this issue report?

**Comment by yosifkit** [comment]
Created an issue around updating openjdk versions: #272.

**Comment by alexellis** [comment]
Is there an OpenJDK 11 image for Alpine Linux?

**Comment by keckelt** [comment]
No. From java.net:
> The Alpine Linux build previously available on this page was removed as of JDK 11 GA. It’s not production-ready because it hasn’t been tested thoroughly enough to be considered a GA build.

The one I used before OpenJDK12 was available can be found here: https://github.com/keckelt/openjdk11-alpine

But i would recommend using OpenJDK12: https://pkgs.alpinelinux.org/packages?name=openjdk12&branch=edge

**Comment by delabassee** [comment]
> But i would recommend using OpenJDK12: https://pkgs.alpinelinux.org/packages?name=openjdk12&branch=edge

I wouldn't recommend 12 as it isn't supported anymore and that particular Alpine build is ~18 months old.
If you really want a recent Alpine build, grab the 14 one  at https://jdk.java.net/14/ with the usual caveats (EA, don't try this at home, ...).

**Comment by alexellis** [comment]
Thank you everybody for the input. Perhaps what I need is an alpine given this information. What's the next smallest version that I could be looking at for prod? Debian slim seems to be > 450mb for the JDK.

**Comment by col-panic** [comment]
I use https://hub.docker.com/r/adoptopenjdk/openjdk11 resp adoptopenjdk/openjdk11:alpine-jre-nightly and am quite satisfied with it.

**Comment by delabassee** [comment]
@alexellis to avoid the jumbo size on Debian, you need to strip-out the debug info.
