### ISSUE TITLE
OpenJDK 11 build 22 missing

### ISSUE THREAD

**Issue by loxal** [docker-library/openjdk#214]
OpenJDK 11 "Latest build: 22 (2018/7/12)"  resolves a crucial certifcate issue but it's not yet available as Docker container. It would be awesome if you could speedup the build propagation process as many crucial fixes will land in OpenJDK 11 in the coming days and weeks.

**Comment by loxal** [comment]
Ah, I see, it seems to be an https://hub.docker.com/_/openjdk/ issue. Is there a repository where can pull the most recent OpenJDK 11/build22 image?

**Comment by tianon** [comment]
From https://github.com/docker-library/openjdk#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet:

> ## See a change merged here that doesn't show up on Docker Hub yet?
> 
> Check [the "library/openjdk" manifest file in the docker-library/official-images repo](https://github.com/docker-library/official-images/blob/master/library/openjdk), especially [PRs with the "library/openjdk" label on that repo](https://github.com/docker-library/official-images/labels/library%2Fopenjdk).
> 
> For more information about the official images process, see the [docker-library/official-images readme](https://github.com/docker-library/official-images/blob/master/README.md).

We'll make a PR over there today.
