### ISSUE TITLE
Provide OpenJDK 8 variants for Debian 10/buster

### ISSUE THREAD

**Issue by krichter722** [docker-library/openjdk#219]
It'd be nice to have the different combinations of variants (jre/jdk, normal/slim, etc.) available for OpenJDK 8 based on `debian:buster` (and `debian:buster-slim`).

**Comment by tianon** [comment]
I understand the desire to not be on Unstable (Sid), but I'm not sure I understand why Buster is much better -- the biggest downside of such an image would be that any fixes/updates (including security fixes) will be delayed somewhere between 2-10 days, sometimes even longer (given the nature of Debian's testing repository).

**Comment by krichter722** [comment]
@tianon Thanks for you comment, however I have following problem understanding it: Either there's a unstable/sid image for OpenJDK 8 which I don't find on https://hub.docker.com/_/openjdk/ (which doesn't mean that there isn't another location I can get it from that I don't know, or maybe not all tags are displayed even though the list seems pretty complete - if either is the case, please clarify). Or I do not understand what the provision of images for buster (I wouldn't mind an image for sid if they indeed do not exist) has to do with the delay between unstable and testing.

**Comment by yosifkit** [comment]
We'll likely only migrate to Buster when it becomes "Debian Stable" and Stretch becomes old-stable. Exceptions like an important openjdk (maybe 8u202?) bump might be reason to move.
