### ISSUE TITLE
Provide multi-platform docker images

### ISSUE THREAD

**Issue by dtretyakov** [docker-library/openjdk#223]
Docker registry and docker CLI supports ability to create multi-platform images by leveraging image manifests. For instance `microsoft/docker` image already use it and container start will look the same on all supported platforms `docker run microsoft/dotnet` without need to specify tags and suffixes likes `:latest-windowsservercore-1709`.

To do that after pushing images should be created an image manifest with a list of source images and name of target image:

```
docker manifest create openjdk:10.0.2-jdk \
  openjdk:10.0.2-jdk-sid \
  openjdk:10.0.2-jdk-nanoserver-1709 \
  openjdk:10.0.2-jdk-nanoserver-sac2016 \
  ...
docker manifest push openjdk:10.0.2-jdk
```

And on any supported platform user could do the following to start a new container from such image:
```
docker run openjdk:10.0.2-jdk
```

Docs:
* https://medium.com/@mauridb/docker-multi-architecture-images-365a44c26be6
* https://docs.docker.com/engine/reference/commandline/manifest_create/

**Comment by tianon** [comment]
Oh snap, we should reopen and reconsider this for 12+! (since in 12 and 13, _all_ variant artifacts come from OpenJDK's official downloads at https://jdk.java.net/12/ and https://jdk.java.net/13/ :balloon:)

**Comment by tianon** [comment]
https://github.com/docker-library/openjdk/pull/273 :metal:
