### ISSUE TITLE
Build Java after 9 for ARM64 on alpine

### ISSUE THREAD

**Issue by Denusdv** [docker-library/openjdk#229]
On the docker hub page, there are almost all openjdk (9,10,11 ..) versions for  ARM64.
On the Java page, there is an alpine build for Java 11.

I'm looking for Java 11 for alpine on ARM64. Does such a combination exist? Java 9 and 10 works for me as well.

Thanks

**Comment by tianon** [comment]
Nope, see https://github.com/docker-library/openjdk/issues/211.
