### ISSUE TITLE
Provide JDK 11 with ZGC enabled

### ISSUE THREAD

**Issue by josepowera** [docker-library/openjdk#233]
Java 11 is shipping with low latency Garbage collector.. However starting docker image from openjdk seems to have this feature missing:

```
docker run --rm -it openjdk:11-ea-slim java -XX:+UnlockExperimentalVMOptions -XX:+UseZGC -version
Error occurred during initialization of VM
Option -XX:+UseZGC not supported

```

This option is architecture specific - only available for Linux/x64.  

It could also be upstream issue - debian packacing issue? Probably same problem as seen in  https://twitter.com/shipilev/status/1039180042260111360 

https://src.fedoraproject.org/rpms/java-11-openjdk/c/915d59aa585cfbb210d74ebf9e717c2eddb7d93c?branch=master

**Comment by tianon** [comment]
> It could also be upstream issue - debian packacing issue?

Unfortunately, yes exactly this.  We don't build OpenJDK from source (for various reasons), so this will need to be reported on the Debian `openjdk-11` package instead.

It _could_ also be a quirk of `-slim` (which embeds the Debian "headless" packages); have you also tried with the non-`-slim` images to verify that it's indeed an issue with all of `src:openjdk-11` and not simply something that gets excluded for the smaller "headless" packages?

**Comment by josepowera** [comment]
Same in non slim:
```
docker run --rm -it openjdk:11-ea java -XX:+UnlockExperimentalVMOptions -XX:+UseZGC -version
Error occurred during initialization of VM
Option -XX:+UseZGC not supported
```

**Comment by josepowera** [comment]
Submitted as https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=909560

**Comment by robilad** [comment]
ZGC is an experimental JVM feature, so it needs to be enabled during the configuration of the build from OpenJDK source code. It is built in with the Oracle OpenJDK builds - see https://github.com/docker-library/openjdk/pull/235 for status, and should be available in Debian builds soon.

**Comment by rbjorklin** [comment]
It seems this has been fixed upstream, how/when is a rebuild triggered?

```
$ docker run --rm debian:sid /bin/bash -c 'apt-get update && apt-get install -y openjdk-11-jdk && java -XX:+UnlockExperimentalVMOptions -XX:+UseZGC -version'

...
openjdk version "11" 2018-09-25   
OpenJDK Runtime Environment (build 11+28-Debian-2)
OpenJDK 64-Bit Server VM (build 11+28-Debian-2, mixed mode)
```

**Comment by yosifkit** [comment]
The automatic update.sh caught it already in https://github.com/docker-library/openjdk/commit/11ac1383306934fe910c168aacc06c82ec65fe52.  We just need to update https://github.com/docker-library/official-images with a PR (we'll probably do so tomorrow morning).

**Comment by rbjorklin** [comment]
Sounds good @yosifkit! Since JDK 11 no longer is EA maybe the `update.sh` script should be updated a bit? I've identified the following lines but there might be more:

https://github.com/docker-library/openjdk/blob/master/update.sh#L191-L197
https://github.com/docker-library/openjdk/blob/master/update.sh#L396
https://github.com/docker-library/openjdk/blob/master/update.sh#L409-L421
https://github.com/docker-library/openjdk/blob/master/update.sh#L443-L446

**Comment by yosifkit** [comment]
Already done: https://github.com/docker-library/openjdk/commit/bca955fe8c80ff7272e9f4a4ffa8b822a27a0aef

And should be building shortly with the merge in official images: https://github.com/docker-library/official-images/pull/4892.

**Comment by c-edw** [comment]
Sorry to derail, but would anyone happen to know the status of ZGC on Windows? I have the latest release from http://jdk.java.net/11/ but get the same message as above. Thanks.

**Comment by rbjorklin** [comment]
I think ZGC only has experimental support under Linux on x86_64 so far.

**Comment by c-edw** [comment]
@rbjorklin Ah that's a shame, I will wait and see what happens then. Thanks for your swift response :+1:.

**Comment by rbjorklin** [comment]
@c-edw you might still be interested in trying JDK11, there has been some significant tweaking on the G1GC: http://mail.openjdk.java.net/pipermail/hotspot-gc-use/2018-June/002759.html

**Comment by robilad** [comment]
ZGC has been ported to SPARC/Solaris, and there is work being done by Linaro on an AArch64/Linux port. There is no Windows port yet.
