### ISSUE TITLE
Latest non-LTS images?

### ISSUE THREAD

**Issue by p-bakker** [docker-library/openjdk#238]
With the new release cycle for Java, would it make sense to have images with a `non-lts-latest` tag? And maybe then also a `lts-latest` tag?

See https://jaxenter.com/wp-content/uploads/2018/01/end-of-life-jdk8.jpg

**Comment by tianon** [comment]
Honestly, I'd be more likely to go the other direction -- folks relying on a tag like `latest` are usually surprised when that square wheel rolls and they move from one release to another, so it's better for us to recommend that users be explicit about both their dependencies, and about when those dependencies roll.  In this case, that means they ought to specify that they want OpenJDK 8, 11, etc. explicitly, and thus be unsurprised when they choose to update it.

**Comment by robilad** [comment]
The semantics of lts-latest could become complicated once there is more than one LTS release.  Similarly, non-LTS-latest might imply 10.0.2 rather than 11 at this time, depending on how you interpret non and LTS,

**Comment by p-bakker** [comment]
Mmm, agree on the lts-latest, not on the non-LTS-latests: as far as I understand there is always one non-LTS latests. ATM that is the last Java 11 release, but as soon as Java 12 is GA, it's the latest Java 12 release (of which there will be a 12.0.0, 12.0.1 and 12.0.2 and then it'll be on to Java 13.

AFAIK the newly releases LTS version will also be the latest non-LTS version for 6 months after its release, after which a new non-LTS release will take over

**Comment by robilad** [comment]
I think in that case you're simply asking for the 'latest' tag to be rolling from release to release, LTS-iness of individual releases aside.  

The 'latest' tag seems to be currently pointing to 10.0.2, judging by https://hub.docker.com/_/openjdk/, so  I guess it could be a bit confusing to get 10.0.2 as latest after 11 GA.

**Comment by tianon** [comment]
Whoops, "latest" pointing to 10 is an oversight; now that 11 is GA, that
should be updated (and probably point the generic "latest" tag at the new
Oracle-official variant, using the major bump as a compatibility break).

**Comment by tianon** [comment]
Whoops, realized it would be somewhat irresponsible to update `openjdk:11` to point at something different right now, but in https://github.com/docker-library/openjdk/commit/b334897770e2d249ac0d14d4425892dda675fd43 I've updated `latest` to point at the 11 builds (so now we'll have `openjdk:oracle` that's the "latest all-Oracle bits" release) and for 12+ `openjdk:latest` will point to the Oracle variants (so once this is PR'd to https://github.com/docker-library/official-images, we'll get the following new aliases on those 12 images: `12-ea-15-jdk, 12-ea-15, 12-ea-jdk, 12-ea, 12-jdk, 12`).

**Comment by p-bakker** [comment]
> I think in that case you're simply asking for the 'latest' tag to be rolling from release to release, LTS-iness of individual releases aside.

Maybe... Imho with the current Java release schedule, there's a distinct difference between LTS and non-LTS releases and as such I think that a generic `latest` tag might be a bit confusing/unclear, hence the request to distinguish them.

I do agree that whatever `latest` tag should indeed point to the latest release of Java, so atm that would be (I think) Java 11.0.0 (to be replaced by Java 11.0.1 as soon as its released) and if there would be LTS and non-LTS tags, both would be using Java 11.0.0 right now and the non-LTS release would move to Java 12.0.0 once release and the LTS latest would move to Java 15.0.0 once released

**Comment by brunoborges** [comment]
LTS is a vendor distinction for commercially supported (whether paid or not) builds of OpenJDK (aka binaries). 

OpenJDK itself, the open source project, has no definition of LTS. For example, the source code branch OpenJDK 11 is *not* LTS.

That said, `openjdk:latest` should always point to the _latest_ GA release of OpenJDK (as of May 13th 2020, this would be Java 14). And the binary should come from whatever vendor has the "best" binaries, for whatever definition of best the maintainers of this Docker Library have decided on.

**Comment by tianon** [comment]
Thanks, that makes a lot of sense and reflects the reality of our current state, so I'm going to close this. :+1:
