### ISSUE TITLE
JVM (OpenJDK 11) fails to start when JFR is enabled

### ISSUE THREAD

**Issue by laszlocsontos** [docker-library/openjdk#243]
This is a bug in the current `openjdk-11-jdk` package Debian provides.
Related bug report: [JVM fails to start when JFR is enabled](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=910804)
------
**How to reproduce**

```
% docker run openjdk:11 \
  java -XX:StartFlightRecording=disk=true,dumponexit=true,filename=/tmp/test.jfr -version

Could not parse setting default
Error occurred during initialization of VM
Failure when starting JFR on_vm_start
```

**Analysis**

The problem is caused by missing JFC files from the OpenJDK installation.

Another JDK installation which I created form the official tarball has
the following files:

```
# ls -l /opt/jdk-11/lib/jfr/
total 56
-rw-r--r-- 1 668 668 28012 Aug 23 03:57 default.jfc
-rw-r--r-- 1 668 668 27963 Aug 23 03:57 profile.jfc
```

On the other hand, that one I'm having the problem with doesn't even have
the JFR folder

```
# ls -l /usr/lib/jvm/java-11-openjdk-amd64/lib/jfr
ls: cannot access '/usr/lib/jvm/java-11-openjdk-amd64/lib/jfr': No such file or directory
```

**Wordaround**

Build a custom container image and add the following `RUN` statement after `FROM openjdk:11`.

```
# Workaround for https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=910804
RUN mkdir -p /docker-java-home/lib/jfr && \
    wget https://hg.openjdk.java.net/jdk/jdk11/raw-file/76072a077ee1/src/jdk.jfr/share/conf/jfr/default.jfc \
      -O /docker-java-home/lib/jfr/default.jfc && \
    wget https://hg.openjdk.java.net/jdk/jdk11/raw-file/76072a077ee1/src/jdk.jfr/share/conf/jfr/profile.jfc \
      -O /docker-java-home/lib/jfr/profile.jfc
```

The default JFR profile will be found after that.

```
% docker run 637bba0e215b java -XX:StartFlightRecording=disk=true,dumponexit=true,filename=/tmp/test.jfr -version 
Started recording 1. No limit specified, using maxsize=250MB as default.

Use jcmd 1 JFR.dump name=1 to copy recording data to file.
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment (build 11+28-Debian-3)
OpenJDK 64-Bit Server VM (build 11+28-Debian-3, mixed mode, sharing)
```
-----
Related PR: https://github.com/docker-library/openjdk/pull/244

**Comment by tianon** [comment]
This appears to work great out-of-the-box on `openjdk:11-oracle` (introduced in https://github.com/docker-library/openjdk/pull/235), so I'd recommend giving that a shot if it works for your use case.  At the very least, you could use `openjdk:11-oracle`'s `jlink` to generate yourself a minimal JRE to then use in Debian (if Debian is a requirement). :+1:

**Comment by tianon** [comment]
So, a bit more digging here and it appears these files _do_ exist in the `openjdk-11-jre-headless` package in Debian Buster, but we're installing from `stretch-backports` which has a slightly older version.

Perhaps it'd be possible to get whoever is maintaining that backported package to update it to the version in Buster?

**Comment by tianon** [comment]
Fixed via https://github.com/docker-library/openjdk/commit/df4cff5b79d52fa311d6dff4c874f191996b583c :tada: :heart:

(Thus will be published with https://github.com/docker-library/official-images/pull/5403)

**Comment by Hardikhm** [comment]
I am trying to the above workaround but getting error.

 => ERROR [2/6] RUN mkdir -p /docker-java-home/lib/jfr &&     wget https://hg.openjdk.java.net/jdk/jdk11/raw-file  0.5s
------
 > [2/6] RUN mkdir -p /docker-java-home/lib/jfr &&     wget https://hg.openjdk.java.net/jdk/jdk11/raw-file/76072a077ee1/src/jdk.jfr/share/conf/jfr/default.jfc       -O /docker-java-home/lib/jfr/default.jfc &&     wget https://hg.openjdk.java.net/jdk/jdk11/raw-file/76072a077ee1/src/jdk.jfr/share/conf/jfr/profile.jfc       -O /docker-java-home/lib/jfr/profile.jfc:
#5 0.401 /bin/sh: 1: wget: not found
------
executor failed running [/bin/sh -c mkdir -p /docker-java-home/lib/jfr &&     wget https://hg.openjdk.java.net/jdk/jdk11/raw-file/76072a077ee1/src/jdk.jfr/share/conf/jfr/default.jfc       -O /docker-java-home/lib/jfr/default.jfc &&     wget https://hg.openjdk.java.net/jdk/jdk11/raw-file/76072a077ee1/src/jdk.jfr/share/conf/jfr/profile.jfc       -O /docker-java-home/lib/jfr/profile.jfc]: exit code: 127
