### ISSUE TITLE
openjdk:8-jdk started failing maven builds

### ISSUE THREAD

**Issue by damian-sima-olx** [docker-library/openjdk#247]
Hi guys, I have a few jobs running mvnw to build my projects. These were running on an openjdk:8-jdk. 
I started getting issues like fail to fork vm, with some maven plugins specifically surefire and failsafe. 
Changing to older or newer versions didn't solve the problem. 

What it did solve the problem was to use another docker image that's based on alpine and on top it install java 8. 

I think the issue is with the Debian Stretch image but no idea what could have caused it. Any ideas?

**Comment by albuch** [comment]
This is an bug in openjdk on Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=911925
There is a workaround documented in the bug ticket (Setting jdk.net.URLClassPath.disableClassPathURLCheck for the forked JVM) that works until the patch in upstream OpenJDK is applied and released on Debian.

**Comment by damian-sima-olx** [comment]
That's brilliant, thanks a lot guys! 
I've try the work around and it works fine.
Do you have any estimate when the patch will make it to Debian?

**Comment by albuch** [comment]
@damian-sima-olx you should ask this question over at the Debian bug.

**Comment by yosifkit** [comment]
Update 191 for `openjdk-8*` packages for Debian is only available in [Debian Experimental](https://wiki.debian.org/DebianExperimental) and as such should not be used:

> Experimental is used for packages which are still being developed, and with a high risk of breaking your system. It's used by developers who'd like to study and test bleeding edge software. **Users shouldn't be using packages from there**, because they can be dangerous and harmful even for the most experienced people.
>
> \- https://www.debian.org/doc/manuals/debian-faq/ch-ftparchives.en.html (emphasis added)

When it is available in more stable distribution, it may be considered (or even automatically picked up by `update.sh`).

**Comment by yosifkit** [comment]
@jglick, the reason that it is not available on `buster` (aka `testing`) is that it fails to build on 5 different architectures so the automated migration from `sid` to `buster` is on hold until that is addressed (see the "testing migrations" https://tracker.debian.org/pkg/openjdk-8)

Closing since the original issue was solved. Follow #245 for tracking updating to 8u191.
