### ISSUE TITLE
Requesting Windows nanoserver image for java 11

### ISSUE THREAD

**Issue by petersogaard** [docker-library/openjdk#258]
I would really appreciate a nanoserver image for java 11.

My java 8 containers are based on openjdk:8-nanoserver that has a size of 1.4GB
My java 11 containers are currently based on openjdk:11.0.1-jdk-windowsservercore-ltsc2016 that has a size of 11.4GB.

**Comment by tianon** [comment]
`openjdk:8-nanoserver` is based on the older Nano Server images (when `powershell` was still included and the image was still usable as a useful base).

The newer Nano Server images are more akin to `FROM scratch` for Windows (where the previous images were semi-similar to `FROM alpine` -- still useful to download/install things without too much fanfare), so we haven't a great way to support them going forward (nor much desire, given the effective "uselessness" of the current Nano Server images out-of-the-box).

**Comment by petersogaard** [comment]
Thank you! Much appreciated :-)
