### ISSUE TITLE
Description on https://hub.docker.com/_/java/ has gone missing

### ISSUE THREAD

**Issue by patrick-webs** [docker-library/openjdk#266]
I believe there used to be a note on https://hub.docker.com/_/java/ stating that the image had been deprecated and to use the "openjdk" image instead. https://web.archive.org/web/20181005032908/https://hub.docker.com/_/java/

That message, and the rest of the description, is gone and the page now says "There is no available description for this repository."

Restoring a description would be useful:

1. to let people know to switch to the "openjdk" name
2. to clarify whether the "java" tag contains Oracle Java SE, or OpenJDK, given that with the changes to Java SE licensing there will be increasing concern about whether Oracle JDK is being used accidentally or not.

**Comment by tianon** [comment]
Ouch, thanks for the heads up!  Before I go restore the contents, I've reached out to some Docker folks to see if we can determine what's happened, since we shouldn't have touched it since roughly as far back as June of 2017 😅.

**Comment by patrick-webs** [comment]
FWIW, the description seems to be back for me. Maybe just a temporary issue on DockerHub's end?

**Comment by yosifkit** [comment]
This was brought up to the maintainers of Docker Hub at Docker Inc and will be looked at. We have no visibility on the progress, so I'll close this issue.
