### ISSUE TITLE
Update to Java 8u202 (latest version)

### ISSUE THREAD

**Issue by dennisosimon** [docker-library/openjdk#271]
See latest update:
https://openjdk.java.net/projects/jdk8u/releases/8u202.html

**Comment by yosifkit** [comment]
Discussion from #245 still applies.

TLDR; We consume packages from Debian Stretch and Alpine 3.8 for openjdk 8, so until those have the new version we cannot update. (why not build from source: https://github.com/docker-library/openjdk/issues/150#issuecomment-338713389)

**Comment by yosifkit** [comment]
Created an issue around updating openjdk versions: #272.

**Comment by brichins** [comment]
It appears that 8u202 has been released by Debian stretch now. I don't know how to tell when it was released.  If it was in the last 24 hours, I imagine it could take time for the CI pipeline to detect a new version.  If older than 24 hours, any idea when we can expect an updated image? 
https://packages.debian.org/stretch/openjdk-8-jdk

**Comment by yosifkit** [comment]
@brichins Debian is now at [8u212](https://packages.debian.org/stretch/openjdk-8-jdk);  The reason for the non-updates is because the `update.sh` job is failing see #289, #292, and #294.

Since the 8u212 Debian bump is a security fix, we'll have it merged as soon as possible.

**Comment by brichins** [comment]
That's great news.  Thanks for keeping this up to date.  I, and I'm sure many others, appreciate it.
