### ISSUE TITLE
Any plans to build on centos image as well ?

### ISSUE THREAD

**Issue by sabareeshkkanan** [docker-library/openjdk#280]

**Comment by tianon** [comment]
Nope -- in 11+ we have "oracle" variants which are pulling the Oracle-maintained bits from https://jdk.java.net/ and are based on Oracle Linux (which is very similar to CentOS), and in 12+ it becomes the default variant.

**Comment by sabareeshkkanan** [comment]
Thank you, I do see file for jdk but not for jre. I was able to just change the base image and worked flawlessly
