### ISSUE TITLE
jmap no -heap option

### ISSUE THREAD

**Issue by AllenConquest** [docker-library/openjdk#286]
I am currently using the image openjdk:8u191-jdk-alpine. I wanted to generate some heap summary stats, as I would normally, using jmap -heap <pid>. But that option is not available.

Any idea why this option is not supported on alpine openjdk?

Thanks,

Allen

**Comment by tianon** [comment]
Looks like a quirk of the Alpine packaging for `openjdk8` -- unfortunately don't have any idea further than that.  The help text for `jmap` in `openjdk:8-jdk-alpine` vs `openjdk:8-jdk` is honestly a bit eyebrow-raising for something that I thought was part of the JDK itself (why is it so different?).

So, I'd suggest trying an Alpine forum for asking further on this (not really something we can change in the image here).

**Comment by inter169** [comment]
did a quick investigation (building the openjdk8 apk by hand, compiling source codes ...etc) on this, the command option 'jmap -heap' was depended on loading class 'sun.jvm.hotspot.tools.HeapSummary', which was in 'sa-jdi.jar'.

the openjdk8 related apk packages have no such file 'sa-jdi.jar', so jmap didn't support the option '-heap', and you can find the proof in the source code (.../openjdk/jdk/src/share/classes/sun/tools/jmap/JMap.java)

so you should build and put 'sa-jdi.jar' onto the alpine docker.

**Comment by AllenConquest** [comment]
@inter169 great work! Now do we know who builds the openjdk8 for Alpine?

**Comment by inter169** [comment]
the package info https://pkgs.alpinelinux.org/contents?repo=community&page=1&arch=x86_64&branch=v3.9&name=openjdk8%2A
Probably the alpine community

**Comment by inter169** [comment]
I merged that [(patch)](http://mail.openjdk.java.net/pipermail/portola-dev/2017-May/000185.html) and added a few code fixes by hand into the openjdk8 hotspot codes, built the 'libsaproc.so', 'sa-jdi.jar' during the alpine openjdk8 apk building process.

and put libsaproc.so, sa-jdi.jar files onto the relative jre directory, and installed the openjdk8-dbg (apk add openjdk8-dbg) on the alpine docker, seemed it worked:

```
/mount/wq-test-jmap-relationship-5f9f9c46cb-kmcwj # ./jmap -h
Usage:
    jmap [option] <pid>
        (to connect to running process)
    jmap [option] <executable <core>
        (to connect to a core file)
    jmap [option] [server_id@]<remote server IP or hostname>
        (to connect to remote debug server)

where <option> is one of:
    <none>               to print same info as Solaris pmap
    -heap                to print java heap summary
    -histo[:live]        to print histogram of java object heap; if the "live"
                         suboption is specified, only count live objects
    -clstats             to print class loader statistics
    -finalizerinfo       to print information on objects awaiting finalization
    -dump:<dump-options> to dump java heap in hprof binary format
                         dump-options:
                           live         dump only live objects; if not specified,
                                        all objects in the heap are dumped.
                           format=b     binary format
                           file=<file>  dump heap to <file>
                         Example: jmap -dump:live,format=b,file=heap.bin <pid>
    -F                   force. Use with -dump:<dump-options> <pid> or -histo
                         to force a heap dump or histogram when <pid> does not
                         respond. The "live" suboption is not supported
                         in this mode.
    -h | -help           to print this help message
    -J<flag>             to pass <flag> directly to the runtime system
```

generate the heap info for java process (pid: 1):

```
/mount/wq-test-jmap-relationship-5f9f9c46cb-kmcwj # ./jmap -heap 1
Attaching to process ID 1, please wait...
Debugger attached successfully.
Server compiler detected.
JVM version is 25.191-b12

using thread-local object allocation.
Mark Sweep Compact GC

Heap Configuration:
   MinHeapFreeRatio         = 40
   MaxHeapFreeRatio         = 70
   MaxHeapSize              = 536870912 (512.0MB)
   NewSize                  = 11141120 (10.625MB)
   MaxNewSize               = 178913280 (170.625MB)
   OldSize                  = 22413312 (21.375MB)
   NewRatio                 = 2
   SurvivorRatio            = 8
   MetaspaceSize            = 21807104 (20.796875MB)
   CompressedClassSpaceSize = 1073741824 (1024.0MB)
   MaxMetaspaceSize         = 17592186044415 MB
   G1HeapRegionSize         = 0 (0.0MB)

Heap Usage:
New Generation (Eden + 1 Survivor Space):
   capacity = 41680896 (39.75MB)
   used     = 21742608 (20.735366821289062MB)
   free     = 19938288 (19.014633178710938MB)
   52.1644448334316% used
Eden Space:
   capacity = 37093376 (35.375MB)
   used     = 19402400 (18.503570556640625MB)
   free     = 17690976 (16.871429443359375MB)
   52.30691323431979% used
From Space:
   capacity = 4587520 (4.375MB)
   used     = 2340208 (2.2317962646484375MB)
   free     = 2247312 (2.1432037353515625MB)
   51.012486049107146% used
To Space:
   capacity = 4587520 (4.375MB)
   used     = 0 (0.0MB)
   free     = 4587520 (4.375MB)
   0.0% used
tenured generation:
   capacity = 92266496 (87.9921875MB)
   used     = 78430384 (74.79704284667969MB)
   free     = 13836112 (13.195144653320312MB)
   85.00418613491077% used

43672 interned Strings occupying 5202400 bytes.
```

**Comment by AllenConquest** [comment]
@inter169 this is great, but how do we get it into the alpine openjdk official build?

**Comment by inter169** [comment]
sorry, I'm not very familiar with the dev/patch patterns for alpine, maybe need to talk to the alpine team via alpine IRC channel,

usually I coded & patched to customized alpine docker image, as a quick fix.

thanks
harper

**Comment by tianon** [comment]
I think it would probably be a good idea to file an issue at https://bugs.alpinelinux.org (since this is really an issue in the Alpine upstream package) and add some of this context there so that the actual package maintainers have a higher chance of seeing it and thus fixing it. :+1:

**Comment by tianon** [comment]
They've also got a couple mailing lists and/or their IRC channel previously referenced that might be good sources to ask around once a bug is filed: https://alpinelinux.org/community/

**Comment by wglambert** [comment]
Closing since this is an upstream issue and not something we would want to maintain as a deviation from the source

**Comment by jhmartin** [comment]
As a google breadcrumb; https://github.com/apangin/jattach is able to generate heap dumps from within an Alpine / OpenJDK8 based container.
