### ISSUE TITLE
"[: amd64: unexpected operator" on update-ca-certificates

### ISSUE THREAD

**Issue by aschmied** [docker-library/openjdk#287]
Trying to refresh the CA certs I'm seeing the following:

```
$ docker run --rm -it openjdk:11-jre-slim /bin/bash
root@611c132c648d:/# update-ca-certificates -f
Clearing symlinks in /etc/ssl/certs...
done.
Updating certificates in /etc/ssl/certs...
151 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...

/etc/ca-certificates/update.d/jks-keystore: 56: [: amd64: unexpected operator
...
```

The problem on line 56 of the jks-keystore script is this:

```
root@611c132c648d:/# cat /etc/ca-certificates/update.d/jks-keystore
#!/bin/sh
...
    if [ "$arch" == "armhf" ]; then
...
```

`==` is the string equality operator for bash. sh uses `=` ([ref](https://stackoverflow.com/q/24464690/2833126)).

**Comment by wglambert** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=922720

> Date: Sat, 09 Mar 2019 12:17:07 +0000
> Source: ca-certificates-java
> Source-Version: 20170929~deb9u2
> 
> We believe that the bug you reported is fixed in the latest version of
> ca-certificates-java, which is due to be installed in the Debian FTP archive.
> . . .

**Comment by aschmied** [comment]
@wglambert thanks! I wasn't sure where to look for upstream bug reports.

**Comment by tianon** [comment]
Closing since this appears to be fixed upstream. :+1:
