### ISSUE TITLE
Java 9 support

### ISSUE THREAD

**Issue by md5** [docker-library/openjdk#29]
In an email exchange today with one of the Jetty developers, I was told that Jetty 9.3 will be tracking Java 9 to take advantage of its built-in support for [ALPN](https://en.wikipedia.org/wiki/Application-Layer_Protocol_Negotiation).

It doesn't look like `openjdk-9-*` packages for Debian Sid are even a glimmer in anyone's eye yet, so perhaps this would be the time to start to exploring compilation from source.

Based on the comments in the `Dockerfile`, it looks like the objections to doing a source build revolved around the need to install a bootstrap JDK and Oracle's licensing. It looks like installing a boostrap JDK is still a requirement in the current `jdk9` build (cf. http://hg.openjdk.java.net/build-infra/jdk9/file/50da9851d248/README-builds.html#l352).

**Comment by tianon** [comment]
There's https://bugs.debian.org/751519, but it was shot down for `openjdk-8` being available; no idea WTF that's about. :confused:

**Comment by md5** [comment]
Yeah, that's a bit odd. Perhaps it makes more sense to someone more involved in the Debian Java community.

I started looking into the situation a bit more and it looks like they only want to have a single default JDK per Debian release, so `openjdk-9` will presumably not be available until Debian 10...

**Comment by md5** [comment]
I think "NEW" is this: https://wiki.debian.org/NewQueue

And from my reading it looks like they don't want `openjdk-9` in "NEW" until `openjdk-8` is out. And I think `openjdk-8` moving out of "NEW" may be dependent on this: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=760984

So it seems that `openjdk-8` will likely be part of Debian 9/Stretch, at which point `openjdk-9` can go into Sid.

**Comment by tianon** [comment]
The fact that an "openjdk-8" package is available for installing means it's
moved out of NEW already. :disappointed:

**Comment by tianon** [comment]
And looking at https://packages.debian.org/sid/openjdk-8-jdk, it's clear
it's not available in Jessie, which means they must be targeting Stretch.

**Comment by md5** [comment]
There's a thread on `debian-java` about the plans for Java in Stretch: https://lists.debian.org/debian-java/2015/04/msg00082.html

**Comment by tianon** [comment]
Wow, even adding "Ensure our openjdk-8 package passes the TCK";
they're definitely getting ambitious!

(cc @jpetazzo)

**Comment by jpetazzo** [comment]
Indeed! I hope this'll also make @giltene happier with the current state of Java-on-Docker :-)

**Comment by tianon** [comment]
This was fixed in https://github.com/docker-library/openjdk/pull/55. :+1:

**Comment by md5** [comment]
@tianon For some reason I missed this last month, but I thought I'd check if you guys have an ETA or any expectations for an Alpine variant for OpenJDK 9.

**Comment by md5** [comment]
It looks like I commented on the PR itself back in November 2015 though 😕

**Comment by tianon** [comment]
As soon as https://pkgs.alpinelinux.org/packages?name=openjdk9* returns something (ie, there's an Alpine package for it), so can't actually say for certain. :disappointed:
