### ISSUE TITLE
Docker build - failed.

### ISSUE THREAD

**Issue by nowiks** [docker-library/openjdk#290]
Hello, 

Last days we cannot build alpine with java. 

We have the following error:
The command '/bin/sh -c set -x  && apk add --no-cache           openjdk8="$JAVA_ALPINE_VERSION"         && [ "$JAVA_HOME" = "$(docker-java-home)" ]' returned a non-zero code: 1

Could you look at it?

BR,
Rafał

**Comment by J0WI** [comment]
I cannot reproduce so far:
`$ docker build --no-cache openjdk/8/jdk/alpine`
<details>
<summary>output</summary>

```bash
Sending build context to Docker daemon  3.072kB
Step 1/8 : FROM alpine:3.9
 ---> 5cb3aa00f899
Step 2/8 : ENV LANG C.UTF-8
 ---> Running in afa760ea23ef
Removing intermediate container afa760ea23ef
 ---> b75f21e6be38
Step 3/8 : RUN {                echo '#!/bin/sh';               echo 'set -e';          echo;           echo 'dirname "$(dirname "$(readlink -f "$(which javac || which java)")")"';  } > /usr/local/bin/docker-java-home     && chmod +x /usr/local/bin/docker-java-home
 ---> Running in 1c8c96859cc2
Removing intermediate container 1c8c96859cc2
 ---> 4fe762a5aba3
Step 4/8 : ENV JAVA_HOME /usr/lib/jvm/java-1.8-openjdk
 ---> Running in 5a1bfcc3adf9
Removing intermediate container 5a1bfcc3adf9
 ---> 4143c7db934d
Step 5/8 : ENV PATH $PATH:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin
 ---> Running in f369e88637da
Removing intermediate container f369e88637da
 ---> 0b9d085785aa
Step 6/8 : ENV JAVA_VERSION 8u191
 ---> Running in 5174ccbf9fa7
Removing intermediate container 5174ccbf9fa7
 ---> 0fed99479e9b
Step 7/8 : ENV JAVA_ALPINE_VERSION 8.201.08-r0
 ---> Running in 88fd72af7ce9
Removing intermediate container 88fd72af7ce9
 ---> 442061082567
Step 8/8 : RUN set -x   && apk add --no-cache           openjdk8="$JAVA_ALPINE_VERSION"         && [ "$JAVA_HOME" = "$(docker-java-home)" ]
 ---> Running in 8b85cd2167c3
+ apk add --no-cache 'openjdk8=8.201.08-r0'
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/37) Installing libffi (3.2.1-r6)
(2/37) Installing p11-kit (0.23.14-r0)
(3/37) Installing libtasn1 (4.13-r0)
(4/37) Installing p11-kit-trust (0.23.14-r0)
(5/37) Installing ca-certificates (20190108-r0)
(6/37) Installing java-cacerts (1.0-r0)
(7/37) Installing libxau (1.0.8-r3)
(8/37) Installing libbsd (0.8.6-r2)
(9/37) Installing libxdmcp (1.1.2-r5)
(10/37) Installing libxcb (1.13-r2)
(11/37) Installing libx11 (1.6.7-r0)
(12/37) Installing libxcomposite (0.4.4-r2)
(13/37) Installing libxext (1.3.3-r3)
(14/37) Installing libxi (1.7.9-r2)
(15/37) Installing libxrender (0.9.10-r3)
(16/37) Installing libxtst (1.2.3-r2)
(17/37) Installing alsa-lib (1.1.8-r0)
(18/37) Installing libbz2 (1.0.6-r6)
(19/37) Installing libpng (1.6.35-r0)
(20/37) Installing freetype (2.9.1-r2)
(21/37) Installing libgcc (8.2.0-r2)
(22/37) Installing giflib (5.1.4-r2)
(23/37) Installing libjpeg-turbo (1.5.3-r4)
(24/37) Installing libstdc++ (8.2.0-r2)
(25/37) Installing openjdk8-jre-lib (8.201.08-r0)
(26/37) Installing java-common (0.1-r0)
(27/37) Installing krb5-conf (1.0-r1)
(28/37) Installing libcom_err (1.44.5-r0)
(29/37) Installing keyutils-libs (1.6-r0)
(30/37) Installing libverto (0.3.0-r1)
(31/37) Installing krb5-libs (1.15.5-r0)
(32/37) Installing lcms2 (2.9-r1)
(33/37) Installing pcsc-lite-libs (1.8.24-r1)
(34/37) Installing lksctp-tools (1.0.17-r0)
(35/37) Installing openjdk8-jre-base (8.201.08-r0)
(36/37) Installing openjdk8-jre (8.201.08-r0)
(37/37) Installing openjdk8 (8.201.08-r0)
Executing busybox-1.29.3-r10.trigger
Executing ca-certificates-20190108-r0.trigger
Executing java-common-0.1-r0.trigger
OK: 98 MiB in 51 packages
+ docker-java-home
+ '[' /usr/lib/jvm/java-1.8-openjdk '=' /usr/lib/jvm/java-1.8-openjdk ]
Removing intermediate container 8b85cd2167c3
 ---> d022d548f703
Successfully built d022d548f703
```
</details>

**Comment by nowiks** [comment]
Hmm it is really strange:
Ubuntu 14.04:
 - Linux aspen 4.4.0-140-generic #166~14.04.1-Ubuntu SMP Sat Nov 17 01:52:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
on Ubuntu 18.04 the same problem

command:
"docker build --pull --no-cache . " where Dockerfile copied from https://github.com/docker-library/openjdk/tree/master/8/jdk/alpine  

output:
'Sending build context to Docker daemon  3.072kB
Step 1/8 : FROM alpine:3.9
3.9: Pulling from library/alpine
Digest: sha256:644fcb1a676b5165371437feaa922943aaf7afcfa8bfee4472f6860aad1ef2a0
Status: Image is up to date for alpine:3.9
 ---> 5cb3aa00f899
Step 2/8 : ENV LANG C.UTF-8
 ---> Running in 06e5335e1cf4
 ---> c0780ec49d89
Removing intermediate container 06e5335e1cf4
Step 3/8 : RUN {                echo '#!/bin/sh';               echo 'set -e';          echo;           echo 'dirname "$(dirname "$(readlink -f "$(which javac || which java)")")"';    } > /usr/local/bin/docker-java-home     && chmod +x /usr/local/bin/docker-java-home
 ---> Running in b528af4668cf
 ---> 5102debd197c
Removing intermediate container b528af4668cf
Step 4/8 : ENV JAVA_HOME /usr/lib/jvm/java-1.8-openjdk
 ---> Running in d408942f9a74
 ---> b61bf3097552
Removing intermediate container d408942f9a74
Step 5/8 : ENV PATH $PATH:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin
 ---> Running in 4d66ee46bb26
 ---> bea4f23eb1d9
Removing intermediate container 4d66ee46bb26
Step 6/8 : ENV JAVA_VERSION 8u191
 ---> Running in afd494ad1da0
 ---> 79c285020990
Removing intermediate container afd494ad1da0
Step 7/8 : ENV JAVA_ALPINE_VERSION 8.191.12-r0
 ---> Running in fb3fd6fc9251
 ---> e106eb2f6bc3
Removing intermediate container fb3fd6fc9251
Step 8/8 : RUN set -x   && apk add --no-cache           openjdk8="$JAVA_ALPINE_VERSION"         && [ "$JAVA_HOME" = "$(docker-java-home)" ]
 ---> Running in 20d4d50bacf6
+ apk add --no-cache 'openjdk8=8.191.12-r0'
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  openjdk8-8.201.08-r0:
    breaks: world[openjdk8=8.191.12-r0]
The command '/bin/sh -c set -x  && apk add --no-cache           openjdk8="$JAVA_ALPINE_VERSION"         && [ "$JAVA_HOME" = "$(docker-java-home)" ]' returned a non-zero code: 1
'

**Comment by J0WI** [comment]
I've already updated it manually, because the [update.sh job](https://doi-janky.infosiftr.net/job/update.sh/job/openjdk/) is failing
```
diff --git a/8/jdk/alpine/Dockerfile b/8/jdk/alpine/Dockerfile
index 2fecd63..fadbd6c 100644
--- a/8/jdk/alpine/Dockerfile
+++ b/8/jdk/alpine/Dockerfile
@@ -32,7 +32,7 @@ ENV JAVA_HOME /usr/lib/jvm/java-1.8-openjdk
 ENV PATH $PATH:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin
 
 ENV JAVA_VERSION 8u191
-ENV JAVA_ALPINE_VERSION 8.191.12-r0
+ENV JAVA_ALPINE_VERSION 8.201.08-r0
 
 RUN set -x \
        && apk add --no-cache \
```

**Comment by nowiks** [comment]
Hello,

Yes in the message I was able to read the problem:

"ERROR: unsatisfiable constraints:
openjdk8-8.201.08-r0:
breaks: world[openjdk8=8.191.12-r0]"

But I wasn't pretty sure. 

Right now everything is clear.

BR,
Rafal
