### ISSUE TITLE
Travis Build failing with arm32v7/openjdk:11

### ISSUE THREAD

**Issue by ZoltanSzilagyiCse** [docker-library/openjdk#309]
Travis Build fails with this error:

```
Sending build context to Docker daemon  452.2MB
Step 1/12 : FROM arm32v7/openjdk:11
11: Pulling from arm32v7/openjdk
no matching manifest for unknown in the manifest list entries
```

You can find more log here: https://api.travis-ci.com/v3/job/197770047/log.txt

I pulled the image on my raspberry pi without any issues. Can someone explain to me why this is happening?

**Comment by tianon** [comment]
`arm32v7/openjdk:11` is a manifest list (which is why it won't pull properly on amd64), so what you probably wanted was `arm32v7/openjdk:11-stretch`, although I'd also point out that it's likely becoming unsupported in https://github.com/docker-library/openjdk/pull/322.
