### ISSUE TITLE
Do we have any plans to make openjdk:12.0.1-slim ?

### ISSUE THREAD

**Issue by faisalp4p** [docker-library/openjdk#310]

**Comment by wglambert** [comment]
The latest `openjdk` images are built from Oracle instead of Debian. The current `openjdk:12` image is equivalent in size to `openjdk:11-slim` 
```console
$ docker images | grep openjdk
openjdk               12                  831a029b6add        2 weeks ago         470MB
openjdk               11-slim             5cc6ea6c24c4        4 weeks ago         468MB
openjdk               11                  0aa10063a184        4 weeks ago         815MB
```

While `openjdk:13` has an Alpine variant, this was deprecated with `openjdk:12` https://github.com/docker-library/openjdk/pull/281
>it appears OpenJDK has dropped Alpine builds from 12

**Comment by faisalp4p** [comment]
> The current openjdk:12 image is equivalent in size to openjdk:11-slim

Thanks for that useful piece of info :)

**Comment by stefan-it** [comment]
Why is "Oracle" used instead of Debian?

**Comment by wglambert** [comment]
Oracle Linux's latest builds are licensed under GPLv2 and allow for more timely updates by decoupling the Java version updates from package and version cycles of the different Linux distros.
https://github.com/docker-library/openjdk/issues/212 https://github.com/docker-library/openjdk/pull/235

**Comment by EricLemieux** [comment]
See #302 for a more detailed discussion about why Debian isn't being used as the base anymore.

**Comment by tianon** [comment]
Yep, `-slim` variants were an artifact of the Debian base in use and https://github.com/docker-library/openjdk/issues/302 is the appropriate place to discuss/follow that further. :+1:

**Comment by cscetbon** [comment]
Sorry for asking here but what about `12-jre` ? It seems `12.0.2-jdk-oracle` and `12.0.2-oracle` are the same size.

**Comment by yosifkit** [comment]
@cscetbon, There is no official JRE for 12+ (there wasn't even one for 11 until recently).

> JDK 11 has no official JRE build. The reason for this is that the "jlink" tool allows users to create precisely-targeted stripped JDK images for their applications, and this is IMO better for Docker than a JRE image.
>
> \- https://github.com/docker-library/openjdk/issues/320#issuecomment-494417274

See #322 that removed the 11-jre builds and this [commit](https://github.com/docker-library/openjdk/commit/572682ed1cb951ab8d978e8015e4a910093db920) that added it back.

**Comment by cscetbon** [comment]
got it, thanks @yosifkit
