### ISSUE TITLE
Git removed in 12-jdk

### ISSUE THREAD

**Issue by Stianhn** [docker-library/openjdk#311]
I'm upgrading from java 11 to 12 and I found that git have been removed in 12-jdk. Is this intentional? If yes, are there alternatives that includes git?

**Comment by wglambert** [comment]
The latest `openjdk` images are built from Oracle as opposed to the previous buildpack-deps
https://github.com/docker-library/openjdk/blob/ec1553cccfb87c5f53a38555771fa6d13cebfcba/11/jdk/Dockerfile#L7

With `openjdk:11` and before there was a `slim` variant, and with our `openjdk:12`+ images they are equivalent to that in size and we would like to keep them as such, especially with `git` being 150MB

What you can do is make a Dockerfile `FROM` this one and then add what you want to it

```console
$ docker build -t openjdk:git - <<EOF
FROM openjdk:12    
RUN yum install -y git; rm -rf /var/cache/yum
EOF

Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM openjdk:12
 ---> 831a029b6add
Step 2/2 : RUN yum install -y git; rm -rf /var/cache/yum
 ---> Using cache
 ---> 0394cd247012
Successfully built 0394cd247012
Successfully tagged openjdk:git

$ docker run --rm openjdk:git git --version
git version 1.8.3.1

$ docker images | grep openjdk
openjdk               git                 0394cd247012        8 minutes ago       619MB
openjdk               12                  831a029b6add        2 weeks ago         470MB
openjdk               11-slim             5cc6ea6c24c4        4 weeks ago         468MB
openjdk               11                  0aa10063a184        4 weeks ago         815MB
```
