### ISSUE TITLE
newest openjdk8 alpine image not on docker hub 

### ISSUE THREAD

**Issue by renstoonen** [docker-library/openjdk#312]
the 8u201-jdk-alpine3.9 image is still on dockerhub: https://github.com/docker-library/openjdk/blob/bbb929b5877fd14377f8b1d40a1eb1a9ebf39e2f/8/jdk/alpine/Dockerfile

 while the newer version, 8u212-jdk-alpine3.9 is already on the master branch, but this one isn't pushed to dockerhub yet : https://github.com/docker-library/openjdk/blob/master/8/jdk/alpine/Dockerfile

When can the newest image for alpine be expected on dockerhub?

**Comment by wglambert** [comment]
https://github.com/docker-library/official-images/pull/5861
