### ISSUE TITLE
Problem pulling openjdk on AArch64 

### ISSUE THREAD

**Issue by rhenwood-arm** [docker-library/openjdk#318]
I've just tried to pull an openjdk image on my AArch64 machine:

```
$ docker run --rm -it openjdk /bin/bash
Unable to find image 'openjdk:latest' locally
latest: Pulling from library/openjdk
docker: no matching manifest for linux/arm64 in the manifest list entries.
See 'docker run --help'.
```

Does anyone have a suggestion on debugging further?

**Comment by tianon** [comment]
This is an unfortunate consequence of https://github.com/docker-library/openjdk/pull/235 (and following PRs) -- Oracle doesn't publish AArch64 bits on https://jdk.java.net/. :disappointed:

**Comment by rhenwood-arm** [comment]
Thanks for the prompt reply!

What would you suggest I do if I want a version of java on AArch64?

**Comment by tianon** [comment]
I think the best two options are to consider AdoptOpenJDK (https://github.com/docker-library/official-images/pull/5710) or to contact Oracle and ask really nicely that they start publishing AArch64 bits on https://jdk.java.net/. :sweat_smile:

**Comment by rhenwood-arm** [comment]
Ok, I think I've got a bit confused and created noise. I was looking for 'openjdk' on my aarch64 machine.

Running using `docker run --rm -it openjdk /bin/bash` resulted in `no matching manifest`. Using `docker run --rm -it arm64v8/openjdk /bin/bash` works fine.

I am happy to recognize this is user error - but I feel like the arm64v8 platform bit of the label should be inferred I'm on a aarch64 (arm64v8 machine):

```
$ docker info
Containers: 10
 Running: 0
 Paused: 0
 Stopped: 10
Images: 94
Server Version: 18.09.6
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.6
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: aarch64
CPUs: 8
Total Memory: 15.61GiB
Name: xxxx
ID: xxxx
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

**Comment by tianon** [comment]
Oh no, your initial intuition was definitely correct -- the current `openjdk:latest` tag does not support arm64.

See https://github.com/docker-library/official-images/blob/master/library/openjdk for the canonical listing of tags+sources+architectures for `openjdk`.

What you're getting when you pull `arm64v8/openjdk:latest` is the last version of the `latest` tag which did support arm64, which is probably OpenJDK 11 based on Debian.  With 12+, the OpenJDK official has switched to using the official release artifacts from Oracle who do not (currently? :sweat_smile: :heart:) publish arm64 artifacts.

If you compare the output of `java -version`, that should be more apparent:

```console
$ # on x86
$ docker pull openjdk
Using default tag: latest
latest: Pulling from library/openjdk
Digest: sha256:1b8b7c7f36409ac92f1413adbbf74619d71cd9c73434237d344bdcd07c34b394
Status: Downloaded newer image for openjdk:latest
$ docker run --rm openjdk java -version
openjdk version "12.0.1" 2019-04-16
OpenJDK Runtime Environment (build 12.0.1+12)
OpenJDK 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)

$ # on arm64
$ docker pull arm64v8/openjdk
Using default tag: latest
latest: Pulling from arm64v8/openjdk
Digest: sha256:d863812cee34a595640f412171c86d9b81fefebd79fbb1a5409bb277a5667438
Status: Image is up to date for arm64v8/openjdk:latest
$ docker run --rm arm64v8/openjdk java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment (build 11.0.2+9-Debian-3bpo91)
OpenJDK 64-Bit Server VM (build 11.0.2+9-Debian-3bpo91, mixed mode)
```

If you try to use `openjdk:11` or `openjdk:8`, either of those should still have arm64 support and should work properly.

**Comment by gdams** [comment]
@rhenwood-arm as an alternative, the AdoptOpenJDK official image also provides arm64 support: https://hub.docker.com/_/adoptopenjdk

**Comment by tianon** [comment]
Also worth noting that the state of this has changed somewhat given #322:

```console
$ bashbrew cat openjdk | grep -B2 'arm64'
Tags: 11.0.3-jdk-stretch, 11.0.3-stretch, 11.0-jdk-stretch, 11.0-stretch, 11-jdk-stretch, 11-stretch
SharedTags: 11.0.3-jdk, 11.0.3, 11.0-jdk, 11.0, 11-jdk, 11
Architectures: amd64, arm64v8
--

Tags: 11.0.3-jdk-slim-stretch, 11.0.3-slim-stretch, 11.0-jdk-slim-stretch, 11.0-slim-stretch, 11-jdk-slim-stretch, 11-slim-stretch, 11.0.3-jdk-slim, 11.0.3-slim, 11.0-jdk-slim, 11.0-slim, 11-jdk-slim, 11-slim
Architectures: amd64, arm64v8
```

**Comment by dchuyko** [comment]
> Thanks for the prompt reply!
> 
> What would you suggest I do if I want a version of java on AArch64?
Try Liberica JDK: https://hub.docker.com/u/bellsoft

**Comment by santhosh-tekuri** [comment]
use `arm64v8/openjdk` from https://hub.docker.com/r/arm64v8/openjdk/
```
$ docker run arm64v8/openjdk:16 java -version
Unable to find image 'arm64v8/openjdk:16' locally
16: Pulling from arm64v8/openjdk
4a780b35fbf9: Pull complete
67b11c9e8386: Pull complete
37520f14a8b1: Pull complete
Digest: sha256:52f7ea847cd25ad7d6995f0e4c41c4ff7436c74e29d3257c2baaf6ef8012e014
Status: Downloaded newer image for arm64v8/openjdk:16
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9-24)
OpenJDK 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
```
