### ISSUE TITLE
OpenJFX can not be used anymore

### ISSUE THREAD

**Issue by jschneider** [docker-library/openjdk#323]
Since the latest switch to OpenJDK JavaFX is no longer supported.
In our docker image we install the openjfx package which adds several files to "/usr/lib/jvm/java-8-openjdk-amd64"

Could you add a possibility to enable JavaFX again for the latest docker files?

**Comment by tianon** [comment]
This is an unfortunate side effect of https://github.com/docker-library/openjdk/pull/322 -- previously when you did `apt-get install openjfx` you were getting JavaFX from Debian, which worked fine with the OpenJDK we also installed from Debian.  Now that we don't install OpenJDK from Debian, that OpenJFX package isn't going to work.

I'd recommend looking at https://openjfx.io/openjfx-docs/#install-javafx and getting OpenJFX more directly from the upstream OpenJFX project (or switching your `Dockerfile` to be `FROM debian:stretch` and continue to just `apt-get install openjfx`, which may or may not require `stretch-backports`).

**Comment by jschneider** [comment]
Yes, I realize the problem.
Unfortunately OpenJFX is only released for newer Java version (>8).

I worked around the issue by copying the jar files around. But wanted to report it to:
- maybe get it fixed
- give other people a chance to find an answer faster than I did


This works for me:

RUN cp /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/jfxrt.jar /usr/local/openjdk-8/jre/lib/ext \
    && cp /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/javafx.properties /usr/local/openjdk-8/jre/lib \
    && cp /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jfxswt.jar /usr/local/openjdk-8/jre/lib \
    && cp /usr/lib/jvm/java-8-openjdk-amd64/lib/ant-javafx.jar /usr/local/openjdk-8/lib \
    && cp /usr/lib/jvm/java-8-openjdk-amd64/lib/javafx-mx.jar /usr/local/openjdk-8/lib

**Comment by wglambert** [comment]
Yeah this looks resolved the best it can be, since JavaFX expects the Debian OpenJDK and we use a non-Debian build there isn't really a great way to make that work since there are differences between those builds.

Going to close since this isn't really an error with the image but an effect of the recent changes.

**Comment by qixiaobo** [comment]
So glad to see this. i will have a try

**Comment by qixiaobo** [comment]
I want use this https://github.com/sgerrand/alpine-pkg-java-openjfx

**Comment by qixiaobo** [comment]
![image](https://user-images.githubusercontent.com/2881751/132164452-5d82e6c8-ebed-49d1-86be-195e7f04ae73.png)

**Comment by qixiaobo** [comment]
bellsoft-java8 contains the full Liberica JDK, including JavaFX and a variety of JVMs for platforms which support it.
bellsoft-java8-runtime includes Liberica JRE with JavaFX.
I just use bellsoft-java8-Full

**Comment by qixiaobo** [comment]
```dockerfile
RUN wget -q -O - https://download.bell-sw.com/pki/GPG-KEY-bellsoft |  apt-key add - && \
    echo "deb [arch=amd64] https://apt.bell-sw.com/ stable main" |  tee /etc/apt/sources.list.d/bellsoft.list && \
    apt-get update && \
    apt-get -y install bellsoft-java8-full  java-common
#切换bellsoft
ENV JAVA_HOME=/usr/lib/jvm/bellsoft-java8-full-amd64
ENV PATH=/usr/lib/jvm/bellsoft-java8-full-amd64/bin:$PATH
```

**Comment by tianon** [comment]
This discussion is unrelated to this repository/issue -- please take it elsewhere.
