### ISSUE TITLE
latest version of openjdk:11-jdk-slim does not have stretch-backports anymore

### ISSUE THREAD

**Issue by michl-b** [docker-library/openjdk#324]
The latest version of openjdk:11-jdk-slim does not have stretch-backports as a apt reposotory anymore.

So the libs cannot be installed.

e.g.
`RUN apt-get -qq -y install libtcnative-1=1.2.21-1~bpo9+1`

**Comment by tianon** [comment]
Right, this is a bit of a side-effect of https://github.com/docker-library/openjdk/pull/322 -- we were previously including `stretch-backports` only because it's where we could get an up-to-date OpenJDK from Debian's repositories.  Now that we're pulling OpenJDK from a tarball more directly, it's no longer required in the image by default.

**Comment by songokudbz** [comment]
I have the same issue ... when will this be fixed? If I revert to openjdk:11.0.1-jdk-slim it works, but with openjdk:11-jdk-slim (which is 11.0.3 currently) it doesn't work.

**Comment by tianon** [comment]
As I noted in https://github.com/docker-library/openjdk/issues/324#issuecomment-496550217, `stretch-backports` was included as a side effect, so it being gone is not considered a bug.  I'd recommend updating your `Dockerfile` to include the one-liner to reintroduce it:

```dockerfile
FROM openjdk:11-jdk-slim-stretch
RUN echo 'deb http://deb.debian.org/debian stretch-backports main' > /etc/apt/sources.list.d/backports.list
```

**Comment by songokudbz** [comment]
Error on apt-get update:
"
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/rmid to provide /usr/bin/rmid (rmid) in auto mode
update-alternatives: error: error creating symbolic link '/usr/share/man/man1/rmid.1.gz.dpkg-tmp': No such file or directory
"

**Comment by songokudbz** [comment]
I've fixed it:
 - i've added mkdir -p /usr/share/man/man1
 - adjusted java.security path and java cacerts to /usr/local/openjdk-11/conf/security/java.security, respectively /usr/local/openjdk-11/lib/security/cacerts.

**Comment by michl-b** [comment]
Thanks a lot. 
As @tianon mentioned, i added the line to the Dockerfile. This worked fine for me.
