### ISSUE TITLE
uncessary package in openjdk:8-jre

### ISSUE THREAD

**Issue by souhaiebtar** [docker-library/openjdk#325]
just a question, is 
`adwaita-icon-theme` package  is a requirement, because it's in the image `openjdk:8-jre` because i checked the resource image `buildpack-deps:stretch-curl` and it doesn't contain that package

**Comment by tianon** [comment]
It likely comes in as part of `fontconfig`'s dependencies:

https://github.com/docker-library/openjdk/blob/2544422915ae09bf77b02f0afaadaad5ba204cef/Dockerfile-adopt-linux.template#L10-L13

If you want to trim out strictly unnecessary packages, I'd suggest using `openjdk:8-jre-slim` instead, which shouldn't contain this package.

**Comment by souhaiebtar** [comment]
@tianon thanks for the explanation, just i tried to help

**Comment by tianon** [comment]
Now that I'm at a proper keyboard and can test this, I'm actually having trouble reproducing:

```console
$ docker pull openjdk:8-jre
8-jre: Pulling from library/openjdk
Digest: sha256:b9c4c3fd01a6caee5b1412d90d8fee0023b15f52a2559d83259541a63662e613
Status: Image is up to date for openjdk:8-jre

$ docker run --rm openjdk:8-jre dpkg -l | grep icon
$ 
```

**Comment by tianon** [comment]
(Perhaps it was an older image?)

**Comment by souhaiebtar** [comment]
@tianon  i tested with the latest image and you are correct, there is no adwaita icon them, i will close it
