### ISSUE TITLE
openjdk:8-jre missing Java

### ISSUE THREAD

**Issue by majusko** [docker-library/openjdk#326]
When you run this:

FROM openjdk:8-jre
ENTRYPOINT ["/usr/bin/java", "-jar", "/usr/share/service.jar"]

Error: failed to start container "monitoring-dev": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/usr/bin/java\": stat /usr/bin/java: no such file or directory": unknown
Back-off restarting failed container

PS: 

I tried alpine image "FROM openjdk:8-jre-alpine" and it worked like a charm. There is some issue with the newest build.

**Comment by e-larrambebere** [comment]
We are also seeing this exact same issue:

> /usr/bin/java: no such file or directory": unknown

**Comment by wagam** [comment]
Hello, 
According to this Dockerfile: 
https://github.com/docker-library/openjdk/blob/282961c4ca0be09af7a556e38b8d5be0c2db0608/8/jre/Dockerfile#L20
the installation path has been updated and your entrypoint is probably "/usr/local/openjdk-8/jre/bin/java"

**Comment by e-larrambebere** [comment]
Just noticed that on line 21 of that Dockerfile they add JAVA_HOME to the path so the entrypoint could be just "java"

**Comment by majusko** [comment]
@e-larrambebere  Thank you. Just updated projects to use only java.
