### ISSUE TITLE
cacerts not updated with `update-ca-certificates`

### ISSUE THREAD

**Issue by ukabu** [docker-library/openjdk#327]
The usual way to add certificate to a debian system by copying them to `/usr/local/share/ca-certificates/` and running `update-ca-certificates` broke with the switch to AdoptOpenJDK.
We've tested with `openjdk:8` that was updated a few days ago (sha256:d318d6aeb831170ba394aae69e0c33cf4bcd4ab2a90ff60f50e68664fac09ecf).
Usually, `update-ca-certificates` updates `/etc/ssl/certs/java/cacerts` and this files is sim-linked in the jdk `jre/lib/security/cacerts`.
However since the switch to AdoptOpenJDK, it no longer happens.
We need to have a script like http://rabexc.org/posts/certificates-not-working-java#comment-4099504075 to update the JDK cacerts file.

**Comment by tianon** [comment]
Doh, really great catch -- I'd tested that CA certificates were working, but that was directly with the bundle included with the https://adoptopenjdk.net/upstream.html tarballs.  I'll get a fix PR up ASAP. :+1:

**Comment by tianon** [comment]
PR up at https://github.com/docker-library/openjdk/pull/328 :+1:
