### ISSUE TITLE
Dockerfile for openjdk:8u212-jre-alpine3.9 image missing

### ISSUE THREAD

**Issue by zencircle** [docker-library/openjdk#330]
Previous link to the Dockerfile returns 404
https://github.com/docker-library/openjdk/blob/master/8/jre/alpine/Dockerfile

**Comment by wglambert** [comment]
https://github.com/docker-library/openjdk/pull/322
>no more OpenJDK 8 Alpine images (Alpine/musl is not officially supported by the OpenJDK project

You could try [AdoptOpenJDK](https://hub.docker.com/r/adoptopenjdk/openjdk8) which is now an official-image https://github.com/docker-library/official-images/pull/5710 and supports Alpine

**Comment by tianon** [comment]
Also, if you go to https://github.com/docker-library/openjdk/commits/master/8/jre/alpine/Dockerfile you can see all the commits that changed that file and easily restore https://github.com/docker-library/openjdk/blob/ec1553cccfb87c5f53a38555771fa6d13cebfcba/8/jre/alpine/Dockerfile for your needs, although as you can see it's really not much more than `FROM alpine:3.9` followed by `RUN apk add --no-cache openjdk8-jre` (and setting `JAVA_HOME` appropriately, which you may or may not require).
