### ISSUE TITLE
Provide Alpine image with Java11

### ISSUE THREAD

**Issue by madmath03** [docker-library/openjdk#334]
Hi,

I'm aware the requests for Alpine images are quite frequent but I've got a good reason for this one : seems like Alpine added openjdk11 with this [PR](https://github.com/alpinelinux/aports/pull/6469)  🎉

**Comment by tianon** [comment]
It does appear that Alpine added OpenJDK 11, but with #322 we've stopped consuming releases from distributions entirely, instead preferring releases published and/or blessed by OpenJDK upstream and/or project leads for each release of OpenJDK, so unfortunately this means we won't be considering these Alpine packages.

OpenJDK currently has support for Alpine in the OpenJDK 13 Early Access releases, but unless the support and community behind [Project Portola](https://openjdk.java.net/projects/portola/) increases, it might not continue (as we saw when OpenJDK 12 went GA and the Alpine releases went away).

For users who want to use Alpine's packages, you'll have to use [Alpine Edge](https://pkgs.alpinelinux.org/packages?name=openjdk11*&branch=edge&arch=x86_64) (which is another thing we would've been wary of previously, given the experimental nature of Alpine's Edge/development repository):

```dockerfile
FROM alpine:edge
RUN apk add --no-cache openjdk11-jdk
```

**Comment by reitzig** [comment]
This is really unfortunate and hurts downstream projects.

For instance, while one could use Azul Zulu base images, derived images can not be published in "Official" projects (e.g. [Maven](https://github.com/carlossg/docker-maven/pull/120)).

FWIW, OpenJDK seems to be [part of the regular 3.10 repos](https://pkgs.alpinelinux.org/packages?name=openjdk11*&branch=v3.10&arch=x86_64)?
