### ISSUE TITLE
Freetype font library is missing

### ISSUE THREAD

**Issue by Martin1978** [docker-library/openjdk#335]
java.lang.UnsatisfiedLinkError: /usr/local/openjdk-8/jre/lib/amd64/libfontmanager.so: libfreetype.so.6: cannot open shared object file: No such file or directory

**Comment by tianon** [comment]
If you're on the slim variants, this is a duplicate of #333.  If you're not, we're going to need more information to reproduce your problem.

**Comment by Martin1978** [comment]
Yep I'm using the slim version. Thanks.
