### ISSUE TITLE
Java 11 JRE Images

### ISSUE THREAD

**Issue by AttwellBrian** [docker-library/openjdk#339]
Java 8 has both JRE and JDK images (which are mostly identical, except for the AdoptOpenJDK tar they download). 

Now that [AdoptOpenJDK/openjdk11-upstream-binaries](https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/) has some releases that contain jre tars, we should publish a Java 11 Docker JRE image, right?

**Comment by tianon** [comment]
If you look at https://adoptopenjdk.net/upstream.html, the latest GA releases don't have a JRE yet, so as soon as 11.0.4 drops officially, we will be adding JRE images accordingly.
