### ISSUE TITLE
Where did openjdk:8u131-jdk-alpine disappear to?

### ISSUE THREAD

**Issue by alexellis** [docker-library/openjdk#345]
We've been using `openjdk:8u131-jdk-alpine` for community usage of the OpenFaaS templates and I got an issue report from a user saying that he wanted a newer version of the OpenJDK 8 for Alpine Linux.

I came to the tags page and could only see JDK 13 / 14 listed, and the Dockerfiles are missing for the earlier builds.

Can you bring me up to speed please?

Thanks,

Alex

**Comment by tim-hellhake** [comment]
They are hidden on page 6.
https://hub.docker.com/_/openjdk?tab=tags&page=6.

**Comment by alexellis** [comment]
I'm not seeing the alpine version

**Comment by wglambert** [comment]
Alpine isn't officially supported by the OpenJDK project so our variants reflect that https://github.com/docker-library/openjdk/pull/322, https://github.com/docker-library/openjdk/issues/211#issuecomment-426708580, https://github.com/docker-library/openjdk/pull/235#issuecomment-424599754

13 and 14 uses the latest builds from https://jdk.java.net/13/
https://github.com/docker-library/openjdk/issues/272

**Comment by tim-hellhake** [comment]
Sorry I missed that.
Last alpine version seems to be 8u212-jdk-alpine. 
https://hub.docker.com/_/openjdk?tab=tags&page=23

**Comment by alexellis** [comment]
Tim perhaps we can use that version for now and Investigate the AWS distribution too?

**Comment by tim-hellhake** [comment]
Sounds good.
212 is way better than 131.

**Comment by tim-hellhake** [comment]
Azul seems to provide alpine images with the latest jdk8.
https://hub.docker.com/r/azul/zulu-openjdk-alpine

**Comment by alexellis** [comment]
Who is Azul?

**Comment by tim-hellhake** [comment]
A company specialized on the jvm.
They provide tck compliant jdk builds.

**Comment by yosifkit** [comment]
Since the "missing" Alpine-based images are on purpose, I'll close.

**Comment by alexellis** [comment]
Can you elaborate why they are missing "on purpose"?

**Comment by tianon** [comment]
See the links in @wglambert's comment above (https://github.com/docker-library/openjdk/issues/345#issuecomment-517357112) for details:

> Alpine isn't officially supported by the OpenJDK project so our variants reflect that #322, [#211 (comment)](https://github.com/docker-library/openjdk/issues/211#issuecomment-426708580), [#235 (comment)](https://github.com/docker-library/openjdk/pull/235#issuecomment-424599754)
> 
> 13 and 14 uses the latest builds from https://jdk.java.net/13/
> #272

The comment from https://github.com/docker-library/openjdk/pull/235#issuecomment-424599754 is particularly relevant:

> Yeah, the alpine port is not in a supported release, since it's not in the mainline code base, so it's only available as early access builds of OpenJDK Project Portola http://openjdk.java.net/projects/portola.  
> 
> It works, but at this stage it basically needs community contributors to help maintain it and get it into mainline - see https://twitter.com/MikaelVidstedt/status/984920426655526912 for details. Interested contributors should drop by portola-dev to discuss specifics.

In other words, the OpenJDK project does not (yet) officially support Alpine Linux.  The work to do so is in-progress, but has insufficient contributor support and help is needed.

To discuss this further, I'd recommend [joining the "portola-dev" mailing list](https://mail.openjdk.java.net/mailman/listinfo/portola-dev).
