### ISSUE TITLE
Support for Windows Server 2019 Core

### ISSUE THREAD

**Issue by mibollma** [docker-library/openjdk#357]
Is there any support planned for Windows Server 2019 Core?
The 2016 images e.g. winamd64/openjdk:11.0.4-jdk-windowsservercore-ltsc2016 does not seem to run on 2019 machines such as https://aws.amazon.com/marketplace/pp/B07R3V4X23

**Comment by tianon** [comment]
If you look at the version numbers in https://hub.docker.com/_/microsoft-windows-servercore, you can see that `ltsc2019` is currently the same version as `1809` (which is why we don't have an explicit "`ltsc2019`" variant -- it would be identical to `1809`).

**Comment by mibollma** [comment]
So you are saying when using 1809 it should run on core 2019?

**Comment by tianon** [comment]
Correct, which can be seen by pulling/running the `hello-world:latest` image (which includes a broad set of Windows OS versions via manifest list and Docker *should* automatically choose the most appropriate image):

```console
$ docker pull hello-world
Using default tag: latest
latest: Pulling from library/hello-world
Digest: sha256:b8ba256769a0ac28dd126d584e0a2011cd2877f3f76e093a7ae560f2a5301c00
Status: Image is up to date for hello-world:latest

$ docker run --rm hello-world
...
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (windows-amd64, nanoserver-1809)
...
```

**Comment by mibollma** [comment]
Okay thanks. I'll try that.
