### ISSUE TITLE
IBM container registry issue

### ISSUE THREAD

**Issue by tolvaly** [docker-library/openjdk#358]
Using the openjdk:11.0.4-jre-slim image, I got vulnerability issue on the ibm container registry with the following error:
"Upgrade openssl to >= 1.1.0k-1~deb9u1"

![image](https://user-images.githubusercontent.com/20593548/65492315-5e110300-deb9-11e9-8420-0bb677df26ae.png)

**Comment by wglambert** [comment]
```console
$ docker run -it --rm openjdk:11.0.4-jre-slim bash
root@5e57060aae08:/# openssl version
OpenSSL 1.1.1c  28 May 2019
```

**Comment by tolvaly** [comment]
Thank you! it seems the IBM image checker had an issue. Now is fixed on their end as well!
