### ISSUE TITLE
Create image for java 8u222 for Alpine linux

### ISSUE THREAD

**Issue by davidpiber** [docker-library/openjdk#363]
We are currently using openjdk:8u212-jre-alpine, but as requirements, we need to include  java 822 update for security reasons.

Are you creating a openjdk:8u222-jre-alpine image?

**Comment by wglambert** [comment]
See https://github.com/docker-library/openjdk/issues/272

Alpine isn't officially supported by the OpenJDK project https://github.com/docker-library/openjdk/pull/322
>no more OpenJDK 8 Alpine images (Alpine/musl is not officially supported by the OpenJDK project, so this reflects that -- see "Project Portola" for the Alpine porting efforts which I understand are still in need of help)

Also https://github.com/docker-library/openjdk/issues/211#issuecomment-426708580, https://github.com/docker-library/openjdk/pull/235#issuecomment-424599754
