### ISSUE TITLE
[proposal] support for pulling images of arm64 and other arches from openjdk repository

### ISSUE THREAD

**Issue by runzexia** [docker-library/openjdk#364]
Currently I can use docker buildx to build the image (using the same dockerfile).
But when the base image of the project is openjdk, I can't complete this step. I need to create another dockerfile. 
like https://github.com/kubesphere/docker-sonarqube/blob/kubesphere/7.4-community/Dockerfile-arm

**Comment by wglambert** [comment]
https://github.com/docker-library/golang/issues/304#issuecomment-536720249

```console
$ docker version | grep OS
 OS/Arch:           linux/amd64
  OS/Arch:          linux/amd64

$ docker pull arm64v8/openjdk:8-jdk
8-jdk: Pulling from arm64v8/openjdk
no matching manifest for linux/amd64 in the manifest list entries

$ docker pull arm64v8/openjdk:8-jdk-slim
8-jdk-slim: Pulling from arm64v8/openjdk
29b80961214d: Pull complete 
392e0924564e: Pull complete 
d15c6e01e710: Pull complete 
acba4335cd44: Pull complete 
b1f6a0f413ed: Pull complete 
Digest: sha256:728f475f19f5cfe7882c01aee76cd2f60f86be24de19bb7846e537413aefba8c
Status: Downloaded newer image for arm64v8/openjdk:8-jdk-slim
docker.io/arm64v8/openjdk:8-jdk-slim

$ docker pull arm64v8/openjdk:8-jdk-stretch
8-jdk-stretch: Pulling from arm64v8/openjdk
5894e2829197: Pull complete 
7a8e6888cee6: Pull complete 
8bf90e854779: Pull complete 
a4c8eeecda69: Pull complete 
84d24874c96b: Pull complete 
c0b183b74b0d: Pull complete 
46da99b9149b: Pull complete 
e5974158891e: Pull complete 
Digest: sha256:1fbd49e3fc5e53154fa93cad15f211112d899a6b0c5dc1e8661d6eb6c18b30a6
Status: Downloaded newer image for arm64v8/openjdk:8-jdk-stretch
docker.io/arm64v8/openjdk:8-jdk-stretch
```

**Comment by runzexia** [comment]
@wglambert 
Sorry, I didn't say the problem clearly.   
The alpine image as an example. The same tag in the alpine image will support multiple arches.
![image](https://user-images.githubusercontent.com/31230341/66593515-bcccc100-ebc9-11e9-8e4c-624c2f054bd2.png)
When I pull the image on a different arch host, docker will automatically pull the appropriate image.   When using cross-platform builds, `docker buildx` also will automatically handle this .  
So when I build an image based on alpine, I don't need to specify the image to pull `arm64v8`.

**Comment by james-crowley** [comment]
@runzexia What we need it a proper Docker manifest file to manage multi-archs. 

@tianon @yosifkit I know you guys are busy, but is something you guys would think about supporting? I would like to get `ppc64le` and `s390x` support going here.

It looks like [s390x](https://hub.docker.com/r/s390x/openjdk/) and [ppc64le](https://hub.docker.com/r/ppc64le/openjdk/) are getting built by their `buildslaves`, is that coming from the "official" image builds? I could never tracked down an answer for where the arch buildslaves come from.

**Comment by tianon** [comment]
See https://github.com/docker-library/openjdk/issues/272, especially the bits about where our actual artifacts come from, which will help explain why `s390x/openjdk` and `ppc64le/openjdk` are not currently being actively updated (note the "Updated 5 months ago" on the pages you linked).  If you scroll down to "Supported tags and respective `Dockerfile` links", you'll see both sections of tags are completely empty to reflect that.

So more concretely, for OpenJDK 8 and 11 to support more architectures, you'd need to convince the folks maintaining the builds at https://adoptopenjdk.net/upstream.html to include builds for the desired architectures.

For OpenJDK 13+, you'd need to convince Oracle to include the desired architectures on https://jdk.java.net/13/ + https://jdk.java.net/14/.

Regarding @runzexia's specific question about `arm64v8`, OpenJDK 11 is the only version for which any sort of official `arm64v8` builds exist, so thus that's the only version listed on https://hub.docker.com/r/arm64v8/openjdk.

That being said, there is now an explicit official AdoptOpenJDK image (https://hub.docker.com/_/adoptopenjdk) which does have much broader multi-architecture support.

**Comment by james-crowley** [comment]
@tianon Thanks for the response. I see what you saying now. I was unaware that OpenJDK's only "official" releases where for x86_64. Been relying and using packages compiled by various distros.

Going forward, is there away to make it more clear on `s390x/openjdk` and the various other architectures, that they are no longer receiving updates? Other then the last update was 5 months ago, it is not very clear to the user. 

> If you scroll down to "Supported tags and respective Dockerfile links", you'll see both sections of tags are completely empty to reflect that.

I know you mentioned this, but honestly to someone reading the page it just looked like someone did not fill out this section.

I think some sort of explicit warning would be a better idea. 

With that being said, I think the next best option is to use the AdoptOpenJDK image that you linked to.

**Comment by tianon** [comment]
Great idea -- https://github.com/docker-library/docs/pull/1585 implements a better message for that edge case :+1:
