### ISSUE TITLE
openjdk:11-jre-slim has timezone sync issue

### ISSUE THREAD

**Issue by haneefkassam** [docker-library/openjdk#365]
I'm trying to utilize 11-jre-slim docker tag to create a deployment image for my java application.  I have my own dockerfile, in which I'm running an "apt update", but running into an issue with the clock being out of sync.  This does not happen with the openjdk:11-jre image.  The difference in resulting docker images is ~100mb (so I'd like to use the slim version - in lieu of there not being an openjdk:11-alpine3 image to base off of)

11-jre-slim:
![image](https://user-images.githubusercontent.com/6538654/67113666-132c9780-f1a8-11e9-904f-ee97a1f933bf.png)

11-jre:
![image](https://user-images.githubusercontent.com/6538654/67113725-36574700-f1a8-11e9-9986-5f8b10569858.png)

**Comment by wglambert** [comment]
If you want to set the timezone you can use the `TZ` environment variable, I can't reproduce any issues with the repo list or timezone

```console
$ docker run -it --rm openjdk:11-jre-slim bash

root@0fff984f8995:/# apt update
Get:1 http://security-cdn.debian.org/debian-security buster/updates InRelease [39.1 kB]
Get:2 http://cdn-fastly.deb.debian.org/debian buster InRelease [122 kB]       
Get:3 http://cdn-fastly.deb.debian.org/debian buster-updates InRelease [49.3 kB]
Get:4 http://security-cdn.debian.org/debian-security buster/updates/main amd64 Packages [99.2 kB]
Get:5 http://cdn-fastly.deb.debian.org/debian buster/main amd64 Packages [7899 kB]
Get:6 http://cdn-fastly.deb.debian.org/debian buster-updates/main amd64 Packages [5792 B]
Fetched 8214 kB in 3s (3189 kB/s)                    
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
```
```console
$ docker run --rm openjdk:11-jre-slim date
Fri Oct 18 18:03:57 UTC 2019

$ docker run --rm -e TZ="America/Los_Angeles" openjdk:11-jre-slim date
Fri Oct 18 11:04:05 PDT 2019
```

**Comment by haneefkassam** [comment]
Ah.  this is good to know.

So, issue was resolved when I updated my VMs system clock (noticed it was set to the time indicated in the screenshot.  weird why it affected one tag but not another, but looks like it was a user error :(
