### ISSUE TITLE
Why does 13-alpine contain Java 13-ea?

### ISSUE THREAD

**Issue by lorenzleutgeb** [docker-library/openjdk#369]
`openjdk:13-alpine` contains an early-access release (its version number is suffixed with "-ea" as of 2019-11-11 even though Java 13 reached GA on 2019-09-17. I would expect a non-early-access release.

To verify:
```
$ podman run --pull always -ti openjdk:13-alpine java -version
Trying to pull docker.io/library/openjdk:13-alpine...
Getting image source signatures
Copying blob a8c71082b2bb skipped: already exists
Copying blob 050382585609 skipped: already exists
Copying config c4b0433a01 done
Writing manifest to image destination
Storing signatures
openjdk version "13-ea" 2019-09-17
OpenJDK Runtime Environment (build 13-ea+32)
OpenJDK 64-Bit Server VM (build 13-ea+32, mixed mode, sharing)
```

What I find interesting is that the contained Java version appears to have been built on the same day that it went GA so I would expect to not see the "-ea" suffix.

If that's intentional, then it's also quite confusing...

**Comment by wglambert** [comment]
See https://github.com/docker-library/openjdk/issues/272
https://github.com/docker-library/official-images/pull/6441#discussion_r312631824
https://jdk.java.net/13/
>The Alpine Linux build previously available on this page was removed as of the first JDK 13.0.1  release candidate. It’s not production-ready because it hasn’t been tested thoroughly enough to be considered a GA build. Please use the early-access JDK 14 Alpine Linux build in its place.

The

**Comment by lorenzleutgeb** [comment]
I saw that other issue and the referenced comment, but I couldn't understand them.

Does this imply that there will *never* be a stable (="considered GA") version of this image? Java 13 will be current until Java 14 is released. That should be plenty of time to have it "tested thoroughly"?

Then what is the most recent version of this image that does not ship an early-access build, but is based on Alpine Linux? Did no on "thoroughly test" any? It looks like it's not Java 12 either:

```
$ podman run --pull always -ti openjdk:12-alpine java -version
Trying to pull docker.io/library/openjdk:12-alpine...
Getting image source signatures
Copying blob 9716b977a99b skipped: already exists
Copying blob 6c40cc604d8e skipped: already exists
Copying config 0c68e7c5b7 done
Writing manifest to image destination
Storing signatures
openjdk version "12-ea" 2019-03-19
OpenJDK Runtime Environment (build 12-ea+29)
OpenJDK 64-Bit Server VM (build 12-ea+29, mixed mode, sharing)
```

**Comment by wglambert** [comment]
This is only for Alpine
Oracle/Debian/Slim are General-Availability

```console
$ docker run --rm openjdk:13 java -version
openjdk version "13.0.1" 2019-10-15
OpenJDK Runtime Environment (build 13.0.1+9)
OpenJDK 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)

$ docker run --rm openjdk:13-slim java -version
openjdk version "13.0.1" 2019-10-15
OpenJDK Runtime Environment (build 13.0.1+9)
OpenJDK 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)
```

**Comment by lorenzleutgeb** [comment]
Of course. But I am asking about Alpine because I want to use it, and not Oracle/Debian/Slim. Please be so kind and answer my questions about Alpine, instead of sidestepping them and talking about other Distros. Thank you.

**Comment by wglambert** [comment]
Your question would be better directed to the upstream project, in which the role of the Official-Images is maintaining a Dockerized implementation of what they offer. If they remove Alpine, then we remove Alpine

See Project Portola for Alpine porting efforts https://openjdk.java.net/projects/portola/

**Comment by lorenzleutgeb** [comment]
Thank you, I did not know that this project exists.
