### ISSUE TITLE
Error during connect with docker content trust

### ISSUE THREAD

**Issue by twistdmnd** [docker-library/openjdk#371]
There seems to be an issue with the latest docker engine release (19.03.5) where docker build fails with some images like the openjdk:latest one. Didn't have any issue yesterday (11-13). Since this works for some images like node, I'm assuming this has something to do with your docker image per se.

The steps to reproduce are:

1) Created a very simple dockerfile:
```
FROM openjdk:latest
RUN echo 'hello world'
```

2)
run:
```
export DOCKER_CONTENT_TRUST=1
docker build --no-cache -f docker/Dockerfile -t test:latest .
```

Actual results:
```
error during connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=docker%2FDockerfile2&labels=%7B%7D&memory=0&memswap=0&networkmode=default&nocache=1&rm=1&shmsize=0&t=patate%3Alatest&target=&ulimits=null&version=1: Error: trust data missing for remote repository docker.io/library/openjdk or remote repository not found: targets.cd9af02ef45897dc2a3a88165fda4d7984359605cb3d330f9db9c1bd189980dc trust data unavailable.  Has a notary repository been initialized?
```

**Comment by wglambert** [comment]
Looks like https://github.com/docker-library/official-images/issues/6838

**Comment by twistdmnd** [comment]
the workaround I used for now was to copy/paste the openjdk dockerfile entirely and append my original dockerfile content. Not ideal but it works for now...

**Comment by tianon** [comment]
Yeah, we have no control over this, unfortunately.  Closing as https://github.com/docker-library/official-images/issues/6838 is the appropriate/only place we can track this. :disappointed:
