### ISSUE TITLE
openjdk:8-jre-alpine3.9 unavailable entrypoint mode

### ISSUE THREAD

**Issue by duee** [docker-library/openjdk#373]
Dockerfile
-----------------------------------------
FROM openjdk:8-jre-alpine3.9
COPY admin-1.0.0.RELEASE.jar /admin/
COPY entrypoint.sh /admin/
RUN chmod +x /admin/entrypoint.sh
EXPOSE 8030
ENTRYPOINT  ["/admin/entrypoint.sh"]

entrypoint.sh
------------------------------------------
#!/bin/bash
echo "2019-11-20 15:17:03"
echo $PATH

Error prompt：standard_init_linux.go:178: exec user process caused "no such file or directory"

**Comment by wglambert** [comment]
Alpine doesn't have `bash`, you'll want to use `sh` or `ash`
https://github.com/docker-library/docs/tree/master/openjdk#openjdkversion-alpine
