### ISSUE TITLE
old bash and tar in JDK 13 vs JDK 11

### ISSUE THREAD

**Issue by pjungermann** [docker-library/openjdk#374]
openjdk:11-jdk — tar: version 1.29 (2015), bash 4.4.12(1)-release (2016)
openjdk:13-jdk — tar: version 1.26 (2011), bash 4.2.46(2)-release (2011)

openjdk:13-jdk-slim has more up-to-date ones, but is also based on debian:buster-slim

**Comment by wglambert** [comment]
The tag `openjdk:13-jdk` uses Oracle Linux 7 as the default https://github.com/docker-library/openjdk/blob/0a1e59a9fbc4f2cabaef69d9fede0ffe283dc431/13/jdk/oracle/Dockerfile
See issue https://github.com/docker-library/openjdk/issues/212, PR https://github.com/docker-library/openjdk/pull/235, and reference sheet https://github.com/docker-library/openjdk/issues/272
And the image tags https://github.com/docker-library/docs/tree/master/openjdk#simple-tags

`openjdk:11-jdk` uses Debian Stretch by default and doesn't have Oracle variants
Debian variants for the Oracle-consuming variants were re-added in https://github.com/docker-library/openjdk/pull/355, having been non-existent previously as there were [no Debian packages](https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=openjdk) on stable(Stretch or Buster) for 12+ https://github.com/docker-library/openjdk/issues/302#issuecomment-481022087

So you can also specify `openjdk:13-jdk-buster` which has Bash 5.0.3(1) and Tar 1.30
```console
$ docker run -it --rm openjdk:13-jdk-buster bash

root@fd7d9c6fe378:/# bash -version
GNU bash, version 5.0.3(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

root@fd7d9c6fe378:/# tar --version
tar (GNU tar) 1.30
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
```
