### ISSUE TITLE
Error 404  Not Found [IP: 151.101.188.204 80] in openjdk:8-jdk-slim

### ISSUE THREAD

**Issue by ifilonenko** [docker-library/openjdk#378]
We have been using `FROM openjdk:8-jdk-slim` in upstream spark.

We have suddenly began receiving errors in simple `apt-get update` commands with the following errors: 
```
Err:82 http://security-cdn.debian.org/debian-security buster/updates/main amd64 linux-libc-dev amd64 4.19.67-2+deb10u1
  404  Not Found [IP: 151.101.188.204 80]
```
Examples are shown in this JIRA ticket: https://issues.apache.org/jira/browse/SPARK-30111.

Any ideas where this suddenly came from?

**Comment by tianon** [comment]
I'm not able to reproduce -- is there any kind of firewall, proxy, or DNS hijacking happening in the environment where this is reproducible?

```console
$ docker pull openjdk:8-jdk-slim
8-jdk-slim: Pulling from library/openjdk
Digest: sha256:71592a5c3eecf243b624f0a718402bb54d9ccb282b3ae3aa108f62b5cd5539d1
Status: Image is up to date for openjdk:8-jdk-slim

$ docker run --rm openjdk:8-jdk-slim apt-get update
Get:1 http://cdn-fastly.deb.debian.org/debian buster InRelease [122 kB]
Get:3 http://cdn-fastly.deb.debian.org/debian buster-updates InRelease [49.3 kB]
Get:2 http://security-cdn.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:4 http://cdn-fastly.deb.debian.org/debian buster/main amd64 Packages [7908 kB]
Get:5 http://cdn-fastly.deb.debian.org/debian buster-updates/main amd64 Packages [5792 B]
Get:6 http://security-cdn.debian.org/debian-security buster/updates/main amd64 Packages [159 kB]
Fetched 8309 kB in 1s (7853 kB/s)
Reading package lists...
```

**Comment by ifilonenko** [comment]
Thanks for your extremely quick response!

```
Step 6/12 : RUN apt install -y python python-pip &&     apt install -y python3 python3-pip &&     rm -r /usr/lib/python*/ensurepip &&     pip install --upgrade pip setuptools &&     rm -r /root/.cache && rm -rf /var/cache/apt/*
```
is the command in question

**Comment by tianon** [comment]
See https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#apt-get, especially:

> Always combine `RUN apt-get update` with `apt-get install` in the same `RUN` statement.

**Comment by ifilonenko** [comment]
Is this the reason for our issue? odd that it comes up now to bite us :)

**Comment by tianon** [comment]
Yes, this is the reason for your issue.  Without doing `apt-get update`, your APT lists get outdated, and refer to package versions that no longer exist, hence the 404 trying to download them (Debian does not keep old versions in the archive when a package is updated).
