### ISSUE TITLE
Add Dockerfiles and builds for JDK 15-ea

### ISSUE THREAD

**Issue by sormuras** [docker-library/openjdk#380]
Same as https://github.com/docker-library/openjdk/pull/343 -- but for 15.

https://jdk.java.net/15

**Comment by tianon** [comment]
Nice, thanks for the poke!  PR up at #381. :+1:

**Comment by sormuras** [comment]
😉 

Thanks for adding it so quickly. https://github.com/sormuras/download-jdk could pick it up immediately:

![image](https://user-images.githubusercontent.com/2319838/71049507-d4cd3d80-2142-11ea-803f-0f1a004b167c.png)
