### ISSUE TITLE
java_home to jre_home

### ISSUE THREAD

**Issue by kmursk** [docker-library/openjdk#386]
In dockerfile for openjdk\<version>\jre variable JAVA_HOME is used. For example ```ENV JAVA_HOME C:\\openjdk-8```. But it's wrong, because this path specifies jre distribution kit. It would be better to change to variable JRE_HOME

**Comment by tianon** [comment]
The discussion on https://github.com/AdoptOpenJDK/openjdk-installer/issues/50 matches my own research and experience -- from what I've seen, tomcat is one of the only applications looking at `JRE_HOME`, and that it's very common to set `JAVA_HOME` to point to the JRE when there's no JDK installed.
