### ISSUE TITLE
windows server 2016 nanoserver

### ISSUE THREAD

**Issue by itsstillraining** [docker-library/openjdk#387]
Hi!
is it ok that  command _docker pull openjdk:8-nanoserver_ is not working now for windows server 2016? Command _docker pull openjdk:8u232-nanoserver_ is not working too. (no matching manifest for unknown in the manifest list entries)
docker pull openjdk:8 and openjdk:8u232 works fine.

**Comment by tianon** [comment]
Yes, that's expected; see https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/base-image-lifecycle -- Nano Server 2016 was EOL'd back in 2018.
