### ISSUE TITLE
Security Contact

### ISSUE THREAD

**Issue by jimk-osu** [docker-library/openjdk#388]
Is there an email contact for security findings?

**Comment by wglambert** [comment]
If it's related to CVE's we get reports of those quite frequently 
https://github.com/docker-library/faq#why-does-my-security-scanner-show-that-an-image-has-so-many-cves

https://github.com/docker-library/postgres/issues/655, https://github.com/docker-library/postgres/issues/286#issuecomment-302512767 docker-library/openjdk#161, docker-library/openjdk#112, docker-library/postgres#286, docker-library/drupal#84, docker-library/official-images#2740, docker-library/ruby#117, docker-library/ruby#94, docker-library/python#152, docker-library/php#242, docker-library/buildpack-deps#46, docker-library/openjdk#185.

**Comment by wglambert** [comment]
Going to close since there isn't an issue with the image. If you find an issue with the image itself feel free to make an issue for it
