### ISSUE TITLE
Use a smaller distro as base image

### ISSUE THREAD

**Issue by themasterchef** [docker-library/openjdk#39]
It appears that this official Java image currently uses Debian as its base. Some experiments have been done by people looking to shrink down their Java base images that merely require busybox:

- <https://registry.hub.docker.com/u/errordeveloper/oracle-jre/>
- <https://registry.hub.docker.com/u/errordeveloper/oracle-jdk/>

Appreciate that this requires *Oracle* not *Open* JDK, and that you guys have problems distributing that, but hopefully the general idea has come across: please could you look at using a smaller base distro than Debian, as this would improve build, push, and pull times considerably for us (and no doubt many others).

**Comment by md5** [comment]
This would be a breaking change for many users who have Docker images `FROM java` that also call `apt-get` and do other Debian-specific stuff: https://github.com/search?utf8=%E2%9C%93&q=from+java+apt-get&type=Code&ref=searchresults

**Comment by themasterchef** [comment]
Ah, hmm. That is a problem. Could you do something with either:

- versioning, to make sure that people who locked to current or older versions would keep getting a Debian base, while new pulls get something smaller (which is justifiable because if someone decides not to lock their java image version, they are implicitly accepting that they are willing to keep up with what upstream gives them)
- or branching, so an alternate branch of java offers the smaller base image while the Debian based one carries on in master

**Comment by JorritSalverda** [comment]
The JRE version depends on buildpack-deps:jessie-curl, whereas it doesn't need all those build tools the jdk might need.

Depending on debian:jessie instead and installing curl in this Dockerfile schrinks the resulting image by 31MB.

**Comment by md5** [comment]
@JorritSalverda :+1:

**Comment by md5** [comment]
I think a PR would be welcome.

**Comment by yosifkit** [comment]
The problem is that some users and tools prefer wget and some curl, so `buildpack-deps:jessie-curl` has both plus ca-certs for https connections.

**Comment by tianon** [comment]
Both wget and curl are really tiny too.

**Comment by md5** [comment]
@tianon The problem is that there could be things other than `wget` and `curl` that users have used in their derived Dockerfiles because they saw that they worked.

It would be nice to an exact list of the packages that would be dropped by the proposed change. That could give a better sense of the potential impact.

**Comment by yosifkit** [comment]
```diff
$ diff -u <(docker run --rm debian dpkg-query -W -f='${Package}\n' | sort) <(docker run --rm buildpack-deps:curl dpkg-query -W -f='${Package}\n' | sort)
--- /dev/fd/63	2015-08-28 15:25:08.332529507 -0700
+++ /dev/fd/62	2015-08-28 15:25:08.333529464 -0700
@@ -5,7 +5,9 @@
 base-passwd
 bash
 bsdutils
+ca-certificates
 coreutils
+curl
 dash
 debconf
 debconf-i18n
@@ -42,25 +44,44 @@
 libc-bin
 libcomerr2
 libcryptsetup4
+libcurl3
 libdb5.3
 libdebconfclient0
 libdevmapper1.02.1
+libffi6
 libgcc1
 libgcrypt20
+libgmp10
+libgnutls-deb0-28
 libgpg-error0
+libgssapi-krb5-2
+libhogweed2
+libicu52
+libidn11
+libk5crypto3
+libkeyutils1
 libkmod2
+libkrb5-3
+libkrb5support0
+libldap-2.4-2
 liblocale-gettext-perl
 liblzma5
 libmount1
 libncurses5
 libncursesw5
+libnettle4
+libp11-kit0
 libpam0g
 libpam-modules
 libpam-modules-bin
 libpam-runtime
 libpcre3
 libprocps3
+libpsl0
 libreadline6
+librtmp1
+libsasl2-2
+libsasl2-modules-db
 libselinux1
 libsemanage1
 libsemanage-common
@@ -68,8 +89,11 @@
 libslang2
 libsmartcols1
 libss2
+libssh2-1
+libssl1.0.0
 libstdc++6
 libsystemd0
+libtasn1-6
 libtext-charwidth-perl
 libtext-iconv-perl
 libtext-wrapi18n-perl
@@ -86,6 +110,7 @@
 ncurses-base
 ncurses-bin
 netbase
+openssl
 passwd
 perl-base
 procps
@@ -101,4 +126,5 @@
 tzdata
 udev
 util-linux
+wget
 zlib1g
```

**Comment by md5** [comment]
Umm... This is the `Dockerfile` for `buildpack-deps:curl`, so I think this whole thing may be moot.

```Dockerfile
RUN apt-get update && apt-get install -y --no-install-recommends \
		ca-certificates \
		curl \
		wget \
	&& rm -rf /var/lib/apt/lists/*
```

**Comment by md5** [comment]
I thought it perhaps had a few extra packages in it.

**Comment by tianon** [comment]
We added some initial Alpine variants which were later expanded in https://github.com/docker-library/openjdk/pull/62, which are _much_ smaller:
```console
$ docker images openjdk
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
openjdk             latest              69a777edb6dc        11 days ago         643 MB
openjdk             alpine              f1da3c7976d0        6 weeks ago         144.9 MB
```
