### ISSUE TITLE
issues when using Windows Server container images with the February 11, 2020 security update release

### ISSUE THREAD

**Issue by pso-digital-identity** [docker-library/openjdk#395]
Hi,

After applying the February 11 security update to a Windows 2016 host, my containers are silently failing as described as symptom 4 here: https://support.microsoft.com/en-us/help/4542617/you-may-encounter-issues-when-using-windows-server-docker-container-im

I'm using openjdk:11-jdk-windowsservercore-ltsc2016

It looks like that image is based on windows version 10.0.14393.3443 (January update) (source: https://github.com/docker-library/repo-info/blob/master/repos/openjdk/remote/11-jdk-windowsservercore-ltsc2016.md)

According to the MS article I need to match the version of the container image with the version of my container host operating system which is currently 10.0.14393.3504 (February update).

Will the 11-jdk-windowsservercore-ltsc2016 image get updated to this new Windows version automatically at some point? Or do i need to request an update somewhere?

Best regards
Peter

**Comment by mjvk** [comment]
Doesn't the CI just need a kick? I don't see an explicit version anywhere in the code.

**Comment by yosifkit** [comment]
We periodically pull the windows base images and rebuild to get the patch updates. Since your host is newer, you should be able to run them with `--isolation=hyperv` as a workaround.

It looks like our Windows builder is having issues; I'm working to get it back online and building.

**Comment by yosifkit** [comment]
Server is back up and builds are in process.

**Comment by pso-digital-identity** [comment]
Thanks a lot :-)
