### ISSUE TITLE
Allow java to handle dynamic dns resolution(like in k8s)

### ISSUE THREAD

**Issue by puneetloya** [docker-library/openjdk#397]
Adding something like: networkaddress.cache.ttl=20  by default. Is it worth it?
A docker container is supposed to handle changing IPs especially when you are running them mostly in k8s or other container orchestration platform.

**Comment by wglambert** [comment]
I think having the users supply their own `java.security` settings for what they would want works fine as-is. This doesn't seem so critical as to warrant changing the default caching policy

This value can also be modified on a per-application basis https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-jvm-ttl.html
