### ISSUE TITLE
openjdk:latest uses 13.0.2 and not 14

### ISSUE THREAD

**Issue by delabassee** [docker-library/openjdk#398]
OpenJDK 14 has been released this week but `openjdk:latest`, `openjdk:jdk`, `openjdk` are still on 13.0.2.

**Comment by yosifkit** [comment]
It looks like https://github.com/docker-library/official-images/issues/5216 again :disappointed: We'll get those fixed as soon as we can.

**Comment by yosifkit** [comment]
Should be fixed now!
