### ISSUE TITLE
openjdk alpine jre 11

### ISSUE THREAD

**Issue by prasad-1210** [docker-library/openjdk#403]
Hello All,

As i can see now Alpine repository providing openjdk11 from its apk repository (http://dl-cdn.alpinelinux.org/alpine/edge/community), is it possible to restart generating alpine varients for jdk 8 and jdk 11? like 

openjdk:11-jre-alpine 
openjdk:8-jre-alpine (last updated one year ago)

**Comment by wglambert** [comment]
OpenJDK 11 on Alpine isn't officially supported by the OpenJDK project https://github.com/docker-library/openjdk/issues/211#issuecomment-426708580, https://github.com/docker-library/openjdk/issues/212#issuecomment-424453577, https://github.com/docker-library/openjdk/pull/235#issuecomment-424599754

https://github.com/docker-library/openjdk/issues/272
