### ISSUE TITLE
Why new Java 8 images published by OpenJDK are no longer Alpine based but Debian 10(Buster) based?

### ISSUE THREAD

**Issue by Duke4848** [docker-library/openjdk#405]
I am browsing newest images published by OpenJDK: https://hub.docker.com/layers/openjdk/library/openjdk/8u252-jre-slim-buster/images/sha256-01dfdeac537b9d9adcb2399028fba063733a77186c5264e6b059987002c0e48c?context=explore all of them switchedt

all of the new Java 8 images are using Debian based, is there any official statement that OpenJDK moved from Alpine towards Debian and why? I have nothing against it, I'd like to understand,

Why new Java 8 images published by OpenJDK are no longer Alpine based but Debian 10(Buster) based?

**Comment by tianon** [comment]
OpenJDK 8 on Alpine isn't officially supported by the OpenJDK project https://github.com/docker-library/openjdk/issues/211#issuecomment-426708580, https://github.com/docker-library/openjdk/issues/212#issuecomment-424453577, https://github.com/docker-library/openjdk/pull/235#issuecomment-424599754

https://github.com/docker-library/openjdk/issues/272

**Comment by yosifkit** [comment]
Also, `openjdk:8` Linux tags that did not have `alpine` in the name have always been Debian based.  Alpine based images have only been an explicit opt-in.
