### ISSUE TITLE
s390x architecture (IBM-Z) out of support?

### ISSUE THREAD

**Issue by root4004** [docker-library/openjdk#408]
For s390x architecture (IBM-Z) the latest image version is 11.0.3-jre-slim-stretch. 

Are there any plans to build latest versions for this architecture?

**Comment by wglambert** [comment]
A lot of architectures were lost when shifting to AdoptOpenJDK as the binary source https://github.com/docker-library/official-images/pull/5953
>-arm32v5, arm32v7, i386, ppc64le, s390x

Full discussion on the change https://github.com/docker-library/openjdk/pull/322#issuecomment-495215927
>I know IBM has been keen on ppc64le and s390x in the past, but they're shifting their focus almost entirely to AdoptOpenJDK (as I've understood), so those likely aren't going to be a very heavy loss here (as much as I personally enjoy them 😄).
