### ISSUE TITLE
openjdk:8u252 image missing geotrustglobalca cert in keystore

### ISSUE THREAD

**Issue by akshay-das** [docker-library/openjdk#414]
The new openjdk:8u252 image which was updated 3 days back doesn't have geotrustglobalca cert in keystore, it has only 126 entries in keystore where as version 8u242 has 128 entries. This is causing the below error :

```
"type": "class sun.security.provider.certpath.SunCertPathBuilderException",
            "message": "unable to find valid certification path to requested target",
            "stack": [
                "sun.security.provider.certpath.SunCertPathBuilder::build(SunCertPathBuilder.java::141)",
                "sun.security.provider.certpath.SunCertPathBuilder::engineBuild(SunCertPathBuilder.java::126)",
                "java.security.cert.CertPathBuilder::build(CertPathBuilder.java::280)",
                "sun.security.validator.PKIXValidator::doBuild(PKIXValidator.java::445)",
                "sun.security.validator.PKIXValidator::engineValidate(PKIXValidator.java::317)",
                "sun.security.validator.Validator::validate(Validator.java::262)",
                "sun.security.ssl.X509TrustManagerImpl::validate(X509TrustManagerImpl.java::330)",
                "sun.security.ssl.X509TrustManagerImpl::checkTrusted(X509TrustManagerImpl.java::237)",
                "sun.security.ssl.X509TrustManagerImpl::checkServerTrusted(X509TrustManagerImpl.java::132)",
                "sun.security.ssl.ClientHandshaker::serverCertificate(ClientHandshaker.java::1670)",
                "sun.security.ssl.ClientHandshaker::processMessage(ClientHandshaker.java::226)",
                "sun.security.ssl.Handshaker::processLoop(Handshaker.java::1082)",
                "sun.security.ssl.Handshaker::process_record(Handshaker.java::1010)",
                "sun.security.ssl.SSLSocketImpl::readRecord(SSLSocketImpl.java::1079)",
                "sun.security.ssl.SSLSocketImpl::performInitialHandshake(SSLSocketImpl.java::1388)",
                "sun.security.ssl.SSLSocketImpl::startHandshake(SSLSocketImpl.java::1416)",
                "sun.security.ssl.SSLSocketImpl::startHandshake(SSLSocketImpl.java::1400)",
                "sun.net.www.protocol.https.HttpsClient::afterConnect(HttpsClient.java::559)",
                "sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection::connect(AbstractDelegateHttpsURLConnection.java::185)",
                "sun.net.www.protocol.http.HttpURLConnection::getOutputStream0(HttpURLConnection.java::1340)",
                "sun.net.www.protocol.http.HttpURLConnection::getOutputStream(HttpURLConnection.java::1315)",
                "sun.net.www.protocol.https.HttpsURL

ConnectionImpl::getOutputStream(HttpsURLConnectionImpl.java::264)",
```

Steps to get the cert 

1. exec into the container
2. Run `keytool -list -v -keystore /usr/local/openjdk-8/jre/lib/security/cacerts`  output will be [bad.txt](https://github.com/docker-library/openjdk/files/4774801/bad.txt)

**Comment by ejoncas** [comment]
I ran into this issue as well with the updated tag `openjdk:11.0`

Reverted to `openjdk:11.0.6` fixed the issue.

Apparently there is no ca-certs installed anymore. Is this expected? I could not find any release notes explaining this change.

**Comment by tianon** [comment]
The `openjdk:11` image *does* have `ca-certificates` installed:

```console
$ docker pull openjdk:11
11: Pulling from library/openjdk
Digest: sha256:43b4a74e4c7698e71ab00cfbbbbafffadc0d49f2c1e3432340500a5ec233cc7c
Status: Image is up to date for openjdk:11
docker.io/library/openjdk:11

$ docker run --rm openjdk:11 dpkg -l | grep ca-certificates
ii  ca-certificates            20200601~deb10u1            all          Common CA certificates
```

What you're likely running into is the update to `20200601~deb10u1`, detailed in https://tracker.debian.org/news/1150838/accepted-ca-certificates-20200601deb10u1-source-into-proposed-updates-stable-new-proposed-updates/, which updated the certificate bundle to the latest available (including removing expired and known-bad certificates).

(We don't explicitly control which certificates end up in the images we publish -- we simply make sure that Debian's `ca-certificates` package is installed, and that the certificates it knows about end up packaged in the certbundle that OpenJDK references).

**Comment by ejoncas** [comment]
Hi @tianon thanks for that.

Is there any details on what tags you guys override when publishing images? I would have thought that `11.0` is a fixed tag.

I know people override the `latest` tag all the time and you can get different results.  But I didn't thought that was the case for `openjdk:11.0`.

I'm now using `openjdk:11.0.6` will that be guaranteed to stay the same and not get replaced with something else?

**Comment by tianon** [comment]
All we guarantee with a tag like `openjdk:11.0.6` is that it contains OpenJDK 11.0.6.

If your tolerance for change is "none", you should use a content addressable digest instead.

If you do have some tolerance for change, then looking at https://github.com/docker-library/docs/blob/master/openjdk/README.md#supported-tags-and-respective-dockerfile-links, you can see that each variant has several tags to allow you to choose which things matter to you.

For example, if you want to make sure you stay on Debian Buster with OpenJDK 11, you should probably choose `openjdk:11-buster` or `openjdk:11-jdk-buster`.

Again though, it sounds like your tolerance for change is lower, so you should probably be using a content addressable digest instead to ensure you get exactly the same image every time you pull.

**Comment by tianon** [comment]
(That all being said, the `openjdk:11.0.6` tag is now unsupported as of 11.0.7, so that tag will indeed not be touched again unless upstream "unreleases" 11.0.7, which is unprecedented for OpenJDK.)
