### ISSUE TITLE
How are CA certs managed?

### ISSUE THREAD

**Issue by sixcorners** [docker-library/openjdk#416]
openjdk:14
update-ca-trust updates /etc/pki/ca-trust/extracted/java/cacerts but not /usr/java/openjdk-14/lib/security/cacerts
openjdk:alpine
update-ca-certificates updates /etc/ssl/certs/java/cacerts which is symlinked by /usr/lib/jvm/java-1.8-openjdk/jre/lib/security
so this works fine out of the box
openjdk:14-alpine
you have to install java-cacerts then symlink /opt/java/lib/security/cacerts to /etc/ssl/certs/java/cacerts yourself

Is this something that can or should be fixed? I'm not really sure.

**Comment by yosifkit** [comment]
This is basically the same as #328/#327, but neither Alpine nor Oracle Linux have a simple hook like `/etc/ca-certificates/update.d/` so that fix is currently only available in the Debian based images.

**Comment by tianon** [comment]
Alpine fix is in https://github.com/docker-library/openjdk/pull/418, but the Oracle Linux fix is probably going to be more complicated. :disappointed:

**Comment by tianon** [comment]
Hah, the `update-ca-trust` in Oracle Linux ends with the line `/usr/bin/p11-kit extract --format=java-cacerts --filter=ca-anchors --overwrite --purpose server-auth $DEST/java/cacerts`, so it really is going to be just as easy (slightly easier, even).  Will have another PR up shortly.

**Comment by sixcorners** [comment]
Sweet thanks!
