### ISSUE TITLE
Why openjdk 8 docker image is that big?

### ISSUE THREAD

**Issue by kisbalazspatrik** [docker-library/openjdk#417]
`openjdk                           8                   ba05e3b268fc        12 days ago         5.2GB`

That happens, whenever i try to use openjdk 8, other versions are fine

**Comment by wglambert** [comment]
What's your Dockerfile

```console
$ docker images | grep openjdk
openjdk             8-slim              ceab49f001b1        12 days ago         285MB
openjdk             8                   b190ad78b520        12 days ago         510MB
openjdk             8-alpine            a3562aa0b991        13 months ago       105MB
```

**Comment by tianon** [comment]
Also, are you (perhaps accidentally) using Windows containers?

**Comment by kisbalazspatrik** [comment]
Dockerfile first row:
FROM openjdk:8

**Comment by kisbalazspatrik** [comment]
> Also, are you (perhaps accidentally) using Windows containers?

Thank you, i didnt know about that, but that was the problem!
