### ISSUE TITLE
CI failure looks to be preventing 11.0.8 release

### ISSUE THREAD

**Issue by chadselph** [docker-library/openjdk#421]
11.0.8 was released on Tuesday but it looks like it’s not on Dockerhub yet thanks to this CI failure. 

https://github.com/docker-library/openjdk/actions/runs/170029566

I’m not sure if github issues is the right place to bring this up, but I couldn’t find another way to report.

**Comment by tianon** [comment]
This is a fine place to report, thanks! :+1:

The CI you've linked to is just for a basic smoke test -- it doesn't have anything to do with the actual (official) builds that end up on https://hub.docker.com/_/openjdk.  The test failure there is a quirk of how that test runs for JRE variants (it has to use the JDK to build the `.java` file to test it, and the JDK version it's trying to use isn't available yet).

For the official builds, https://github.com/docker-library/faq#an-images-source-changed-in-git-now-what explains the full process (end to end), and we're currently at https://github.com/docker-library/official-images/pull/8365 (which should be merged and start building soon).
