### ISSUE TITLE
image issues  openjdk:11.0.8-jre

### ISSUE THREAD

**Issue by annata** [docker-library/openjdk#422]
my application base image is openjdk:11.0.6-jre ,it work good
when i upgrade to openjdk:11.0.8-jre ,throw exception

! Causing: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
! at java.base/sun.security.validator.PKIXValidator.doBuild(Unknown Source)
! at java.base/sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
! at java.base/sun.security.validator.Validator.validate(Unknown Source)
! at java.base/sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
! at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
! at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
! at io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$ExtendedTrustManagerVerifyCallback.verify(ReferenceCountedOpenSslClientContext.java:242)
! at io.netty.handler.ssl.ReferenceCountedOpenSslContext$AbstractCertificateVerifier.verify(ReferenceCountedOpenSslContext.java:655)
! ... 27 common frames omitted
! Causing: javax.net.ssl.SSLHandshakeException: General OpenSslEngine problem
! at io.netty.handler.ssl.ReferenceCountedOpenSslContext$AbstractCertificateVerifier.verify(ReferenceCountedOpenSslContext.java:659)
! at io.netty.internal.tcnative.SSL.readFromSSL(Native Method)
! at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.readPlaintextData(ReferenceCountedOpenSslEngine.java:575)
! at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1124)
! at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1236)
! at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1279)
! at io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:217)
! at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1301)
! at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1215)
! at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1249)
! at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
! at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
! at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
! at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
! at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
! at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
! at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
! at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656)
! at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:591)
! at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:508)
! at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470)
! at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
! at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
! at java.base/java.lang.Thread.run(Unknown Source)

**Comment by wglambert** [comment]
Can you give all the commands you ran and any relevant files or logs for reproducing the issue

**Comment by wglambert** [comment]
Looks like https://github.com/docker-library/openjdk/issues/414

**Comment by annata** [comment]
same issues #414
