### ISSUE TITLE
JRE 11.0.8/OpenJ9 Alpine image size growth

### ISSUE THREAD

**Issue by cnocula-i** [docker-library/openjdk#426]
The latest JRE / Alpine image `jre-11.0.8_10_openj9-0.21.0-alpine` grew significantly to 122.75 MB (previously 49.08 MB for `jre-11.0.7_10_openj9-0.20.0-alpine`).
A quick inspection revealed, that the following files exist under the `/tmp` directory:
```
-rw-r--r--    1 root     root     156098560 Jul 20 18:38 gcc-libs.tar
-rw-r--r--    1 root     root      33041312 Jul 20 18:38 gcc-libs.tar.zst
```
Is this some build artifact or actually necessary for the latest versions?

**Comment by wglambert** [comment]
You're looking for https://github.com/eclipse/openj9/issues

https://hub.docker.com/r/adoptopenjdk/openjdk11-openj9
>Where to report problems: [GitHub](https://github.com/eclipse/openj9/issues)

**Comment by tianon** [comment]
Indeed, we don't currently support any version of OpenJDK 11 on Alpine.
