### ISSUE TITLE
Package manager like YUM or dnf are not available anymore on openjdk:14.0-jdk and openjdk:16-jdk

### ISSUE THREAD

**Issue by claudioerichsen** [docker-library/openjdk#429]
Until yesterday there was YUM available on openjdk:14.0-jdk. Now there is no YUM and no dnf anymore.

**Comment by wglambert** [comment]
https://github.com/docker-library/openjdk/pull/425#issuecomment-663640853

**Comment by tianon** [comment]
Yep, this is by design.  If you want the older image based on Oracle Linux 7, you should switch from `openjdk:14-jdk` to something slightly more specific like `openjdk:14-jdk-oraclelinux7`.

The updated images are based on Oracle Linux 8, and thus have `microdnf` instead.

**Comment by Chuxel** [comment]
Wow this is really frustrating. Existing Dockerfiles basing on yum break.

**Comment by wglambert** [comment]
Technically the existing Dockerfiles remain as-is, but the tags for the `latest` variants have the update

You could use a version from before the image update https://github.com/docker-library/repo-info/tree/8579a8cffa1d5ad9fd1b04faa3fa499c2e239bc5/repos/openjdk/remote

```console
$ docker run -it --rm openjdk@sha256:00014063d49f777891646a121f70e6721c61c17db81e624125c1dedd1c8b1fc5 bash
Unable to find image 'openjdk@sha256:00014063d49f777891646a121f70e6721c61c17db81e624125c1dedd1c8b1fc5' locally
sha256:00014063d49f777891646a121f70e6721c61c17db81e624125c1dedd1c8b1fc5: Pulling from library/openjdk
bce8f778fef0: Pull complete 
2778faef3420: Pull complete 
945a8b67ac57: Pull complete 
Digest: sha256:00014063d49f777891646a121f70e6721c61c17db81e624125c1dedd1c8b1fc5
Status: Downloaded newer image for openjdk@sha256:00014063d49f777891646a121f70e6721c61c17db81e624125c1dedd1c8b1fc5

bash-4.2# yum update
Loaded plugins: ovl
ol7_latest                                                                        | 2.7 kB  00:00:00     
(1/3): ol7_latest/x86_64/updateinfo                                               | 2.9 MB  00:00:00     
(2/3): ol7_latest/x86_64/group                                                    | 660 kB  00:00:00     
(3/3): ol7_latest/x86_64/primary_db                                               |  36 MB  00:00:00     
Resolving Dependencies
. . .
```

**Comment by Chuxel** [comment]
Yeah if you're grabbing `openjdk:14-jdk` you get this update - I found `groupadd` was also missing.  Things just stopped working suddenly as people got the update from a pull (since what was on disk from before would work).  Personally, I would have kept what was out there at `oraclelinux7` and added the `oraclelinux8` tag as an option, then defaulted to that with newer versions to avoid the problem.

Debian seems to be a safer bet in this regard, so we can pin to that instead.
