### ISSUE TITLE
openjdk:14.0.2: ANSI_X3.4-1968 encoding instead of UTF-8

### ISSUE THREAD

**Issue by kliakos** [docker-library/openjdk#430]
The default encoding in `openjdk:14.0.2` has changed from previously `UTF-8` to `ANSI_X3.4-1968`.

![image](https://user-images.githubusercontent.com/5412103/91565198-80719300-e94a-11ea-90a5-f9cdf99ee4f3.png)

**Comment by yosifkit** [comment]
That does seem like a bug and we should fix it if possible. It is likely to be caused by `openjdk:14.0.2` changing from Oracle Linux 7 to Oracle Linux 8. If you want to stick to 7, then you need to use more specific tags: `openjdk:14.0.2-oraclelinux7`.

**Comment by tianon** [comment]
Aha, I found the source of the issue!  Oracle Linux 7 didn't have `C.UTF-8`, so we used `en_US.UTF-8` there instead, but Oracle Linux 8 now doesn't have `en_US.UTF-8` but *does* have `C.UTF-8`.  I'll have a PR up shortly. :+1:
