### ISSUE TITLE
Error docker pull openjdk in raspberry

### ISSUE THREAD

**Issue by ssg127** [docker-library/openjdk#432]
Hi, I've installed docker on my raspberry pi 4 model B and now I want to run openjdk in version 13. I use `docker pull openjdk:13.0.2` to pull the image but I get the error:

> 13.0.2: Pulling from library/openjdk
> no matching manifest for linux/arm/v7 in the manifest list entries

I've tried the default tag but the error is the same.

I'm using Noobs as OS and I've tried to run `docker run hello-world` to test that docker is working and it works ok.

**Comment by ssg127** [comment]
I've found the image `arm32v7/openjdk` and this one can be installed but I need openjdk 13 and it's not available.

**Comment by wglambert** [comment]
JDK 13 reached EOL in March https://github.com/docker-library/openjdk/commit/8a2c63d97853e695d5d11e7fb7e512de5cfb767a 

We have a support matrix of the versions/variants https://github.com/docker-library/openjdk/issues/272
>- openjdk 13
>   - has reached end of life (https://en.wikipedia.org/wiki/Java_version_history) https://jdk.java.net/13/

You can still use that image by its sha hash though https://github.com/docker-library/repo-info/blob/68ee2d0de808d921b95850a85a87e6f900cbb5e6/repos/openjdk/remote/13.md but it will not receive updates, also it didn't support `arm32v7`

https://hub.docker.com/_/openjdk/ 
>Supported architectures: amd64, arm64v8, windows-amd64
