### ISSUE TITLE
Where are alpine images?

### ISSUE THREAD

**Issue by manvindar** [docker-library/openjdk#434]
we were using 8-jdk-alpine before but I dont seem to find alpine versions of jdk or jre post 11 ? shall I create one and merge?

**Comment by wglambert** [comment]
https://github.com/docker-library/openjdk/issues/272

**Comment by adamu** [comment]
@manvindar official but unsupported images are available: https://hub.docker.com/_/openjdk?tab=tags&page=1&name=alpine
