### ISSUE TITLE
Where are the 11-jre-alpine images?

### ISSUE THREAD

**Issue by kallisti5** [docker-library/openjdk#440]
Looking to upgrade our 8-jre-alpine containers to 11-jre-alpine, but not seeing any alpine-based containers for OpenJDK 11.
Anyone know what's going on?   There appears to be containers for OpenJDK 12+, and up until OpenJDK 8.

Lots of applications require OpenJDK 11, so it's a weird gap.

**Comment by wglambert** [comment]
https://github.com/docker-library/openjdk/issues/272 
It's not officially supported by the OpenJDK project https://github.com/docker-library/openjdk/issues/211#issuecomment-426708580, https://github.com/docker-library/openjdk/issues/212#issuecomment-424453577, https://github.com/docker-library/openjdk/pull/235#issuecomment-424599754

**Comment by kallisti5** [comment]
I have to ask though... why is OpenJDK 12+ supported on Alpine, and OpenJDK 8 is supported on Alpine, but 11 is not?
I feel like those comments might be based on old information.


I'm guessing it has something to do with "backporting Musl support to OpenJDK 11?.

**Comment by tianon** [comment]
8 and 12+ aren't supported - they are during the early access builds, but as soon as a version hits GA the alpine/musl builds go away.

If you check the timestamp on the images, you'll see they haven't been rebuilt recently.

**Comment by tianon** [comment]
See also https://jdk.java.net/15/:

> The Alpine Linux build previously available on this page was removed as of the first JDK 15 release candidate. It’s not production-ready because it hasn’t been tested thoroughly enough to be considered a GA build. Please use the early-access JDK 16 Alpine Linux build in its place.

**Comment by kallisti5** [comment]
Ok.. this all seems really dumb.
Guess i'm moving to adoptopenjdk/openjdk11:jre-11.0.9_11.1-alpine then.

**Comment by MoaazSuliman** [comment]
> Ok.. this all seems really dumb. Guess i'm moving to adoptopenjdk/openjdk11:jre-11.0.9_11.1-alpine then.
Hi Kallistil,
where can I find this one plz
adoptopenjdk/openjdk11:jre-11.0.9_11.1-alpine then.
