### ISSUE TITLE
Request to provide docker image for oraclelinux 7 with openjdk 11

### ISSUE THREAD

**Issue by nagasitaramthigulla** [docker-library/openjdk#444]
I see oraclelinux has images for jdk 15 and above.
can we get the image for jdk 11.

**Comment by wglambert** [comment]
8 and 11 were moved to consume from AdoptOpenJDK https://github.com/docker-library/openjdk/pull/322

We also have a version/variant support matrix  https://github.com/docker-library/openjdk/issues/272

**Comment by tianon** [comment]
This is a fair request for consistency's sake though - having the RedHat-produced AdoptOpenJDK-hosted binaries on top of Oracle Linux. :smile:
