### ISSUE TITLE
RaspberryPI3B cannot use this container

### ISSUE THREAD

**Issue by Conmi-WhiteJoker** [docker-library/openjdk#463]
root@raspberrypi:~ # sudo docker pull openjdk
Using default tag: latest
latest: Pulling from library/openjdk
no matching manifest for linux/arm/v6 in the manifest list entries

**Comment by yosifkit** [comment]
> no matching manifest for linux/arm/v6 in the manifest list entries

That is correct. Even though your pi 3 has a 64 bit chip, if it is running Raspbian, then it is an `arm32v6` user space. `arm32v6` is not supported by the openjdk project; see https://jdk.java.net/16/

> -	**Supported architectures**: ([more info](https://github.com/docker-library/official-images#architectures-other-than-amd64))  
	[`amd64`](https://hub.docker.com/r/amd64/openjdk/), [`arm64v8`](https://hub.docker.com/r/arm64v8/openjdk/), [`windows-amd64`](https://hub.docker.com/r/winamd64/openjdk/)
>
> \- https://hub.docker.com/_/openjdk

---

You **might** be able to run arm64 images by using `--platform=linux/arm64` on your `docker pull`
