### ISSUE TITLE
Merits of adding additional Windows Versions

### ISSUE THREAD

**Issue by AdrianDeWinter** [docker-library/openjdk#473]
As i continue to play around with Windows containers (i know, bad habit),
i feel the urge to complete the list of supported windows versions and variants (as i somewhat started with #472).

To that end, my question is:

**Is there any reason not to do it?**

The only one i could see, would be to not clutter up the list of available tags,
then again, looking at the docker hub page it seems that ship has sailed.

On the other hand, a more complete support for versions and variants of an OS that is already supported, but only partially,
can't be a bad thing (in my book).

These are the versions i would consider having (including those already supported):
- Server Core LTSC 2022
- Server Core LTSC 2019 -new
- Server Core LTSC 2016
- Server Core 20H2 -new
- Server Core 2004 -new
- Server Core 1909 -new
- Server Core 1809
- Server Nano LTSC 2022 -new
- Server Nano 20H2 -new
- Server Nano 2004 -new
- Server Nano 1909 -new
- Server Nano 1809
- Server LTSC 2022 -new
- Server 20H2 -new
- Server 2004 -new
- Server 1909 -new
- Server 1809 -new

I also added Server Core ltsc2019  for completeness sake, even though it is redundant to 1809.

I wanted to discuss this here first, before i start spamming potentially unwanted pull requests.

(Also, this Issue should probably be tagged something like "question" or "discussion", which i can't do)

**Comment by tianon** [comment]
Honestly, the experience (both of using _and_ of building) Windows based images is so bad we have a really hard time justifying the minimal matrix we currently support.

The non-LTSC releases are even worse on overall usability, so I have a very hard time justifying anything that helps legitimize them in general. :grimacing:
