### ISSUE TITLE
Security Vulnerabilities in image openjdk:8-oraclelinux8

### ISSUE THREAD

**Issue by garrit-schroeder** [docker-library/openjdk#475]
ELSA-2021-9344	glibc:2.28-164.0.1.el8	                                HIGH	
ELSA-2021-9344	glibc-common:2.28-164.0.1.el8	                HIGH	
ELSA-2021-9344	glibc-minimal-langpack:2.28-164.0.1.el8	HIGH

**Comment by wglambert** [comment]
Duplicate of https://github.com/docker-library/openjdk/issues/467
