### ISSUE TITLE
Can we get a JRE 17 image?

### ISSUE THREAD

**Issue by shankarRaman** [docker-library/openjdk#491]
We have a JDK image for Java 17 and we'd like a JRE image for Java 17.

**Comment by yosifkit** [comment]
> - openjdk 17
>    - See https://github.com/docker-library/openjdk/pull/322, the builds come from https://jdk.java.net/17/ which only offers the JDK
>
>\ - https://github.com/docker-library/openjdk/issues/272#issue-400499916

As far as we have been informed, the JRE is no longer a target of the openjdk project. "JDK 12+ has no official JRE build. The reason for this is that the jlink tool allows users to create precisely-targeted stripped JDK images for their applications, and this is IMO better for Docker than a JRE image."
