### ISSUE TITLE
Latest tag points to JDK 17, rather than JDK 18

### ISSUE THREAD

**Issue by robilad** [docker-library/openjdk#500]
The issue has been discussed on Twitter here: https://twitter.com/gunnarmorling/status/1526291112478003202?s=20&t=zW8mMKEII467LHzjCvLgrQ

**Comment by robilad** [comment]
It can also be seen here:

https://hub.docker.com/layers/openjdk/library/openjdk/latest/images/sha256-98f0304b3a3b7c12ce641177a99d1f3be56f532473a528fda38d53d519cafb13?context=explore

**Comment by tianon** [comment]
Oops, thanks @robilad!  Should be a trivial fix, will get a commit up ASAP.

**Comment by tianon** [comment]
I think we avoided this previously because `latest` was pointing at "latest LTS" but I agree it makes sense to go back to "latest release" (given #495).
