### ISSUE TITLE
Retiring OpenJDK Project Builds for JDK 11 and JDK 8

### ISSUE THREAD

**Issue by jerboaa** [docker-library/openjdk#505]
Hi!

This is a heads-up that we are going to retire "[OpenJDK Project Builds](https://adoptopenjdk.net/upstream.html)" for OpenJDK 11u and OpenJDK 8u. We plan to stop producing builds after the July 2022 CPU update (11.0.16 and 8u342 will be the last builds). Since we know that the docker library is using those for the `docker.io/library/openjdk:11` and `docker.io/library/openjdk:8` images, we wanted to give a heads-up that this is going to happen. Perhaps it would be best to remove the `11` and `8` tags (in October 2022, perhaps) as at that point these images would be out-of-date without recent security fixes. I see that the `docker.io/library/openjdk:17` tag points already to an outdated build (`17.0.2` over latest `17.0.3`).

We, Red Hat, have produced those builds as a service to the community for Linux x86_64, Linux aarch64 and Windows x86_64. Now with projects like [Eclipse Adoptium](https://projects.eclipse.org/projects/adoptium) which produce [Eclipse Temurin](https://adoptium.net/temurin/releases/) builds on a wider variety of platforms which are JCK tested there is a natural replacement for a vendor neutral OpenJDK build for the JDK 8 and JDK 11 code streams for the community to use. For the 17u code stream of the OpenJDK updates project the builds linked from the OpenJDK wiki are already Eclipse Temurin binaries and we'd like to make this consistent come October 2022.

**Comment by tianon** [comment]
Thanks for the heads up!  This is unfortunate, but not totally unexpected. :heart:

Response to #495 has been (understandably) pretty mixed so I'm sure this is going to go over similarly well among our users. :grimacing:

IMO this means we should seriously consider deprecating the image altogether since I'm not convinced there's a lot of value in _only_ providing the extremely-time-limited builds Oracle provides. :disappointed: :see_no_evil:

**Comment by theRealAph** [comment]
I believe it had got to the point where these builds weren't adding any value. 

The people have spoken. An independent survey [](https://snyk.io/jvm-ecosystem-report-2021/) of the popularity of OpenJDK builds showed that there were a few clear leaders. I have been told that they are fully TCK'd, so Java compatible. As far as I am aware, these builds are clean (or at least minimally patched) OpenJDK builds, so the OpenJDK Project builds were adding to the confusion.

**Comment by jerboaa** [comment]
@tianon 

> Thanks for the heads up! This is unfortunate, but not totally unexpected.
> 
> Response to #495 has been (understandably) pretty mixed so I'm sure this is going to go over similarly well among our users.

Yes, please inform maintainers of those stacks. Not sure who they are, so leaving this up to you.

> IMO this means we should seriously consider deprecating the image altogether since I'm not convinced there's a lot of value in _only_ providing the extremely-time-limited builds Oracle provides.

I tend to agree. Especially since if people use newer OpenJDK, there might be the expectation that older releases are being kept up to date as well, which is not the case for JDK 8, 11, 17 (starting October 2022 for 11 and 8; with 17 it's already the case).

**Comment by marchof** [comment]
Hi, while I see the point about popularity of other distributions for releases the openjdk images are a very convenient way to test OpenJDK EA versions (e.g. 19-ea).

**Comment by tianon** [comment]
Yeah, that's not a bad point -- I guess we could update to only consuming/"supporting" the EA releases (which aren't currently supported in any of the alternatives AFAIK, definitely not in their Docker images).  That would also make the Oracle rolling support window sting less (since it would necessarily last for the entire life of the EA builds for a particular release).

**Comment by tianon** [comment]
Thanks again for the heads up @jerboaa and @theRealAph -- it's really, really appreciated :heart:

(and for maintaining these builds for so long! :+1:)

**Comment by FibreFoX** [comment]
Sadly all the listed alternatives are not based on Debian, but on Ubuntu. Maybe adding Debian-based alternative would be nice (if there are any).
