### ISSUE TITLE
What is jessie-scm?

### ISSUE THREAD

**Issue by dale2k9** [docker-library/openjdk#51]
What's the source buildpack-deps:jessie-scm in the FROM?  I can't really use a docker that I can't trace the origins.

**Comment by yosifkit** [comment]
https://hub.docker.com/_/buildpack-deps/

**Comment by tianon** [comment]
https://hub.docker.com/_/buildpack-deps/ (specifically the `Dockerfile` links at the top)
https://github.com/docker-library/buildpack-deps/blob/a0a59c61102e8b079d568db69368fb89421f75f2/jessie/scm/Dockerfile
https://github.com/docker-library/buildpack-deps/blob/a0a59c61102e8b079d568db69368fb89421f75f2/jessie/curl/Dockerfile
https://hub.docker.com/_/debian/
https://github.com/tianon/docker-brew-debian/blob/89e5cad1df49d5d6778a9d7cb23d4de2639e1542/jessie/Dockerfile

See also https://github.com/docker-library/docs/blob/master/buildpack-deps/tag-details.md#buildpack-depsjessie-scm (and/or https://github.com/docker-library/docs/blob/master/java/tag-details.md)
