### ISSUE TITLE
openjdk-11: please do one more build to get patch 11.0.16.1

### ISSUE THREAD

**Issue by adonh** [docker-library/openjdk#512]
https://www.oracle.com/java/technologies/javase/11all-relnotes.html#R11_0_16_1

C2 Compilation Errors Unpredictably Crashes JVM:
Fixes a regression in the C2 JIT compiler which caused the Java Runtime to crash unpredictably.

**Comment by yosifkit** [comment]
They are no longer available as binaries from the group that was providing them before (links in https://github.com/docker-library/openjdk/pull/510). Please use one of the other JDKs that is able to provide up-to-date binaries. See the Docker Hub description for some options: https://hub.docker.com/_/openjdk/.
