### ISSUE TITLE
No image for 17.0.4-jre-slim-bullseye and 17.0.4-slim-bullseye

### ISSUE THREAD

**Issue by wobrycki** [docker-library/openjdk#513]
As in the title would it be possible to build slim bullseye images for java 17.0.4, please?
The last one I see is for 17.0.2 and the lib we are using needs 17.0.4 to work.

**Comment by wglambert** [comment]
See https://github.com/docker-library/openjdk/issues/272
There no longer exist "official" (or even semi-official) vanilla builds of OpenJDK 17 suitable for our use or for publishing as "OpenJDK" https://github.com/docker-library/openjdk/pull/495

**Comment by yosifkit** [comment]
The description on Docker Hub (https://hub.docker.com/_/openjdk/) has a list of a few alternative Official Images that contain the JDK.
