### ISSUE TITLE
openjdk alpine 3.17

### ISSUE THREAD

**Issue by zencircle** [docker-library/openjdk#518]
Hi,

openjdk:19-jdk-alpine3.16 is the latest available on dockerhub.
I am trying to see if I can build openjdk:19-jdk-alpine3.17 and looking for source Dockerfile. 
Can you someone please point me in right direction. I found source [here] (https://github.com/docker-library/repo-info/tree/master/repos/openjdk/local) which is debian based images

**Comment by wglambert** [comment]
The OpenJDK image is officially deprecated, but there are other Official Image alternatives
https://github.com/docker-library/docs/tree/master/openjdk#deprecation-notice
https://github.com/docker-library/openjdk/issues/505

https://github.com/docker-library/openjdk/pull/511#issuecomment-1221163646
>Again, once OpenJDK 19 hits GA, the intent is that we will drop support for it (and hopefully, variants like Temurin will pick it up).

Here's the Dockerfile for it from 7 months ago https://github.com/docker-library/openjdk/tree/68650ae15fc5a6e810edc04e03442d163d5c3c26/19/jdk/alpine3.16
https://jdk.java.net/19/ would have an "Alpine Linux/x64" build, but that would go away once a release hit GA
