### ISSUE TITLE
Upgrade for 8u342-jdk-slim-bullseye

### ISSUE THREAD

**Issue by moriahpopo** [docker-library/openjdk#530]
Are you going to release an upgrade image for JAVA 8 jdk-slim-bullseye? The latest one is 342. Thanks

**Comment by ArwynFr** [comment]
Also the openjdk image is 1 year old and has 3 critical CVEs, although based on debian:11-slim which was updated 6 days ago.

**Comment by ArwynFr** [comment]
See #505 this image is deprecated

**Comment by yosifkit** [comment]
Thanks @ArwynFr, that is correct.

https://github.com/docker-library/openjdk/issues/517#issuecomment-1287315959:
>See https://github.com/docker-library/docs/tree/3e16cb28c223c9fec85d7f2066dffa9d18240666/openjdk#deprecation-notice
>>This image is officially deprecated and all users are recommended to find and use suitable replacements ASAP. Some examples of other Official Image alternatives (listed in alphabetical order with no intentional or implied preference):
>>
>>[amazoncorretto](https://hub.docker.com/_/amazoncorretto)
>>[eclipse-temurin](https://hub.docker.com/_/eclipse-temurin)
>>[ibm-semeru-runtimes](https://hub.docker.com/_/ibm-semeru-runtimes)
>>[ibmjava](https://hub.docker.com/_/ibmjava)
>>[sapmachine](https://hub.docker.com/_/sapmachine)
>
> See https://github.com/docker-library/openjdk/issues/505 for more information.
