### ISSUE TITLE
Add JDK 23

### ISSUE THREAD

**Issue by robilad** [docker-library/openjdk#534]
We're in rampdown mode for JDK 22, so JDK 23 has now opened up for fresh development and the first build is out there on 

https://jdk.java.net/23/

**Comment by robilad** [comment]
Actually, it looks like it went up on Dockerhub 20 minutes ago. Self-closing.

**Comment by tianon** [comment]
Thank you @robilad!!  The proactive heads-up is absolutely 100% appreciated regardless :bow: :heart:
