### ISSUE TITLE
[openjdk] Provide a Debian package through equivs, so other Java packages can be installed

### ISSUE THREAD

**Issue by dereckson** [docker-library/openjdk#541]
I maintain an image based on OpenJDK image for Openfire XMPP server.

We've got the following issue reported by a contributor:

- Our image installs Openfire as Debian package
- The package needs an JDK as dependencies
- Any installation of a package AFTER the image is built leads to a broken state situation: "You might want to run 'apt --fix-broken install' to correct these."
- The original reporter suggests to fix this to publish a placeholder package using _equivs_ for the JDK installed.

The scenario to reproduce the issue is this one:

- Use library/opendjk as base image
- dpkg -i --force-depends <Java application package>.deb
- Launch the container
- Install vim to debug something

References:

- Upstream issue: https://github.com/nasqueron/docker-openfire/pull/6
- Reference for equivs: ttps://wiki.debian.org/Packaging/HackingDependencies

**Comment by yosifkit** [comment]
This issue was filed in the wrong repo, so I moved it over.

Quote from the [readme](https://github.com/docker-library/openjdk/blob/31aabd6e46aaed8d09c7d817dab58544f72b1de7/README.md#deprecated) is below. So, the `openjdk:17-jdk-slim-bullseye` image that you are `FROM` has not been updated in two years (and will not be updated).

> # DEPRECATED
> 
> This image is officially deprecated and all users are recommended to find and use suitable replacements ASAP. Some examples of other Official Image alternatives (listed in alphabetical order with no intentional or implied preference):
> 
> -	[`amazoncorretto`](https://hub.docker.com/_/amazoncorretto)
> -	[`eclipse-temurin`](https://hub.docker.com/_/eclipse-temurin)
> -	[`ibm-semeru-runtimes`](https://hub.docker.com/_/ibm-semeru-runtimes)
> -	[`ibmjava`](https://hub.docker.com/_/ibmjava)
> -	[`sapmachine`](https://hub.docker.com/_/sapmachine)
> 
> See [docker-library/openjdk#505](https://github.com/docker-library/openjdk/issues/505) for more information.
> 
> The only tags which will continue to receive updates beyond July 2022 will be Early Access builds (which are sourced from [jdk.java.net](https://jdk.java.net/)), as those are not published/supported by any of the above projects.
>
