### ISSUE TITLE
Import custom certificates

### ISSUE THREAD

**Issue by kink80** [docker-library/openjdk#65]
Is there an easy way to add custom certificates to the default Java keystore or maybe a post-install script that will enable this feature?

**Comment by md5** [comment]
I was able to do something like this successfully:

```Dockerfile
FROM java
RUN mkdir -p /usr/local/share/ca-certificates
COPY *.pem /usr/local/share/ca-certificates
RUN update-ca-certificates
```

Be aware that if you're using Boot2Docker 1.9.1 to build the image, you may run into this AUFS-related bug: https://github.com/docker/docker/issues/18180

**Comment by md5** [comment]
I'm assuming you're talking about CA certificates and not something else.
