### ISSUE TITLE
JVM version uses - which is not for GA releases?

### ISSUE THREAD

**Issue by gregw** [docker-library/openjdk#72]
The [rules for creating JVM versions](http://www.oracle.com/technetwork/java/javase/versioning-naming-139433.html) state that - should not be included in GA releases.  Yet these official docker java images report versions like `1.8.0_72-internal`  which can cause [problems](https://github.com/jetty-project/jetty-alpn-agent/pull/3) for systems that do not expect the '-'

If these images are to be official, it would be better to use a JVM that used _ and a label rather than -

**Comment by tianon** [comment]
Just to be clear, you're referring to the following output, correct?
```console
$ docker run -it --rm java:8-jre java -version
openjdk version "1.8.0_72-internal"
OpenJDK Runtime Environment (build 1.8.0_72-internal-b15)
OpenJDK 64-Bit Server VM (build 25.72-b15, mixed mode)
```

(I don't see anything related to this already filed at https://bugs.debian.org/src:openjdk-8 :disappointed:)

**Comment by gregw** [comment]
@tianon That is the output that I'm referring to, which contravenes Oracles policy which states: A GA (FCS) product version or build identifier **must not contain** a dash (-).     That is there emphasis not mine.

Sorry I didn't follow this upstream to debian.  Do you want me to raise an issue there?

**Comment by tianon** [comment]
If you don't mind, that'd be great! :+1: :heart:  We use their packages, so we're a bit beholden to their choices here.

**Comment by gregw** [comment]
raised https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=819522

**Comment by tianon** [comment]
Closing, since I don't think there's anything we can do here -- this is a quirk of the Debian package we consume, and thus we're at their mercy. :disappointed:

(Future interested travelers should follow / contribute to the discussion in https://bugs.debian.org/819522.)
