### ISSUE TITLE
Issue public key not available

### ISSUE THREAD

**Issue by michaelvoorjans** [docker-library/openjdk#75]
I'm getting this error in a Docker image based on Ubuntu 14.04:
W: GPG error: http://httpredir.debian.org jessie-backports InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B48AD6246925553 NO_PUBKEY 7638D0442B90D010
W: Ignoring Provides line with DepCompareOp for package python-cffi-backend-api-max
W: Ignoring Provides line with DepCompareOp for package python-cffi-backend-api-min
W: Ignoring Provides line with DepCompareOp for package python3-cffi-backend-api-max
W: Ignoring Provides line with DepCompareOp for package python3-cffi-backend-api-min
apt-get install -y openjdk-8-jdk=8u72-b15-1~bpo8+1 ca-certificates-java=20140324

**Comment by brendancf** [comment]
I'm getting a similar error when trying to install packages on the openjdk:8-jre image

```W: GPG error: http://deb.debian.org/debian stretch-updates InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B48AD6246925553 NO_PUBKEY 7638D0442B90D010
W: The repository 'http://deb.debian.org/debian stretch-updates InRelease' is not signed.
W: GPG error: http://security.debian.org stretch/updates InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9D6D8F6BC857C906 NO_PUBKEY 8B48AD6246925553
W: The repository 'http://security.debian.org stretch/updates InRelease' is not signed.
W: GPG error: http://deb.debian.org/debian stretch Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B48AD6246925553 NO_PUBKEY 7638D0442B90D010 NO_PUBKEY EF0F382A1A7B6500
W: The repository 'http://deb.debian.org/debian stretch Release' is not signed.
```

What was the solution to your issue?

**Comment by yosifkit** [comment]
@brendancf , from what I can see on the original post was that they were somehow using Debian apt repos on an image `FROM Ubuntu 14.04`.  And so they were missing the Debian apt signing keys (and probably should just be using Ubuntu repos and repos made for Ubuntu releases).  As for your issue, if you think that it is a problem with the `openjdk:8-jre` image, please open a new issue with any pertinent information (`docker version`, `docker info`, `docker run` line, etc).  Have you tried deleting the image and pulling it again?

**Comment by brendancf** [comment]
Thanks for the response @yosifkit     I opened an issue for the openkdk image  https://github.com/docker-library/openjdk/issues/159    I did try and remove the image and try again, still doesn't work.
