### ISSUE TITLE
Upgrade the base image to alpine:3.4

### ISSUE THREAD

**Issue by SirIle** [docker-library/openjdk#78]
The new alpine:3.4 base image should fix the issue with dns resolving not being able to use search-attribute in the etc/resolv.conf as described for example in https://github.com/gliderlabs/docker-alpine/issues/8. This would allow using this image as base for containers in Docker Cloud and on Kubernetes that rely on this functionality for the service discovery to work.

**Comment by tianon** [comment]
Thanks!
