### ISSUE TITLE
Where is Java 8u101 ?

### ISSUE THREAD

**Issue by anshnd** [docker-library/openjdk#81]
There was a Critical Patch Update from Oracle two weeks ago: http://www.oracle.com/technetwork/security-advisory/cpujul2016-2881720.html#AppendixJAVA with 7 CVE of score 7+.  It also adds new CA roots.  When will it be added here?

**Comment by yosifkit** [comment]
We have to wait for it to appear in jessie-backports; it is still only in unstable: https://security-tracker.debian.org/tracker/source-package/openjdk-8.

**Comment by xenoterracide** [comment]
is -alpine waiting on that too?

**Comment by tianon** [comment]
Alpine would be waiting on something else (possibly notification of the
issue) -- regardless, we're using the latest currently available version of
the packages for Debian and Alpine.

**Comment by anshnd** [comment]
docker run --rm -it java java -version
openjdk version "1.8.0_102"
OpenJDK Runtime Environment (build 1.8.0_102-8u102-b14.1-1~bpo8+1-b14)
OpenJDK 64-Bit Server VM (build 25.102-b14, mixed mode)
