### ISSUE TITLE
immutability expectation for tags?

### ISSUE THREAD

**Issue by jhovell** [docker-library/openjdk#83]
@tianon what should the developer's expectation be about immutability of tags? I am confused that there is no Java8 tag older than 3 days. https://hub.docker.com/r/library/java/tags/ 

Here's a version of Java that has been out for some time but the various tags show as last modified 3 days ago:

![screen shot 2016-08-11 at 12 00 41 pm](https://cloud.githubusercontent.com/assets/1376570/17601107/5c8cbfd6-5fbb-11e6-9ec6-513298e567af.png)

I think I am running into issues pulling images on hosts where there are containers that were built several weeks ago and containers built > 3 days ago that share "common layers" that aren't actually the same. I think what is happening is the newer images are using some layers that already exist on the host and pulling new ones as necessary, and the result is that some layers have changed that, causing a checksum failure. 

Is this expected? Is there any way to extend or build on any tag in this library and be guaranteed the layers won't change? Or is this a red herring and my problem is likely elsewhere? I am confused why so many tags always need to show as updated.

When pulling a particular newly built image on a host that had older images already present, I see a mixture of already existing layers and new layers that leads to a checksum failure and failure to pull the image:

```
docker pull my-registry/my-repo:my-tag
my-tag: Pulling from my-repo
5c90d4a2d1a8: Already exists 
ab30c63719b1: Pull complete 
c6072700a242: Pull complete 
5f444d070427: Pull complete 
620b5227cf38: Pull complete 
3cfd33220efa: Pull complete 
864a98a84dd2: Verifying Checksum 
734cc28150de: Download complete 
6b96ddca4c1d: Download complete 
345fe6818018: Download complete 
f95d3180c348: Download complete 
filesystem layer verification failed for digest sha256:864a98a84dd2bba52cf57d13161517ee01e2966e72c3ac842c6a3d49c07dcb37
```

I understand that a tag like openjdk-8-jdk is likely to change when new versions but openjdk-8u91 would be immutable?

Do I miunderstand how https://hub.docker.com/r/library/java/ is supposed to be used?

**Comment by dweomer** [comment]
@jhovell wrote:
> I understand that a tag like openjdk-8-jdk is likely to change when new versions but openjdk-8u91 would be immutable?

As tags are, at best, secord-order artifacts (i.e. an image alias) of repackaging first-order artifacts (i.e. then openjdk binary overlayed onto an operating system installation) into a container you **have to assume that the underlying container images will change** Tags are very much like branches in git, always pointing to the tip of a commit stream. If you need immutability then you should be pulling by image digest, aka the sha256 content-addressable identifier.

As for the behavior that you are seeing, I wonder if you are using a pull-through caching registry? Something like a [registry](https://hub.docker.com/r/_/registry/) mirror or [sonatype/nexus3](https://hub.docker.com/r/sonatype/nexus3/) perhaps? I have seen this kind of behavior sporadically in the past using docker 1.10 and 1.11 when using a pull-through registry.

**Comment by tianon** [comment]
Closing since the description given above is accurate and excellent. :+1: :heart:
