### ISSUE TITLE
How to rollback to previous version java image

### ISSUE THREAD

**Issue by OrNot** [docker-library/openjdk#84]
When I check the image from repository , the latest version (java 7 u111) leads my app broken. Is there any way to rollback to the previous image ?

Thanks a lot

**Comment by yosifkit** [comment]
The old tags are still available, so you can still use `java:7u101-jdk` for the jdk at that version. [Docker hub](https://hub.docker.com/r/library/java/tags/) lists some of the available, but is not paginated so does not show all of them.
