### ISSUE TITLE
Is it worth adding a working directory?

### ISSUE THREAD

**Issue by AKST** [docker-library/openjdk#85]
At the moment, there's no `WORKDIR` set in the any of the dockerfiles, is worth adding one for when you want a directory in the image to point directory on your filesystem? Like

```
# in docker file
WORKDIR /home
```

This way your docker container can access your files like this

```
docker run --rm -i -t -v $(pwd):/home ls
```

-------

> disclaimer I'm docker noob, so I may be oblivious to an draw backs this has

**Comment by yosifkit** [comment]
You can just add it to your docker run with a `-w=/home`.

**Comment by tianon** [comment]
Yeah, there's not really a good "default" we can apply that will be
reasonable and correct for a majority of image users.

**Comment by AKST** [comment]
@tianon Oh right, that's fair enough.

@yosifkit Thanks!
