### ISSUE TITLE
Alpine versions are not up to date

### ISSUE THREAD

**Issue by garricko** [docker-library/openjdk#86]
The 8-jdk-alpine and 8-jre-alpine are still on 8u92 while the regular openjdk images are on 8u102. Is there a way to keep them in sync so they get the latest patches at the same time?

**Comment by tianon** [comment]
Given that compiling OpenJDK is a very lengthy and involved process, we install OpenJDK from Debian and Alpine's downstream package repositories directly, so unfortunately, we can only currently provide whatever version our downstreams currently do.

It appears that Alpine's `edge` has `8.101.13-r1` (ref https://pkgs.alpinelinux.org/package/edge/community/x86_64/openjdk8 vs https://pkgs.alpinelinux.org/package/v3.4/community/x86_64/openjdk8), so it might be worth considering pulling in `edge` in our 3.4-based images to pull in that newer package.

@ncopa, think it'd be prudent for us to use the `@edge` syntax for pulling in a newer `openjdk8`?  Is there something else we ought to do instead? :innocent:

**Comment by ncopa** [comment]
Maybe we should upgrade openjdk8 in alpine 3.4-stable branch to 8.101.13? I assume it is security fixes there.

**Comment by tianon** [comment]
I think there's at least one security fix between the versions, yeah.

I wouldn't say no to updating 3.4-stable, but didn't want to presume that
was acceptable. :innocent:

**Comment by shatil** [comment]
It is deeply concerning for a "security-oriented" Linux distribution to not include any updates to mainstays like the JDK. I filed https://bugs.alpinelinux.org/issues/6388 requesting an update to the OpenJDK package.

**Comment by h0tbird** [comment]
@shatil Alpine edge is using IcedTea 3.1.0 (OpenJDK 8 u101b13 & IcedTea patches) the next release will be 3.2.0 and I don't know which version of OpenJDK will be included.

**Comment by albuch** [comment]
Pushing this as again as openjdk security fixes are available in Alpine edge and 3.5 since 09 February and no image updates here as the image is based on Alpine 3.4.

**Comment by yosifkit** [comment]
Closer in https://github.com/docker-library/openjdk/pull/103, so I am closing this.
