### ISSUE TITLE
Change default locale from en to en_US

### ISSUE THREAD

**Issue by jitendrachouhan** [docker-library/openjdk#87]
I have built image using openjdk:8, inside image content is basically a executable spring boot application, i have issue like always get en as locale. Can anybody point me how to change default locale of image?

**Comment by rotilho** [comment]
This should be handled in the startup script of your application http://stackoverflow.com/questions/8809098/how-do-i-set-the-default-locale-for-my-jvm

**Comment by tianon** [comment]
Thanks @rotilho! :heart:
