### ISSUE TITLE
SSL issues with alpine openjdk 8

### ISSUE THREAD

**Issue by imavroukakis** [docker-library/openjdk#89]
Hi there, I've got a very similar issue to https://github.com/docker-library/openjdk/issues/74 , I get `java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty`. 

However, the head-scratchy part is that, whilst my image works fine on my local docker instance, when I push it up to our private registry and attempt to run it, I get this exception. Where do you think the difference might lie?

**Comment by tianon** [comment]
That is kind of bizarre -- are you running with any bind mounts locally?

**Comment by imavroukakis** [comment]
No, nothing at all.

**Comment by imavroukakis** [comment]
using Docker 1.13.0-rc2-beta31 (14387) on OSX

**Comment by imavroukakis** [comment]
There is another subtle difference: On the remote system, my logs look like this (a fragment of)
```
redirect_uri=https%!A(MISSING)%!F(MISSING)%!F(MISSING)
```
on the local docker instance, it's fine
```
redirect_uri=https%3A%2F%2F
```

**Comment by imavroukakis** [comment]
Problem found, it was indeed a mount but it was invisible to me, as another process on our server took "care" of starting my container, and flattened /etc/ssl/certs ...
