### ISSUE TITLE
apt-get update error in Dockerfile based on openjdk:8-jre

### ISSUE THREAD

**Issue by YonghoChoi** [docker-library/openjdk#90]
When I create a Dockerfile based on openjdk:8-jre, and execute apt-get update command, the following error occurs.

```
W: Failed to fetch http://deb.debian.org/debian/dists/jessie-backports/main/binary-amd64/Packages  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Comparing Dockerfile with another version that works normally, i found that 8-jre added the following sentence:

```
RUN echo 'deb http://deb.debian.org/debian jessie-backports main' > /etc/apt/sources.list.d/jessie-backports.list
```

So I modified the path specified in `/etc/apt/sources.list.d/jessie-backports.list` as shown below and then executed `apt-get update`.

```
$ echo 'deb http://http.debian.net/debian jessie-backports main' > /etc/apt/sources.list.d/jessie-backports.list
$ rm -rf /var/lib/apt/lists/*
$ apt-get clean
$ apt-get update
```

**Comment by tianon** [comment]
In my personal experience, `Hash Sum mismatch` usually means one of the following:

1. temporary glitch in the mirror / CDN (or mis-generation of mirror files, in the case of non-Debian repositories)
2. temporary glitch in local network / firewall or route to mirror / CDN
3. glitch in APT cacher (flushing cache usually fixes this)

Have you tried again to see if the issue resolved itself?

**Comment by YonghoChoi** [comment]
This is the process that I tested.

1. Writing Dockerfile for testing
```
FROM openjdk:8-jre

RUN apt-get update
```

2. Build execution
```
docker build .
```

3. Error executing apt-get update
```
W: Failed to fetch http://deb.debian.org/debian/dists/jessie-backports/main/binary-amd64/Packages  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update' returned a non-zero code: 100
```

I ran the same test on three machines in different environments and the results were the same.

**Comment by singleseeker** [comment]
Any update?

**Comment by singleseeker** [comment]
Quick way to fix this. Just use your vpn software change your network env, like ExpressVPN.

**Comment by tianon** [comment]
Closing since this is a local environment issue, not an issue with the image.
