### ISSUE TITLE
Image for openjdk:8 isn't setting default java version to 8

### ISSUE THREAD

**Issue by BarakatX2** [docker-library/openjdk#93]
I'm not sure if I am doing something wrong or misunderstanding how the image is supposed to work, but when I type "java -version" in a container made from "openjdk:8", it gives me a Java 7 version. JAVA_HOME is set to the correct java 8 directory, but the java binaries are all 7. I had to add this to my docker file to set the default:

`update-java-alternatives -s java-1.8.0-openjdk-amd64`

Should this be necessary in the Dockerfile that is inheriting?

**Comment by yosifkit** [comment]
It seems to work fine on the base image:
```console
$ docker run -it --rm openjdk:8 bash
root@ae702975cda8:/# java -version
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2~bpo8+1-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)
```

I don't even see java 7 installed in the image:
```console
root@ae702975cda8:/# dpkg-query -l | grep -E 'jdk|java|jre'
ii  ca-certificates-java          20140324                   all          Common CA certificates (JKS keystore)
ii  java-common                   0.52                       all          Base of all Java packages
ii  libatk-wrapper-java           0.30.5-1                   all          ATK implementation for Java using JNI
ii  libatk-wrapper-java-jni:amd64 0.30.5-1                   amd64        ATK implementation for Java using JNI (JNI bindings)
ii  openjdk-8-jdk:amd64           8u111-b14-2~bpo8+1         amd64        OpenJDK Development Kit (JDK)
ii  openjdk-8-jdk-headless:amd64  8u111-b14-2~bpo8+1         amd64        OpenJDK Development Kit (JDK) (headless)
ii  openjdk-8-jre:amd64           8u111-b14-2~bpo8+1         amd64        OpenJDK Java runtime, using Hotspot JIT
ii  openjdk-8-jre-headless:amd64  8u111-b14-2~bpo8+1         amd64        OpenJDK Java runtime, using Hotspot JIT (headless)
```

Did you perhaps install something that pulled in java 7 and thus java 7 is a higher priority in the alternatives?  So yes, if you also install java 7, then you would need to update the alternatives to get java 8 as the default `java`.

We could adjust `PATH` to include `JAVA_HOME`, but I think it would be more useful for users to know that they accidentally installed java 7 in their java 8 project.

**Comment by BarakatX2** [comment]
> Did you perhaps install something that pulled in java 7 and thus java 7 is a higher priority in the alternatives?

This is the problem. I had the Dockerfile pointing to the deprecated java image that had java 7, and I upgraded by just replacing it with openjdk:8. I did not delete the container completely though, so the java 7 from the previous image was left over. So there is no issue with the image, thanks!
